### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by XspeedyGonz** [lenosisnickerboa/csgosl#100]
Followed instructions and have tried numerous times to install the package according to install instructions.
I have so far tried several disutrbutions but i cannot get it to work.

Only getting
can't find package Tk
    while executing
"package require Tk"
    (file "bin/csgosl.tcl" line 6)

Any ideas? i have installed 
Pre-Requisites according to instructions. Running Ubuntu 16.0.4

Best regards
Johan

**Comment by lenosisnickerboa** [comment]
Tested any of the confirmed working platforms Ubuntu 14.04, 16.04? 17.04
also works, running it as dev host. See
https://github.com/lenosisnickerboa/csgosl/wiki/Platform-support

**Comment by XspeedyGonz** [comment]
Well i have tried both 17 and 16.04 no luck on any.
Any other dependencies ? which is missing ?

**Comment by lenosisnickerboa** [comment]
Sorry, time flies... Solved yet? If not, keep reading...

Well, using any of the distros listed in the tested platforms should just work. I haven't done anything more than is detailed in the installation instruction.

I assume you executed "sudo apt-get install libtk-img lib32gcc1" without any errors?

Check this link [https://stackoverflow.com/questions/9200108/get-the-version-of-tcl-from-the-command-line](https://stackoverflow.com/questions/9200108/get-the-version-of-tcl-from-the-command-line)

bash-3.2$ tclsh
% puts $tcl_version
8.6
% info patchlevel
8.6.0

I get 8.6, you to?

Do you get the problems already the first time you start csgosl? That is, csgosl fails prior to installing the csgo server?

**Comment by XspeedyGonz** [comment]
Hi
info patchlevel gives me 8.6.5 might be the issue i would suppose.
And the problem occurs when i try to install so i'm not even able to run the install script.
Would love to run your system tho.

**Comment by lenosisnickerboa** [comment]
Sorry, but I don't know how to solve this. Googling for "can't find package
Tk while executing "package require Tk"" returns a lot of hits, tried these?

Do you run 32 or 64 bit Ubuntu? I have only tried 64 bit.

Is Windows an alternative? The windows version doesn't show these problems?

Anyone else as any hints how to solve this?

**Comment by lenosisnickerboa** [comment]
Closing, no reply.

**Comment by miguel456** [comment]
I know this was a long time ago, but for people running into this issue, run this command:
`sudo apt install tk`
Make sure you do `sudo apt update` first.

This only works for Ubuntu so far, haven't tested.

**Comment by labrok** [comment]
got a bunch of TK related stuff and ..... same error
