### ISSUE TITLE
Windows server installation problem

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [lenosisnickerboa/csgosl#101]
Hello there, i am having a problem while installing. I downloaded the zip file and when i run .vbs file, these errors came:

https://snag.gy/5Qa8tf.jpg

I tried both installation methods (installing csgo via steamcmd and updating existing installation) the results were the same.

**Comment by lenosisnickerboa** [comment]
Not sure I understand what "both installation methods" are and "installing csgo via steamcmd"... There's only one initial method described here [https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server](https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server) . Did you use this one?

If you create a new directory, e.g. c:\csgosl and install according to "To install on Windows:" in the link above you should be fine. Watch the [clip](https://raw.githubusercontent.com/wiki/lenosisnickerboa/csgosl/pics/install-windows.gif) linked in that description and do exactly the same.

Please let me know if this works for you.

**Comment by lenosisnickerboa** [comment]
Still having problems or is the problem solved?

**Comment by lenosisnickerboa** [comment]
Closing, no reply.
