### ISSUE TITLE
Can't host any workshop maps or collections

### ISSUE THREAD

**Issue by roxx77344** [lenosisnickerboa/csgosl#103]
![screenshot_2](https://user-images.githubusercontent.com/30882102/29148924-d81aee44-7d46-11e7-984d-56a77eda8b98.png)

When i try to host any workshop maps or collections the server start but doesnt download any workshop map and no one can enter on the server, already checked the api auth key and the gameserverlogintoken

**Comment by lenosisnickerboa** [comment]
Has this worked before or has it never worked?

**Comment by roxx77344** [comment]
it runs normally when i use mapgroups of normal maps (de_dust2, de_inferno etc) just doesnt work with workshop maps or collections

**Comment by CJNiiva** [comment]
Run dd2 or something, then use map workshop/xxxxxxxxx/your_map and let the server download the map, the server wont launch into a workshop map not downloaded before

Sendt fra min iPhone

Den 11. aug. 2017 kl. 18.22 skrev roxx77344 <notifications@github.com<mailto:notifications@github.com>>:


it runs normally when i use mapgroups of normal maps (de_dust2, de_inferno etc) just doesnt work with workshop maps or collections

**Comment by lenosisnickerboa** [comment]
What I meant was, did it once work hosting a **workshop map** and then it stopped working? Or are you trying to host a workshop map for the first time (using csgosl), i.e. it has never worked?

Also, did you read the instructions on the wiki [here](https://github.com/lenosisnickerboa/csgosl/wiki/Host-workshop-maps)? Do you have an API auth key?

_"To host a workshop map you need an API autorization key which is issued by Valve on Steam. Just head over to the Steam Registration page and generate a key. Copy and paste this key into the apiauthkey setting on the Steam tab."_

**Comment by lenosisnickerboa** [comment]
Still having problems or is the problem solved?

**Comment by roxx77344** [comment]
I gave up from fixing some days ago, but now i tried again and it worked, when i create a mapgroup and dont select any default map the server doesnt start or download any workshop map, but if i select a default map it works normally, thanks for the support.

**Comment by lenosisnickerboa** [comment]
OK, closing.
