### ISSUE TITLE
Server Keeps Insisting LAN Only

### ISSUE THREAD

**Issue by Nameback** [lenosisnickerboa/csgosl#104]
As the title states, no matter how many times I enter or save the config with my server key in it when I launch it insists there's nothing there. What am I missing?

**Comment by lenosisnickerboa** [comment]
You really need to provide more details than that. Have a look here for
some hints: https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug

**Comment by Nameback** [comment]
I realize I apologize I was simply frustrated. Here's what I've got.

csgosl version: 2.1.2
platform: windows 
describe problem: I've filled out the steam page(in CSGOSL) and have a valid server token input, but upon launching it claims "No Steam Account Token Specified"
does it happen every time or just once-in-a-while: Always
screen dump:
console output:
![console](https://user-images.githubusercontent.com/25129624/29426060-680eb17c-8353-11e7-8504-91c333d58f9a.JPG)

**Comment by lenosisnickerboa** [comment]
No worries, just needed some more info to help out :)

Have you double checked that your login token has not expired? (Mine had, just regenerated it).
If not go to [https://steamcommunity.com/dev/managegameservers](https://steamcommunity.com/dev/managegameservers) and if your token has expired simply hoover over it and select regenerat and enter the new token in csgosl. 

Also make sure to update the server (by pressing the "Update Server" button on the top of csgosl).

Please let me know if this works.

**Comment by lenosisnickerboa** [comment]
Closing, no reply.

**Comment by EarthsDefect** [comment]
Also having this problem, I tried new key, also if I click update server I get error "host error DDL_crosshairangle: not a client" so I update sourcemod and metamod and it fixes, but still get error about token. so until this is fixed I cant host online.

**Comment by EarthsDefect** [comment]
If I update metamod and not soucemod, fixes error "host error DDL_crosshairangle: not a client"

**Comment by lord-carlos** [comment]
I also get the `host error DDL_crosshairangle: not a client` bug. On two computer. One of them had CSGOSL working before. The other one is fresh. 

This is the only page on google that shows up when searching for this bug.

For me I only want a Lan server.

**Comment by msmaiaa** [comment]
for anyone having this problem, i fixed it by putting this command on the autoexec: sv_setsteamaccount "your token here"

**Comment by mayank-pq2q4** [comment]
Also, I must add this (in case it wasn't noticed), the banprotection must be enabled. Otherwise, it forces your server to go LAN.

`=======================================================================
Sourcemod banprotection is disabled, enforcing GSLT-less lanonly mode
=======================================================================`
