### ISSUE TITLE
Major Issue. Can't move restart loop.

### ISSUE THREAD

**Issue by Dreamin420** [lenosisnickerboa/csgosl#105]
Every time I load into the server there's a tab menu that shows up about 3 seconds in, I can't move and then it restarts onto a different map. I've tried resetting every setting back to default and I will try to reinstall everything. I'll let you know if it works.

Update: Tried reinstalling, no difference. I am trying to run the game on the same computer the server is on if that might make a difference let me know. Also have tried inputting steam keys and all that stuff and tried without them and there's no difference. Let me know if there's any file or screenshots you need to understand the problem better or to troubleshoot.

**Comment by lenosisnickerboa** [comment]
Some hints about reporting a bug here: [report a bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)

_"Every time I load into the server there's a tab menu that shows up about 3 seconds in"_

So you have installed csgosl with just default settings, that is, **nothing is changed in csgosl**. Then you start the server and connect to it from the csgo game client on the same machine you run the server and _"tab menu that shows up about 3 seconds"_ 

So the server starts ok and you can connect to it just that something weird happens in the game once connected?

Can you connect to other servers from the same machine?

What does the "tab menu" say? Is it an error message or what kind of message is it?

I really have no clue but perhaps a screenshot could help me or someone else running csgosl?

**Comment by Dreamin420** [comment]
csgosl version: 2.1.2
platform: windows
does it happen every time or just once-in-a-while: every time

The server starts alright, and I am able to connect to it. It's only when I get into game the bots are able to move and shoot however the players are stuck being unable to move, then the tab menu shows up with the "retstarting match" text + countdown at the top of the scoreboard and switches to the next map. I have tried changing and not changing settings.

**Comment by jensbhurtah** [comment]
@Dreamin420 did you manage to solve the problem and the server working correctly ?

**Comment by jensbhurtah** [comment]
cs go console : 
connect 192.168.100.5:27016
Connecting to public(192.168.100.5:27016) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
Connecting to public(192.168.100.5:27016) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
Connected to 192.168.100.5:27016

Counter-Strike: Global Offensive
Map: ar_baggage
Players: 1 (0 bots) / 10 humans
Build: 6878
Server Number: 2

SignalXWriteOpportunity(3)
Got pure server whitelist: sv_pure = 1.
ero-sennin connected.
ApplyGameSettings: Map ar_dizzy not part of Mapgroup 
Executing server command:
sv_skirmish_id 0
nextlevel ar_dizzy
map ar_dizzy reserved

---
Can't change replicated ConVar sv_skirmish_id from console of client, only server operator can change its value
Can't change replicated ConVar nextlevel from console of client, only server operator can change its value

**Comment by jensbhurtah** [comment]
Ok i managed to get it working.
Just change the maxrounds settings from o to a high number.

**Comment by Dreamin420** [comment]
Cheers mate!
