### ISSUE TITLE
Issue on run of csgosl.bat

### ISSUE THREAD

**Issue by Bobakanoosh** [lenosisnickerboa/csgosl#106]
https://i.imgur.com/XD7pnmw.png

**Comment by Bobakanoosh** [comment]
Fixed it by re-downloading, but still odd. Only thing I did was move it to a new directory after a server install.

**Comment by lenosisnickerboa** [comment]
Yes, really strange. Only thing I can think of judging from the error message is if you had messed around with the map groups editor. It's kinda buggy and e.g. doesn't handle spaces in map group names. Only moving the installation folder should not be a problem, I do it often during testing. Anyway, I close this issue and you can reopen it if you run into the same problem and can provide some more details.
