### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by Creston1** [lenosisnickerboa/csgosl#109]
When I start the server, it spews out at me that it's missing game mode "nameIDs, descIDs, and entry execs" for every single game mode, and even after putting my steam name and gameserverlogintoken, it syas I haven't entered them. I have literally every single LAN option turned off.

**Comment by Creston1** [comment]
The reason the server was going into lan mode is WS. I cannot find out why, as these are my settings.
https://i.imgur.com/rATD439.png

**Comment by lenosisnickerboa** [comment]
You have enabled "bad" sourcemod plugins according to the settings meaning csgosl will enforce LAN only mode to protect you from being banned, read more [here](https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod). This link explains why and recommends separate servers for "bad" plugins and public servers.

Does this answer address all your questions?

**Comment by lenosisnickerboa** [comment]
Closing, no answer.
