### ISSUE TITLE
Maps not saving once downloaded from workshop Collection

### ISSUE THREAD

**Issue by takeashot54** [lenosisnickerboa/csgosl#110]
Hi,

I tried downloading a map collection to host on my server but when i try to change the map and use the in game voting only the normal maps show up as options. When i looked in the map list in the server launcher the map from the collection i had added did not show in the UI. I am sure that the maps were downloaded by the server because they all worked when I tried switching through the console commands.

Any idea why they arent showing up in the maps section?

**Comment by lenosisnickerboa** [comment]
You did restart csgosl after having downloaded the maps? csgosl doesn't support adding new maps on the fly, it only picks up downloaded maps when you start csgosl.

Need more info to understand your problem, did it work to download the map and play on it but it just didn't show up in the map selector?

What map are we talking about?

Is this windows or linux?

Csgosl version?

And anything else you can come up with which might help...

**Comment by takeashot54** [comment]
My apologizes, they have appeared after I restarted csgosl.
