### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by kastorfever** [lenosisnickerboa/csgosl#111]
Hello, 1st time trying to get my way with dedicated servers so im very bad at it, im not sure if this is the right place to make some question, if its not please tell me so.
1st of all, can i use ebot with this ui?
if i can, how do i install it?
thanks a lot

**Comment by kastorfever** [comment]
I tried copying my configs to the folder of the ui on /server/csgo/cfg and still cant exec the config, its says "Unknown command "File"" i know the problem isnt the configs since i use them everyday on my online servers.

**Comment by lenosisnickerboa** [comment]
Never heard of ebot but I'll try to answer your question as best I can. Read a little about ebot but I'm still not exactly sure what ebot does so I can't really tell you to what extent csgosl and ebot go together. 

If ebot actually starts/stops your server:
==========================
You can use csgosl for the installation and configuration of your server and let ebot start/stop the server by pointing it to your installed and configured server.

If ebot connects to running servers:
=======================
Then you can fully use csgosl to install, configure and start/stop your server and just let ebot connect to it.

Anyone else who can shed some light on this?

**Comment by kastorfever** [comment]
well it connects to a running servers and do specific configuration for each match, the thing is that he isnt connecting at all to the server for some reason

**Comment by kastorfever** [comment]
But you have to sucessfull install the addon on the server, and i dont know how to do that on ur UI :s a simple copy paste to the addons folders should do the trick but no :s

**Comment by lenosisnickerboa** [comment]
csgsosl ("the ui") really only installs/updates, configures and start/stops the csgo server. Once installed you don't need to start csgosl if you don't want to. You can start the csgo server manually from command line. So I don't see how csgosl could in any way influence the way ebot works or doesn't work? 

Unfortunately I don't have time to dig into the ebot details but quickly browsing through the installation instructions there seems to be a lot more than just copy-pasting a folder to get it working. There's php installation, install dependencies, ebot starting, ... I read this page [how to install](https://github.com/deStrO/eBot-CSGO/wiki/Install). I guess you should be fine with just using the installed csgo server and installing ebot as described. Then you can choose to start the csgo server via csgosl ui or manually via command line options.

**Comment by kastorfever** [comment]
Ok, thanks a lot, ill try again i guess

**Comment by lenosisnickerboa** [comment]
Closing, reopen if you have more questions.
