### ISSUE TITLE
sv_lan Bug

### ISSUE THREAD

**Issue by izzQuantum** [lenosisnickerboa/csgosl#113]
If I try to start the server online with the setting "lan_only", which is deactivated in the program, it remains only in LAN mode (although I entered a GLST).
The following lines are output in the server console:
Initializing Steam libraries for LAN server
Logging into Steam gameserver account with logon token' 133742069XXXXXXXXX' - Logging into Steam gameserver account with logon token' 133742069XXXXXXXXX'.
Assigned persistent gameserver Steam ID[nvm boy].
VAC secure mode disabled.
GC Connection established for server version 636, instance idx 1
And in the console of the program sv_lan 1 is still started, although the config and the program have a different value.
I don't know what to do now, I guess it will be a bug of the program.

**Comment by lenosisnickerboa** [comment]
AFK but do you have bad sourcemod plugins enabled? In this case csgosl will
still set lanonly enabled to protect you from being banned.

**Comment by lenosisnickerboa** [comment]
Closing, no answer.
