### ISSUE TITLE
Workoshop maps "do not exist" problem

### ISSUE THREAD

**Issue by viper2097** [lenosisnickerboa/csgosl#117]
Hi there,
I followed the guide and set up everything correctly. (No spaces in file path, steam id set, api key set, token set)

When directly starting a workshop map by writing the workshop number in the map  field, everything runs fine.
But then I restart my pc / server, add the workshop map to a mapgroup and start that mapgroup with another map.
When then the workshop map should load as next map, I only get the message "this map does not exist".

Can you please help me? I can't find the failure...
Additional infos:
Windows 10
Same Computer as I'm playing
With standard maps, everything runs really fine
It never worked

Thank you very much in advance!

**Comment by lenosisnickerboa** [comment]
Two things to try...
Do you have spaces in the mapgroup name? That doesn't work either... should fix it some time...
If you select the downloaded workshop map as startmap in csgosl, does the map load then?

**Comment by lenosisnickerboa** [comment]
OK, that's good info. Don't have time right now to reproduce and troubleshoot but some more hints for now...

Can you see if the workshop maps you downloaded are still there? They should be present under <your installfolde>\csgosl\server\csgo\maps\workshop as folders with the same number as the workshop map id you used to download it.

Are the downloaded maps all available in the Maps tab in csgosl?

You could try this and report the result back:
- create a new mapgroup, e.g. maps1
- download two workshop maps as before
- restart csgosl, add the two workshop maps to mapgroup maps1 (just those two)
- select one of the workshop maps as startmap, see if map change works
- restart csgo server and csgosl, select the other workshop map as startmap and again check if map change works

Will be AFK for a while but will probably check back later today (it's 4pm here righ now)

**Comment by viper2097** [comment]
Yes, the downloaded maps are there where they should be.
Yes, the downloaded maps are available in csgosl.

I've tried as you said, the results are:
At your point 4: Start map loads, but map where it should switch to "does not exist"
At your point 5: Same as in Point 4

Here you have two screens:
![1](https://user-images.githubusercontent.com/35421711/34917540-0de70e2c-f948-11e7-97f1-6eb0cc6e10a5.JPG)
![2](https://user-images.githubusercontent.com/35421711/34917541-0e0321de-f948-11e7-8fc6-6b34b7e86bdf.JPG)

Don't hurry, I'm glad to get help. Thank you.

**Comment by lenosisnickerboa** [comment]
Yes, seems like csgo is looking for the maps in the wrong place... 

One workaround to try is to just copy (or move) the files under maps/workshop/<number>/ to directly under maps/ and see if that works. It's not a final solution but it would give me more input on how to solve the problem in csgosl. Perhaps csgosl should do this automatically for all workshop maps? I don't actually play csgo much so I haven't tried a map group with several workshop maps. I mostly run the stock maps.

Could you provide the links, or the workshop ids to the two maps you tried above (I see one of them is 1v1_metro.bsp) so I can play around with this when I have more time.

**Comment by viper2097** [comment]
Tried to copy the map to the \maps directory:
The map cannot be found when switching to it, and also the server can not start on it.
I know, it's strange, I wouldn't bother you if I would have found a soultion :-/.

Workshop Maps including Map votes and competive rules are the reason for useing a dedicated server to play, for all other we could use the gamefunctions itself....
Here you have the id's, but I don't hink that it is map specific...
![1](https://user-images.githubusercontent.com/35421711/34920372-004c4bf4-f972-11e7-8163-1acb8fa2cfc5.JPG)

**Comment by lenosisnickerboa** [comment]
Yep, strange... 

Got curious and tried this:
Created a new map group maps1
Added two workshop maps (which I had already downloaded months ago)
- [zoo](https://steamcommunity.com/sharedfiles/filedetails/?id=389175812)
- [dm_bf_noshahr_canals_d2](https://steamcommunity.com/sharedfiles/filedetails/?id=307529583)
Map change works without problems! Used plugin rockthevote to vote for next map and it directly changed to that map.

Two things:
1. Can you give the *two* ids of the maps you used above and I'll try to use the exact same maps to see if that triggers the problem.
2. Can you try downloading the two maps I used, create a new map group and see if that works for you? For this test please disable any other source mod plugins you have installed to avoid them interfering.

**Comment by viper2097** [comment]
Did as you said with zoo and dm_bf_noshahr_canals_d2, same result again.
I never heard from rockthevote before, I've enabled it in server settings, but it not seems to be activated?
However, rock the vote is (according to the itnernet) not for selecting next map after a match....
I haven't installed any sourcemod plugins at all.

The two id's I've used before are: 961263660 & 1258599704, but it's with all custom maps the same.

Two more things:
I'm not 100% sure, but I think it worked when I've installed csgosl the first time until I've restarted my computer where it runs on. But not fully sure.

(Tried this while typing:)
Before going to a dedicated server, I tried to host a local MP game with Workshop maps. For that, to access them, I've needed to edit the gameserver_modes.txt the follwoing:
Going all the way down to the map groups:

In CSGOSL, it looks like:
"Test2"
		{
			"name" "Test2"
			"maps"
			{
				"cs_cruise" "" //Workshop map
				"de_bank" "" //Original map
			}
		}

Before I needed to change this to:
"Test2"
		{
			"name" "Test2"
			"maps"
			{
				"\workshop\779308707\cs_cruise" ""
				"de_bank" ""
			}
		}

To make it work. (still changed to dedicated for easier setup reasons etc...)

**I've edited now this by hand, and it seemed to work!**

Could this have maybe been the solution? But why it works then at your computer without that modification?

**Comment by CJNiiva** [comment]
If you make csgosl change the direction of the workshop map, make it an option, dont change it, I have always used workshop maps and have had no issues

Sendt fra min iPhone

14. jan. 2018 kl. 21:36 skrev lenosisnickerboa <notifications@github.com<mailto:notifications@github.com>>:


Yep, strange...

Got curious and tried this:
Created a new map group maps1
Added two workshop maps (which I had already downloaded months ago)

  *   zoo<https://steamcommunity.com/sharedfiles/filedetails/?id=389175812>
  *   dm_bf_noshahr_canals_d2<https://steamcommunity.com/sharedfiles/filedetails/?id=307529583>
Map change works without problems! Used plugin rockthevote to vote for next map and it directly changed to that map.

Two things:

  1.  Can you give the two ids of the maps you used above and I'll try to use the exact same maps to see if that triggers the problem.
  2.  Can you try downloading the two maps I used, create a new map group and see if that works for you? For this test please disable any other source mod plugins you have installed to avoid them interfering.

**Comment by viper2097** [comment]
Did you tried it in the recent months?
As far as I know did CSGO a change in handling the maplists, e.g. so that mapcycle.txt is no used anymore etc...

I would find it strange if I'm the only one with that problem. Did two times a clean install and changed nothing...

**Comment by lenosisnickerboa** [comment]
I hear you @CJNiiva, these problems are very strange and I don't want to change something which will break stuff for all you others. csgosl has been downloaded several thousand times in the last couple of months and no one has reported similar problems.

Still, something isn't working and we need to sort out what's happening. I'm not aware of any changes which would break the old behavior.

@viper2097 you wrote:
"Did two times a clean install and changed nothing..."

Does this mean you did a complete reinstall to a new location, downloaded two workshop maps, created a new map group containing those two maps only, and then the problem occurred? You didn't edit any config-files (gameserver_modes.txt) manually?

**Comment by viper2097** [comment]
If i remember correctly:
I've downloaded Csgosl, installed it and then moved the folder. Everything worked, played around with the settings im csgosl and then tried to do a mapgroup with workshop maps. Did not worked.
Deleted the whole folder and downloaded csgosl again, because I thought that the folder movement was a problem.
Installed it and did not moved the folder. Changed nearly nothing in the csgosl gui and tried to do a mapgroup with two workshop maps.
I cant remember 100%, but I think it worked.
Shut then my Computer down went to bed and started it the next day and it stopped working. Can't explain why. Nothing changed.

If it would help you and you have the time, i could also show you everything on teamviewer...

Never changed any file manualy before the one I wrote in my last posting.

Maybe a Workaround for me would be, to make on steam a workshop collection and then load everytime the collection...

**Comment by CJNiiva** [comment]
Please keep in mind something funny happens to workshop maps if you turn off the server while a workshop map is being loaded

Sendt fra min iPhone

15. jan. 2018 kl. 22:34 skrev viper2097 <notifications@github.com<mailto:notifications@github.com>>:


If i remember correctly:
I've downloaded Csgosl, installed it and then moved the folder. Everything worked, played around with the settings im csgosl and then tried to do a mapgroup with workshop maps. Did not worked.
Deleted the whole folder and downloaded csgosl again, because I thought that the folder movement was a problem.
Installed it and did not moved the folder. Changed nearly nothing in the csgosl gui and tried to do a mapgroup with two workshop maps.
I cant remember 100%, but I think it worked.
Shut then my Computer down went to bed and started it the next day and it stopped working. Can't explain why. Nothing changed.

If it would help you and you have the time, i could also show you everything on teamviewer...

Never changed any file manualy before the one I wrote in my last posting.

Maybe a Workaround for me would be, to make on steam a workshop collection and then load everytime the collection...

**Comment by viper2097** [comment]
Intresting thing:
Did again a new install, only loaded two workshop maps. cs_militia and de_zoo and did a group with them.
When playing de_zoo, and at the end of the match I voted for milita, zoo is loaded again.
(no such map milita etc, loading zoo / he can't find the voted map, thats why he is loading the start map)
When i do a rcon changelevel de_zoo, it immediately works and zoo is loaded. (intresting)

at the end of this match then, at the mapvote, it doesnt matter if zoo or milita is selected. it is loading milita because he can't find both... (no such map zoo/militia, loading zoo / he can't find the voted map, thats why he is loading the start map again)

I don't know why but I can't now also change gamemode_servers.txt by hand like I did before. It is always changed by csgosl before starting the server... Don't know how I changed the gamemode_servers.txt before to make it work...
Would it possible for you, to add the option to write the mapgroups by csgosl alternative in this format:
	"mapgroups"
	{
		"testgroup"
		{
			"name" "testgroup"
			"maps"
			{
				"\workshop\1193865998\cs_militia" ""
                                "de_bank"
				"\workshop\389175812\de_zoo" ""
                                "de_dust2" ""
			}
		}
	}
}

instead of that one:
	"mapgroups"
	{
		"testgroup"
		{
			"name" "testgroup"
			"maps"
			{
				"cs_militia" ""
                                "de_bank"
				"de_zoo" ""
                                "de_dust2" ""
			}
		}
	}
}
I think that this maybe could really be the solution... Also from a logic point of view, this seems to make sence... (But still it makes no sence that "rcon changelevel de_zoo worked"...)

**Comment by lenosisnickerboa** [comment]
I just released a new csgosl version with a new option on the Application tab, generategamemodeservers, which can be used to control if csgosl regenerates gamemode_servers.txt when config is saved (or when the server is started). It's not exactly what you wanted but it allows you to have csgosl write gamemode_servers.txt once, then you can disable updates and edit the file manually and see if this makes everything work for you. Please report back if this solves your problem and I will consider making csgosl add the workshop path automatically (optionally of course @CJNiiva :) )

**Comment by viper2097** [comment]
Thank you very much for that fast response. I've tested now over an hour, but only with me alone. So I can't guarantee that everything is the same with more players then me on the server.

In gamemodes_server.txt I did now the following. Please notice that cs_militia and de_zoo is a workshop map, while de_bank is a originaly map by csgo.
By csgosl the mapgroup part of the file is created like this:
"mapgroups"
	{
		"testgroup"
		{
			"name" "testgroup"
			"maps"
			{
				"cs_militia" ""
				"de_bank" ""
				"de_zoo" ""
			}
		}
	}
}
For me, this is not working. The server can't find any maps to change to when the round is over and the next map is voted. It will always load the map with which the server was started.

I changed it now by hand (thanks to your update) to:
"mapgroups"
	{
		"testgroup"
		{
			"name" "testgroup"
			"maps"
			{
				"workshop/1193865998/cs_militia" ""
				"de_bank" ""
				"workshop/389175812/de_zoo" ""
			}
		}
	}
}


This works now without any problem. At the end of a match I can vote the next map and it is also loaded.

Here are three times the output of csgosl while changing map:
Switching from workshop militia to workshop zoo
---
Going to intermission...
CHANGELEVEL: Looking for next level in mapgroup 'testgroup'
Looking for next map in mapgroup 'testgroup'...
CHANGELEVEL: Choosing map 'workshop/389175812/de_zoo' (previous was workshop/1193865998/cs_militia)
CHANGELEVEL: ConVar 'nextlevel' is set, next map will be 'workshop/389175812/de_zoo'
CHANGE LEVEL: workshop/389175812/de_zoo
Bad SetLocalOrigin(912.356323,-1000.625732,17020.080078) on predicted_viewmodel
---- Host_Changelevel ----
*** Map Load: workshop/389175812/de_zoo: Map Group testgroupmaterial zoo/liquids/water_zoo_beneath needs to have a $fogcolor.
---

Switching from workshop militia to originaly bank
---
Going to intermission...
CHANGELEVEL: Looking for next level in mapgroup 'testgroup'
Looking for next map in mapgroup 'testgroup'...
CHANGELEVEL: Choosing map 'de_bank' (previous was workshop/1193865998/cs_militia)
CHANGELEVEL: ConVar 'nextlevel' is set, next map will be 'de_bank'
CHANGE LEVEL: de_bank
---- Host_Changelevel ----
*** Map Load: de_bank: Map Group testgroupMissing map material: TOOLS/TOOLSBLOCKBULLETS_CS
---

Switching from originaly bank to workshop zoo
---
Going to intermission...
CHANGELEVEL: Looking for next level in mapgroup 'testgroup'
Looking for next map in mapgroup 'testgroup'...
CHANGELEVEL: Choosing map 'workshop/389175812/de_zoo' (previous was de_bank)
CHANGELEVEL: ConVar 'nextlevel' is set, next map will be 'workshop/389175812/de_zoo'
CHANGE LEVEL: workshop/389175812/de_zoo
Bad SetLocalOrigin(902.530212,-520.584106,31660.845703) on predicted_viewmodel
---- Host_Changelevel ----
*** Map Load: workshop/389175812/de_zoo: Map Group testgroupmaterial 
---

As you can see, the paths for the workshop levels are now correct (workshop/389175812/de_zoo), before they were incorrect (only de_zoo).

From my point of view, this "fix" is fully logical and I can't understand why it is somewhere working without it.
Important is the correct typing:

 "workshop/1193865998/cs_militia"  <- working
"/workshop/1193865998/cs_militia" <- not working
"workshop\1193865998\cs_militia" <- not working
"\workshop\1193865998\cs_militia" <- not working


Thank you very much for your help so far, I hope that maybe this will also help someone who has this problem.
One more thing: I'm, running the server on the same computer as I'm playing, maybe this has something to do with it.

**Comment by viper2097** [comment]
So will there be an update?

**Comment by lenosisnickerboa** [comment]
Busy right now but added 3 new open issues for your suggestions. Stay tuned...
