### ISSUE TITLE
Add cmd cvar commands

### ISSUE THREAD

**Issue by jorisremandet** [lenosisnickerboa/csgosl#119]
Hello, it is possible to add cvar commands in cmd format like bot_pistols_only. I try to add in the all_modes with custom cvar and don't work.  For example adding a shortcut in the RconCLI should be a good idea :)

**Comment by lenosisnickerboa** [comment]
Hi, sorry for the long over due answer...

You should be able to add any custom cvar to e.g. the all_modes tab. Select 'New cvar', enter the fields, then select "Save all settings" and "Restart csgosl". Go back to the All_modes tab and the cvar should be there.

**Comment by lenosisnickerboa** [comment]
Closing, please reopen if you have more questions.
