### ISSUE TITLE
Include optional workshop map path in gamemodes_server.txt

### ISSUE THREAD

**Issue by lenosisnickerboa** [lenosisnickerboa/csgosl#120]
From previous post:

Important is the correct typing:
"workshop/1193865998/cs_militia" <- working
"/workshop/1193865998/cs_militia" <- not working
"workshop\1193865998\cs_militia" <- not working
"\workshop\1193865998\cs_militia" <- not working

Suggested by @Viper2097

**Comment by viper2097** [comment]
Are there any plans when this will be integrated?
Thank you

**Comment by lenosisnickerboa** [comment]
No, sorry. Haven't had time for csgosl for a while. Perhaps I will make an effort with this and some other requests during the weekend.

**Comment by lenosisnickerboa** [comment]
This support is now available in the 2.4 release. See the Application tab -> Troubleshooting. Try it out and see if it does what you want.

**Comment by viper2097** [comment]
Works now perfect. Thank you very much.
Will try it out for more hours and come back to you if there are occuring any problems.
