### ISSUE TITLE
sv_downloadurl / where to find

### ISSUE THREAD

**Issue by killingzoe666** [lenosisnickerboa/csgosl#124]
Hello,

small problem maybe. I tried to activate the fastdl for maps. But the servercfg is allways overwritten when i restart the server, thats ok... But where can i write into a cfg, or which field have i to fill it in?

Thx for reading
killingzoe

**Comment by lenosisnickerboa** [comment]
Sorry but csgosl will always rewrite the server cfg file, that's the way csgosl works. I haven't used the fastdl mod (which I assume you mean) so I don't know how to configure it. You can of course still use csgosl to configure stuff, then manually edit the files you want, and then start the csgo server via the generated start script found in the csgo installation folder (standalone-server-start.bat).  You need to enable this option in the Server tab under "Standalone script generation".

**Comment by killingzoe666** [comment]
THX for your Information. 

*CLOSED*

**Comment by lenosisnickerboa** [comment]
Read something about fastdl, is it what is described here: https://github.com/GameServerManagers/LinuxGSM/wiki/Fastdl

If so it would be pretty easy to options for this in csgosl, just to add the cvars 
sv_downloadurl "http://subdomain.domain.com/fastdl"
sv_allowdownload 0

Right?

**Comment by killingzoe666** [comment]
yes. CSGO limited the downloadspeed. So if the map is not in your client-folder, you will automatic download it from the Server with very low speed. Maybe the map will change and you are not finished downloading it. 
But when your activate sv_download with extern download-folder, you got fastdownload. But when csgosl rewrite the servercfg everytime, you cannot activate this feature. So maybe it is helpfull, to activate it in csgosl....

**Comment by EduardTheThird** [comment]
We play on a local network using workshop maps. 
There are network bandwidth limitations and our server is run offline.
To ensure that all players keep downloading the new maps, which are almost always larger than 64mb, we need to add the following to servercfg:

sv_downloadurl "http://<some url>"
sv_allowdownload 1
sv_allowupload 1

**Comment by lenosisnickerboa** [comment]
Just released 2.4.4 with fastdl support, check it out and tell me if it works for you.

**Comment by killingzoe666** [comment]
Good Job !

**Comment by EduardTheThird** [comment]
Brilliant, thank you 🐱
