### ISSUE TITLE
Are you up for hire?

### ISSUE THREAD

**Issue by elnoxx** [lenosisnickerboa/csgosl#125]
Hi,

I am Lenoxx owner of freecsgoservers.com currently we host over 500 CS:GO servers world wide.
I saw your project and i am interested in hiring you, to optimize your work for our needs.

I would be able to pay you 2000$ in total, and it would be in chunks once we reach certain milestones.
I could provide you access to a dedicated root server to test your work and progress faster.

We would need a similar system to csgosl but with a different user interface much more simple and limited for users (unlimited for admins).
The system would need to have a max server cap for each root server and once that is reached it would need to find a different root with the space on it since we have multiple root servers.
Servers would need to auto delete after a certain interval, unless certain player counts are met.

If this sounds like something you are interested in, please contact me on Steam or Skype and i will try to explain you our plans in more detail.

Steam: http://steamcommunity.com/profiles/76561197992753664/

Skype: ulm1221

Please write me once i accepted you to let me know its you, there would also be some kind of proof needed once a conversation has started, just to make sure its you.

Have a nice day :)

**Comment by lenosisnickerboa** [comment]
Answered on skype... Closing.

**Comment by elnoxx** [comment]
Hey, i have not gotten an invite on Skype, are you sure you added the right username?

Username: ulm1221
