### ISSUE TITLE
Add fastdl support

### ISSUE THREAD

**Issue by lenosisnickerboa** [lenosisnickerboa/csgosl#126]
Unclear what it means for csgosl, read this https://github.com/GameServerManagers/LinuxGSM/wiki/Fastdl

Would adding support for:

sv_downloadurl "http://subdomain.domain.com/fastdl"
sv_allowdownload 0

be enough?

**Comment by EduardTheThird** [comment]
To use fastdl, only the following changes to the server.cfg should be needed:

sv_downloadurl "http://example/csgo"
sv_allowdownload 1
sv_allowupload 1

The url for sv_downloadurl should be the only value that needs to be changed by the user.
