### ISSUE TITLE
can't disable mp_autokick

### ISSUE THREAD

**Issue by mtbeercan** [lenosisnickerboa/csgosl#127]
I noticed that the default is 1.  When you uncheck the box it goes to default, which is "1".  When you check the box it enables it... which is also setting it to "1".  Can you please make it so if you check the box you disable autokick and sets it to "0"?

**Comment by lenosisnickerboa** [comment]
Hi! csgosl uses the wrong default "0" for starters, should be "1". But when I change it in csgosl I don't see it changing in any config file so that seems to be broken as well. In what config file did you see changes?

**Comment by mtbeercan** [comment]
Haha, That's what I'm saying, it doesn't change it off of 1. I am in competitive when I see this issue, but the only place to modify this cvar is in the server tab of csgosl. Maybe it needs to be specifically in the competative mode config changes.

**Comment by lenosisnickerboa** [comment]
I think it just needs to be set in server.cfg, right? I'll keep the default to "0" meaning "don't kick" but you will be able to set the value now.

**Comment by mtbeercan** [comment]
O ok, are u going to release a new version for me to test? Or send it just to me?

**Comment by lenosisnickerboa** [comment]
It will be a new version

**Comment by lenosisnickerboa** [comment]
Released now, try it out and see if it works for you.

**Comment by mtbeercan** [comment]
Looks like unchecking it now makes it 0. Which is definitely what I want. But the game's default is 1, so idk if everyone wants  it likes thus, but it definitely fixed it for me. Thank you!

**Comment by lenosisnickerboa** [comment]
np, thanks for reporting, closing...
