### ISSUE TITLE
CHANGELEVEL: GetNextMap failed for mapgroup '<allmaps>', map group invalid or empty

### ISSUE THREAD

**Issue by jasonboche** [lenosisnickerboa/csgosl#129]
Great tool - thank you (sent donation this morning). 

Brand new server installed today.

Run settings:
gamemodetype: Classic Competitive

Maps:
mapgroup: allmaps
startmap: gd_rialto

I played the 1st map (gd_rialto). When the maxrounds was reached and the server tried to change to the next map, the server console spewed the following errors and the gd_rialto map was started again.

EVERYONE CAN BUY!
Going to intermission...
CHANGELEVEL: Looking for next level in mapgroup '<allmaps>'
Looking for next map in mapgroup '<allmaps>'...
CHANGELEVEL: GetNextMap failed for mapgroup '<allmaps>', map group invalid or empty
CModelLoader::Map_IsValid:  No such map 'maps\\\csgosl2.4.1config1atTueMar1318:57:45CDT2018(DONOTTOUCHTHISHEADERLINE!!!).bsp'
Invalid map '//csgosl2.4.1config1atTueMar1318:57:45CDT2018(DONOTTOUCHTHISHEADERLINE!!!)' included in map cycle file. Ignored.
CModelLoader::Map_IsValid:  No such map 'maps\\\DON'TEDIT,WILLBEOVERWRITTENNEXTTIMEYOUSAVE!!!.bsp'
Invalid map '//DON'TEDIT,WILLBEOVERWRITTENNEXTTIMEYOUSAVE!!!' included in map cycle file. Ignored.
CHANGELEVEL: Map list empty or failed to parse, using current map 'gd_rialto'
CHANGELEVEL: Looking for next level in mapgroup '<allmaps>'
Looking for next map in mapgroup '<allmaps>'...
CHANGELEVEL: GetNextMap failed for mapgroup '<allmaps>', map group invalid or empty
CHANGELEVEL: Not changing level, mp_match_end_restart is false, mp_match_end_changelevel is false and next is the same
EVERYONE CAN BUY!
Game will not start until both teams have players.
Game will not start until both teams have players.
EVERYONE CAN BUY!

Thank you,
Jas

**Comment by jasonboche** [comment]
[mapcycle.txt](https://github.com/lenosisnickerboa/csgosl/files/1809131/mapcycle.txt)
[maplist.txt](https://github.com/lenosisnickerboa/csgosl/files/1809132/maplist.txt)

**Comment by lenosisnickerboa** [comment]
First of all, thanks for the appreciation and donation! 

I will have a look at this when I get back from work this evening. Meanwhile I guess the problem would be solved by creating a new map group containing the maps you want and by selecting that map group.

**Comment by jasonboche** [comment]
Thank you for the response. Confirmed last night that creating a new mapgroup with 2 or all maps in it is a workaround. 

From what I've learned about mapgroups in the last few days, the issue here is in the file gamemodes_server.txt. The default mapgroup allmaps is instantiated in the file, however no maps are are added to it in the same file at the bottom.
![2018-03-14_8-42-32](https://user-images.githubusercontent.com/37353170/37405824-b58bff90-2763-11e8-81f2-785bde2f9ae2.png)

On a related note, is there a way within csgosl to specify map order in the mapgroup?

Thank you,
Jas

**Comment by lenosisnickerboa** [comment]
Thanks for finding the bug, will mark this thread as a bug and hopefully fix it soon.

No, sorry, no way to change map order. Will add this as an enhancement but no promises when (and if) this will be implemented. I've only got so much spare time... :)

**Comment by lenosisnickerboa** [comment]
Now fixed in release 2.4.2. Thanks for reporting!

**Comment by jasonboche** [comment]
Indeed fixed. Nice job!!
