### ISSUE TITLE
Color on Radar and scoreboard round indicator.

### ISSUE THREAD

**Issue by kastorfever** [lenosisnickerboa/csgosl#130]
Hi guys, i really need this fixed soon cause im hosting a tornment but i cant find answers anywhere :(
On the radar on the servers no1 can see different colors even with sv_competitive_official_5v5 1 and cl_teammate_colors_show 1.

Also players cant see the rounds indicator, i mean who survived, how the round ended etc.

help please, and please, please lol Thanks

**Comment by lenosisnickerboa** [comment]
This seems like a general csgo server related question? I don't have an answer for you and I guess you will get faster response somewhere else. 

Or can somebody help with this?

**Comment by kastorfever** [comment]
I use the same configs of some server providers and everything works just fine :s

**Comment by lenosisnickerboa** [comment]
Nothing new, reopen if still valid.
