### ISSUE TITLE
Server Install Application Error steamcmd.zip archive is corrupt or invalid

### ISSUE THREAD

**Issue by jasonboche** [lenosisnickerboa/csgosl#132]
I've tried this several times on different computers between yesterday and today and it's always the same result. When csgosl is used to install a new server, the steamcmd.zip file is corrupted during download and the server cannot be deployed.

The workaround is to manually download steamcmd.zip using a web browser from https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip, create the steamcmd folder under csgosl folder, place the steamcmd.zip file in the steamcmd folder, then click "Install server" in csgosl. csgosl will find the steamcmd.zip file and properly install the server.

Low priority for me but I just thought you might want to know something is fundamentally broken right out of the gate when this wonderful tool's purpose is to make it easy for anyone without the knowledge to create a CS:GO server. :)

Archive:  E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip,
        and cannot find E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip.zip, period.
Archive:  E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip,
        and cannot find E:/csgosl-windows/csgosl/steamcmd/steamcmd.zip.zip, period.
    while executing
"exec "$installFolder/bin/unzip" -o "$archive""
    (procedure "Unzip" line 9)
    invoked from within
"Unzip "$steamcmdFolder/$steamCmdArchive" "$steamcmdFolder""
    (procedure "UpdateServer" line 51)
    invoked from within
"UpdateServer"
    invoked from within
".title.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.update"
    (command bound to event)

![2018-03-14_11-08-58](https://user-images.githubusercontent.com/37353170/37414981-62dcfcda-2778-11e8-8c99-43857aaa1836.png)
[install.log.txt](https://github.com/lenosisnickerboa/csgosl/files/1811957/install.log.txt)

**Comment by lenosisnickerboa** [comment]
Thanks for reporting, will have a look. Reinstalled from scratch on linux, never tested windows.

**Comment by lenosisnickerboa** [comment]
Weird, just installed a server from scratch in windows, no problems?!?

```
20:58:26 Installing steamcmd.exe in D:/_NB/csgosltest/csgosl/csgosl/steamcmd...
20:58:26 Downloading steamcmd.zip...
20:58:26 Wget: http://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -> D:/_NB/csgosltest/csgosl/csgosl/steamcmd/steamcmd.zip
20:58:26 Wget: http://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -> D:/_NB/csgosltest/csgosl/csgosl/steamcmd/steamcmd.zip OK
20:58:26 Unpacking D:/_NB/csgosltest/csgosl/csgosl/steamcmd/steamcmd.zip
20:58:26 Unzip D:\_NB\csgosltest\csgosl\csgosl\steamcmd\steamcmd.zip -> D:/_NB/csgosltest/csgosl/csgosl/steamcmd
20:58:27 Unzip D:\_NB\csgosltest\csgosl\csgosl\steamcmd\steamcmd.zip -> D:/_NB/csgosltest/csgosl/csgosl/steamcmd OK
20:58:27 --------------------------------------------------------------------------------
20:58:27 Updating your server at D:/_NB/csgosltest/csgosl/csgosl/server [D:/_NB/csgosltest/csgosl/csgosl/steamcmd/steamcmd +runscript D:/_NB/csgosltest/csgosl/csgosl/bin/steamcmd.txt]```

Could you have a look at the downloaded steamcmd.zip (the one csgosl downloaded) and try do unzip it using some other tool (e.g. winrar) just to see if it is the download (wget) that creates a corrupt archive or if it is the unzip tool which has problems unpacking.

**Comment by jasonboche** [comment]
Win zip won’t open it. Complains it’s invalid or broken in some way. If I download the .zip file manually, winzip can open it just fine and I can see the steamcmd.exe file inside. And that is in fact the version that csgosl will find and is able to open in the workaround. 

I can keep trying on more windows machines to see if anything changes but thus far I’ve watched this fail 8 different times on 3 different Windows machines. A mix of brand new windows server 2016 and I also tried it on a few windows 10 machines.

**Comment by jasonboche** [comment]
I am no longer able to reproduce this issue tonight on build 2.4.3 as well as 2.4.1. On 2 machines everything is working fine now. Perhaps a download mirror was corrupt but I won't even waste time speculating. Closing and moving forward.
