### ISSUE TITLE
Error : child process exited abnormally

### ISSUE THREAD

**Issue by K3v1990** [lenosisnickerboa/csgosl#139]
Hi, im very new to linux, i tired to start the server and this error came up.
Any ideas?

child process exited abnormally
child process exited abnormally
    while executing
"exec "wget" "$url" --quiet -O "$filename""
    (procedure "Wget" line 8)
    invoked from within
"Wget "whatismyip.akamai.com" "$fileName""
    (procedure "net::externalIpAddress" line 4)
    invoked from within
"net::externalIpAddress"
    (procedure "ShowNetInfo" line 5)
    invoked from within
"ShowNetInfo "
    ("after" script)

**Comment by lenosisnickerboa** [comment]
could be that you're missing the wget command perhaps? try issuing the command wget and see if it is installed. 
You don't state which linux distro you're on but if it is ubuntu you will get the proper command for installing it if it is not installed.

**Comment by K3v1990** [comment]
Yup was missing something... Thanks!


/close
