### ISSUE TITLE
Saving edited configs?

### ISSUE THREAD

**Issue by virul3nce** [lenosisnickerboa/csgosl#140]
Whenever I manually edit a config and then change the server with csgosl it overwrites what I did. Is there a  way to circumvent this?

**Comment by lenosisnickerboa** [comment]
That's basically what csgosl does, manage (write) the config files for
people that can't or don't want to edit config files them self. I agree it
would be nice if csgosl somehow could keep manually edited stuff but I have
no idea how to implement that? If you have any ideas please share.

There's one setting in the application tab (don't remember the name AFK)
which will disable writing of gameserver cfg. It was meant as a temporary
fix for a problem while developing the proper fix.

**Comment by virul3nce** [comment]
Ahh I see, outside of having every config option available to the program I can't think of a solution off the top of my head lol

**Comment by lenosisnickerboa** [comment]
Closing, no way forward.
