### ISSUE TITLE
I'm having problems getting cksurf to work

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#147]
after reading about it on some forums it seems to be related to sourcemod 1.9, but since cksurf is abondoned by the dev, you could consider changing it to https://influxtimer.com/ I'm going to try the plugin now, seems really good

**Comment by lenosisnickerboa** [comment]
Had a quick look, says its much easier to install than ckSurf which sounds good. Try it and get back to me with the result and I'll add it.

**Comment by CJNiiva** [comment]
well, it works great:D

**Comment by lenosisnickerboa** [comment]
Closing, coming in release 2.6 in a couple of minutes.
