### ISSUE TITLE
Error after adding workshop map

### ISSUE THREAD

**Issue by exxis** [lenosisnickerboa/csgosl#149]
Hello,

after adding a workshop map I'm getting this error

https://i.gyazo.com/2696bbbda9bfe64558154e0ec1204a4a.png

and csgosl doesn't start anymore.

**Comment by lenosisnickerboa** [comment]
Could you give the url to the workshop map you're trying to add?
Is this the first workshop map or have you added others which have worked?
If you remove this workshop map does everything work again?

**Comment by lenosisnickerboa** [comment]
No answer, closing.
