### ISSUE TITLE
Crash after new csgo update related to GOTV

### ISSUE THREAD

**Issue by Roldhave** [lenosisnickerboa/csgosl#151]
After a CSGO update around the 10/sep/18 then when you open csgosl and have gotv enabled the server crash after it has completed the startup and then immediately crash it is related to GOTV

**Comment by spacecow123** [comment]
This is the only fix I've found so far https://forums.alliedmods.net/showthread.php?t=310599

**Comment by lenosisnickerboa** [comment]
Thanks for pointing out the fix but I guess we just have to wait for the fix. People in a hurry will have to patching the game files as described in the fix link.

**Comment by lenosisnickerboa** [comment]
This seems to have been resolved by Valve, please reopen if not.
