### ISSUE TITLE
Crash if workshop map is removed from workshop

### ISSUE THREAD

**Issue by viper2097** [lenosisnickerboa/csgosl#152]
Hi,
I have a lot of workshop maps on my server running. Last time we've played, the server choose a map which is not available anymore on the workshop.
Instead of switching to another map and giving some kind of information, the server just crashed.
not sure if that is something CSGOSL can manage or if it is outside your boundaries.

**Comment by lenosisnickerboa** [comment]
Do you still see this problem if you restart csgosl and select the "SaveAll" button and then make sure you restart the csgo server? Once the csgo server is started there's nothing csgosl can do. Restarting csgosl and resaving the config files should make the csgo server not see the missing workshop map and everything should work again.

**Comment by viper2097** [comment]
Hello and sorry for my late answer.
Unfortunately I can't reproduce the problem now, becaue I have removed the workshop map fast and restarted the server because we wanted to play. So I can#t add now a map that is not existing in the WS anymore to test it.

I have started the server for updating several times before we played (also clicked save all and restarted it).
I think, that CSGOSL should check if all maps are still available at the workshop when the programm (not the server) is started. If one or more maps was removed, they should also be removed from the server and a notification should appear.

I think that the problem in my case was, that CSGOSL did not checked that when the server was started, which lead to a servercrash.

**Comment by lenosisnickerboa** [comment]
Guess simply checking all local workshop maps by trying to download the corresponding URL https://steamcommunity.com/sharedfiles/filedetails/?id=<some id> would do the trick. It would add csgosl startup time though, I mean if it should be performed at startup it will take some extra time. I will add it as an improvement though. It will either be an option to include this check on startup (default off) or a dedicated button you need to actively press to have csgosl check this.

**Comment by lenosisnickerboa** [comment]
Closing this since it is now a separate issue #153
