### ISSUE TITLE
csgo-retakes plugin rule: retakes_pistolallocator and retakes_pistolallocator

### ISSUE THREAD

**Issue by borzaka** [lenosisnickerboa/csgosl#154]
> retakes_pistolallocator
> This plugin is an alternative to retakes_standardallocator (meaning: you shouldn't use both of these plugins, just one!) that makes every round a pistol round and lets players choose which pistol they have.

So, `retakes_standardallocator` and `retakes_pistolallocator` can't be checked at the same time.

It would be nice, if the csgosl would handle this.

**Comment by lenosisnickerboa** [comment]
Closing, coming in release 2.6 in a couple of minutes.
