### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by GonnaGoPostal** [lenosisnickerboa/csgosl#156]
I am new to linux and want to learn more and this has got me stumpped
I tried looking on google but there was very few links to choose from so I will post here in hopes of a solution. Linux Mint 19 w/cinnamon all newest updates. Is there something I am missing?

output from terminal follows
eragamesrv@eragamesrv:~/NewERA1/csgosl$ ./csgosl.sh
-->  ./csgosl.sh: line 18: tclsh: command not found
eragamesrv@eragamesrv:~/NewERA1/csgosl$ 

Line 18+ of csgosl.sh follows
while : ; do
    tclsh bin/csgosl.tcl "$@"
    rc=$?
    if [ $rc -eq 84 ] ; then
    Update
    fi
    if [ $rc -ne 42 ] ; then
    exit
    fi
done

**Comment by lenosisnickerboa** [comment]
Try this:

`sudo apt install tcl libtk-img lib32gcc1 lib32stdc++6`

From the [csgosl install guide](https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server)

**Comment by GonnaGoPostal** [comment]
Sorry had to go to work but just before I left tried all those steps again
and there was another pkg affecting and removed that and everything is good.

**Comment by lenosisnickerboa** [comment]
Which pkg? Might be good for others runni g into the same problem.

**Comment by GonnaGoPostal** [comment]
Start-Date: 2018-10-02  15:14:34
Commandline: /usr/bin/apt autoremove
Requested-By: eragamesrv (1000)
Remove: libc6-mips64-cross:amd64 (2.27-3ubuntu1cross1.2), libc6-mips32-mips64-cross:amd64 (2.27-3ubuntu1cross1.2), gcc-8-cross-base-ports:amd64 (8.2.0-1ubuntu2~18.04cross1)
End-Date: 2018-10-02  15:14:36
