### ISSUE TITLE
Sourcemod doesn't work

### ISSUE THREAD

**Issue by bl4ckOut** [lenosisnickerboa/csgosl#164]
Hi ..
I'm trying to get sourcemod working. I enabled sourcemod in the settings tab and also unchecked "lan only".  I saved all settings and updated the server with "Update server". The log during the update process also states that sourcemod is enabled. 
Futhermore all files and folders seem to be correct in '..csgo/addons'.

But when I  connect to my server and type 'meta list' it says "No active plugins loaded." 
So at least metamod seems working fine.

Setup:
Ubuntu 17.01 x64
User for server and csgosl: 'steam'.

Do you need any further logs ?

**Comment by lenosisnickerboa** [comment]
Well, what plugins have you enabled which you expect to show up when listed? Your description above only mentions enabling sourcemod. Also I would suggest starting out with lanonly enabled until you get things working locally, then disable lanonly to try it outside your lan.

**Comment by lenosisnickerboa** [comment]
Closing, no response.
