### ISSUE TITLE
mp_forcecamera can't set to 2

### ISSUE THREAD

**Issue by nixon123465** [lenosisnickerboa/csgosl#165]
I've add mp_forcecamera into custom convars, But everytime I set it to 2, it changes to 1 (default value) after I press the Save all settings button.

**Comment by lenosisnickerboa** [comment]
This is not obvious... the killcam option in the Run tab controls the mp_forcecamera variable. You can do the following:
Application tab: enable fullconfig
SaveAll+Restart csgosl
Run tab/Gameplay options: uncheck the right checkbox on killcam option line (this disables csgosl control of this option and lets you control it as a custom option)

**Comment by nixon123465** [comment]
ok, thanks I've changed it
