### ISSUE TITLE
Warmod Issues

### ISSUE THREAD

**Issue by cdterry98** [lenosisnickerboa/csgosl#166]
I've been using CSGOSL for about a week to do private matches with my buddies at LAN parties.  My issue is specifically with the Warmod plugin.  Whenever we startup a match it goes through warmup, we .ready, and then when knife round starts it scrambles the teams.  If I skip knife round and force start it still scrambles the teams.  I've gone through all the Warmod cfg's and CVars and there's nothing about randomizing teams.  I've used Warmod before on a server without CSGOSL and it didn't do this.  I'd appreciate any advice, maybe there's a command or cfg I'm missing.  Thanks.

**Comment by lenosisnickerboa** [comment]
Closing, no response.
