### ISSUE TITLE
Graphic overlay

### ISSUE THREAD

**Issue by Osberg** [lenosisnickerboa/csgosl#174]
Hi Lenosisnickerboa,

Was wondering a thing... no a issue, but not able to make a feature request. :) 

Could it be possible to get the same overlay when running ESL config as they are using today or is that to much work to do?? 

Frank

**Comment by lenosisnickerboa** [comment]
Hi!

I have no idea about what you're asking 😁 sorry... What overlay? Used
where? Can you describe a little more in detail, provide pictures/links?

**Comment by Osberg** [comment]
Hehe sorry if my description was to weak here. :) 

It could be a GoTV function I am not sure. :) But you can see here in the screenshoot, when a bomb is planted it shows like this and when a defuse is going also. :) 

Hope this makes sense... :) 
![img_20190126_183344](https://user-images.githubusercontent.com/23699885/51790725-5158d580-2199-11e9-878e-d02dcd99c680.jpg)
![img_20190126_183333](https://user-images.githubusercontent.com/23699885/51790726-5158d580-2199-11e9-9980-b227d16ecd14.jpg)

Could be me there is just not thinking about GoTV how that is.. :)

**Comment by lenosisnickerboa** [comment]
Ah ok, sorry but no, this is not anything which can be implemented i
csgosl.
