### ISSUE TITLE
Restart script

### ISSUE THREAD

**Issue by Osberg** [lenosisnickerboa/csgosl#181]
Hi Lenosisnickerboa, :)

Would it be possible to have this script build into the menu 

https://gamebanana.com/scripts/1404

It´s a restart 3 times scripts, could be nice to have under Rcon mode... But could that be done? :) 

Frank

**Comment by lenosisnickerboa** [comment]
Well sure, looks simple, just need time to do it. Labeling it enhancement and it will be delivered in the next release.

**Comment by Osberg** [comment]
It would be very nice... We are having a LAN part for the hole city next month, where I am gonna run the CS servers with your setup here, and the commands here could be very nice to have in the release. :)

**Comment by lenosisnickerboa** [comment]
Check out https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.6.8 and see if it works for you, just added it with very little testing done.

**Comment by Osberg** [comment]
I will do some test tonight, thanks for your help here. :)

**Comment by Osberg** [comment]
Ok I have tested now, but nothing happens when I hit the restart_game button in RCON mode. as you can see here
![image](https://user-images.githubusercontent.com/23699885/54949448-5e970400-4f3f-11e9-9f70-7515abd379e0.png)

I was in the game, but nothing happen in here. I was hoping it would say restart 3 times etc and then go go go. 

What can I do here to help to get this fixed :)

**Comment by Osberg** [comment]
Hi @lenosisnickerboa is there a update on this matter here?? 

Can I help out to get this fixed?? :)

**Comment by lenosisnickerboa** [comment]
Sorry, didn't see your reply until now. I really don't know how this script
is supposed to work, I just added the button and execution of the script. I
guess asking the guy who wrote the script may be a way forward.

**Comment by Osberg** [comment]
@lenosisnickerboa fair enough.... not sure if the guy still is doing this. :) 

I have asked in the stream community about it now. :) https://steamcommunity.com/app/730/discussions/0/1813170373212314123/

So lets see if somethings comes out here. :)

**Comment by Osberg** [comment]
@lenosisnickerboa i found out that the script is in general not working. :) but can you make some modification to the restart button in the rcon part? 

I made this script that is placed under the cfg folder where you have the autoexec etc files.

the restart_game.cfg file contains on this

mp_restartgame 3
say [Good Luck] & [Have Fun]

Also can you made some extra function here for function like knife first like they have on faceit and warmup funktion. I have attached config files here.

knife.cfg file:

mp_warmup_end  
mp_freezetime 8
bot_kick
mp_ct_default_melee weapon_knife
mp_t_default_melee weapon_knife
mp_ct_default_secondary ""
mp_t_default_secondary ""
mp_ct_default_primary ""
mp_t_default_primary ""
mp_startmoney 0
mp_roundtime 3
mp_roundtime_defuse 3
mp_give_player_C4 0
mp_restartgame 3

say ">LIVE - KNIFE FOR SIDE CHOOSE<
say ">PLAY FAIR!<

and warmup.cfg

mp_warmuptime 80280
mp_startmoney 16000
mp_freezetime 0
mp_maxrounds 0
bot_kick
mp_warmup_start 1
mp_ct_default_melee "weapon_knife"
mp_ct_default_secondary "weapon_hkp2000"
mp_ct_default_primary ""

mp_t_default_melee "weapon_knife"	
mp_t_default_secondary "weapon_glock"
mp_t_default_primary ""

if you make two buttons more like the restart_game it could be nice. 

would it be a idea that you reload a server.cfg without having to restart your server. 

So lets say you want to load a esl config or a custom config you could have a button that says 

exec esl2on2.cfg fx?? Could that be done?? :) 

hope this makes sense for you. :)

**Comment by lenosisnickerboa** [comment]
I guess adding a folder where you can put your cfgs and each cfg file would show up automatically as a button would solve your problems? Then you can have whatever cfgs you like and easily execute them via button pushes on the RCON tab? Right?

**Comment by Osberg** [comment]
@lenosisnickerboa that could be a great idea for sure. Would be very nice.

**Comment by Osberg** [comment]
But what I saw today was that they need to be in the cfg folder if you want to run the exec command, could not get it to work if the cfg file was in another folder.

**Comment by lenosisnickerboa** [comment]
That may be so but would the "automatic RCON buttons" solve what you need? Getting them to execute the scripts is something I will have to figure out :)

**Comment by Osberg** [comment]
@lenosisnickerboa that Is true... Could be a very nice option. ☺

**Comment by lenosisnickerboa** [comment]
OK, adding it to the enhancement list.

**Comment by Osberg** [comment]
Hi @lenosisnickerboa have you any idea on when you might have the time for this?? :)

**Comment by lenosisnickerboa** [comment]
Try out the new release 2.7. It contains "auto rcon buttons", see the release notes for more info, but you basically put your cfg files in a specific folder and they appear as buttons in the rcon tab. Try it and see if it works for you.

**Comment by Osberg** [comment]
@lenosisnickerboa I will give it a test run when I get home and can test it... It will be on Thursday. ☺

**Comment by Osberg** [comment]
The new rcon function is working like a charm... Great job @lenosisnickerboa

**Comment by lenosisnickerboa** [comment]
Great that it worked for you!
