### ISSUE TITLE
problem to create a public server with PPoE provider

### ISSUE THREAD

**Issue by beraldonico** [lenosisnickerboa/csgosl#182]
I have a internet provider that use PPPoE protocols and already had ask them to open a port for me. I configurated my internal port to connect to their external port but the server it's not showing up to my friends. The technical support of my provider told me that their port it's already open and them sugested that I'm having some issue with my internal port. Any idea of what can I do? I just want a server to have fun with my friends.
The server it's created because appears as LAN for me and I had the option "onlylan" not ticked.

**Comment by Osberg** [comment]
What are you running the server on?? Windows or linux?? if Windows have you open the ports in windows fw etc?? :)

**Comment by beraldonico** [comment]
I'm running it in a windows 10, the PC it's a DELL inspirion 15 gaming 7567. When asked I allow the program to go through the firewall and I just tryed to select manually the port in the config of the firewall. It's not working too.

**Comment by Osberg** [comment]
Did you open for tcp or UDP.

**Comment by beraldonico** [comment]
Yes, since I have a PPpoE provider I asked them to open one port, they opened the 36474 then I connected this external port to my internal 27015, that supposed to have the server. My provider told me that the external 36474 it's open and I'm having a internal problem. I already create a new rule on Win FW and tryed to ignore the provider port like the images below.

Router port forwarding:
![roteador](https://user-images.githubusercontent.com/39355783/54852917-06f16200-4ccd-11e9-8701-52a7063e9e99.png)

Win Firewall rule for TCP:
![FW_rule](https://user-images.githubusercontent.com/39355783/54853190-d6f68e80-4ccd-11e9-9f6a-975bd5958bfd.png)
I do have an other rule for UDP.

I'm going to ask a friend to try to create the server. He use the same PPpoE provider, I'm starting to think thar I have a problem with the router, because it's all correctly configured.

**Comment by Osberg** [comment]
Year all seems to be correct. :)

**Comment by lenosisnickerboa** [comment]
Closing, nothing new. Please reopen if csgosl related.
