### ISSUE TITLE
Host_Error: Crosshairangle: not a client

### ISSUE THREAD

**Issue by SaKeR2222** [lenosisnickerboa/csgosl#183]
hi there, when I run the server I get this error. Host_Error: DLL_Crosshairangle: not a client. what should I do?

**Comment by mm0ji** [comment]
I'm getting the same error after yesterday's update. Must be the EZ4ENCE music kit.

**Comment by spacecow123** [comment]
Update your sourcemod and metamod files

**Comment by SaKeR2222** [comment]
hi there, this did not fix the problem

**Comment by EarthsDefect** [comment]
csgo host_error DLL_crosshair, new install

**Comment by EarthsDefect** [comment]
reinstalling metamod, fixes the problem, but cant host online.

**Comment by EduardTheThird** [comment]
Getting the same issue since 29 March 2019.
Grown men are crying.
Cats are screaming.
And no one is playing CS:GO.
Fixing this might also fix a few hearts as well.

**Comment by vikizor** [comment]
I had the same problem, but manually updating sourcemod and metamod files worked. Hosting online is possible also.

Just download these files:
https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git970-windows.zip
https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6276-windows.zip

Extract them and copy over to your server folder.

**Comment by xShuuShii** [comment]
> I had the same problem, but manually updating sourcemod and metamod files worked. Hosting online is possible also.
> 
> Just download these files:
> https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git970-windows.zip
> https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6276-windows.zip
> 
> Extract them, copy over to your server folder and make sure you apply changes to earlier files.

Well I tried but failed. Maybe can you help me through teamview or make a video showing how to do it correctly ? I replace those in Mods.rar file and also extracted both of them in the server folder but still not working at all. Thx
Please contact me: akinobu160402@gmail.com | Facebook : Fb.com/16040xx

**Comment by mm0ji** [comment]
> Well I tried but failed. Maybe can you help me through teamview or make a video showing how to do it correctly ? I replace those in Mods.rar file and also extracted both of them in the server folder but still not working at all. Thx
> Please contact me: [akinobu160402@gmail.com](mailto:akinobu160402@gmail.com) | Facebook : Fb.com/16040xx

DO NOT extract the files into the server folder, this doesn't work. Install the new SM and MM files into the csgosl/server/addons folder.

**Comment by vikizor** [comment]
> > I had the same problem, but manually updating sourcemod and metamod files worked. Hosting online is possible also.
> > Just download these files:
> > https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git970-windows.zip
> > https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6276-windows.zip
> > Extract them, copy over to your server folder and make sure you apply changes to earlier files.
> 
> Well I tried but failed. Maybe can you help me through teamview or make a video showing how to do it correctly ? I replace those in Mods.rar file and also extracted both of them in the server folder but still not working at all. Thx
> Please contact me: [akinobu160402@gmail.com](mailto:akinobu160402@gmail.com) | Facebook : Fb.com/16040xx

Yes I can help you via Teamviewer. I will contant you in email later today.

**Comment by vikizor** [comment]
> > Well I tried but failed. Maybe can you help me through teamview or make a video showing how to do it correctly ? I replace those in Mods.rar file and also extracted both of them in the server folder but still not working at all. Thx
> > Please contact me: [akinobu160402@gmail.com](mailto:akinobu160402@gmail.com) | Facebook : Fb.com/16040xx
> 
> DO NOT extract the files into the server folder, this doesn't work. Install the new SM and MM files into the csgosl/server/addons folder.

And yes extracting directly to folder is a wrong way to do it. You will need to extract them into seperate own folders and then copy them from there. Paste into server folder and make sure you replace earlier files.

**Comment by jasonboche** [comment]
My csgosl server was dead with the same issue.

> I had the same problem, but manually updating sourcemod and metamod files worked. Hosting online is possible also.
> 
> Just download these files:
> https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git970-windows.zip
> https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6276-windows.zip
> 
> Extract them, copy over to your server folder and make sure you apply changes to earlier files.

Thank you **vikizor** documenting the fix for us. It worked for my server and I'm operational now.

**Comment by lenosisnickerboa** [comment]
Hi guys! Sorry for being so slow to fix this, haven't been playing csgo myself so I haven't noticed the problem. Anyhow, please find the 2.6.9 release with a fix for this problem. And thanks to @spacecow123  for finding the fix!

**Comment by lenosisnickerboa** [comment]
Closing, fixed.
