### ISSUE TITLE
Can't select custom maps in map groups

### ISSUE THREAD

**Issue by EarthsDefect** [lenosisnickerboa/csgosl#185]
Hi , I cant select the workshop maps in my custom map group, the images are too big and I can't click the box because I cant see it. I tried making the window bigger but didn't help, would be better if the maps were listed in the center of the screen.

Example: https://imgur.com/a/j3QXBp7

**Comment by lenosisnickerboa** [comment]
Could you provide a link to the workshop map in question so I can reproduce the problem?

**Comment by EarthsDefect** [comment]
Its pretty much most workshop maps I have. I put the maps I downloaded into maps folder and launch csgsl and can't click on most of them.
here are a couple.
https://steamcommunity.com/sharedfiles/filedetails/?id=122521875&searchtext=pool+day
https://steamcommunity.com/sharedfiles/filedetails/?id=122521875&searchtext=pool+day

**Comment by EarthsDefect** [comment]
I solved the problem by removing the mapname.png file from the maps folder.
