### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by AThePeanut4** [lenosisnickerboa/csgosl#187]
Small issues but nevertheless
The tooltip for the new rcon cfg buttons has a spelling error (it should be 'here' and not 'hear') and the period at the end is in the wrong place.
The tkpunish setting prevents players from playing the next round if they tk'd, so I think the tooltip would explain it better if it read "Prevent team killers from playing the next round" or something similar.
The autoteambalance tooltip could also maybe read "Automatically move players to balance teams".

**Comment by lenosisnickerboa** [comment]
Thanks for your findings, will fix. Many of the options I have never used
myself so any help on better tooltips is much appreciated! Keep'em coming!

**Comment by lenosisnickerboa** [comment]
Pushed fixes, will be part of next release.

**Comment by AThePeanut4** [comment]
The tooltip fixes for tkpunish and autoteambalance also apply on the server page, and I also found a couple others (all on the run page):
startmoney: I don't think the '<800-1600>' part is necessary, and the value can actually go from 0 to 65535 I believe.
mp_consecutive_loss_max: This is the limit to how many times the loss bonus will increase, but does not limit the loss counter itself. Not sure how to put this into a concise sentence, the new system is confusing.
cash_team_winner_bonus_consecutive_rounds: There's actually an error in the patch notes for the new money system, this setting should actually be cash_team_loser_bonus_consecutive_rounds (default 500), and a suitable tooltip would be "Amount the loss bonus increases by per loss".
However mp_consecutive_loss_max and cash_team_loser_bonus_consecutive_rounds I don't think are necessary to have displayed as most people would just want to change mp_consecutive_loss_aversion (ie switch between the old and new systems).
