### ISSUE TITLE
Cannot find the procedure start address SteamInternal_CreateInterface in DLL file "csgosl-windows\csgosl\server\bin\engine.dll"

### ISSUE THREAD

**Issue by filloppen** [lenosisnickerboa/csgosl#193]
Happens when I try to start the CS1.6 Server [https://imgur.com/aFkYjG7](url)

**Comment by lenosisnickerboa** [comment]
Can't follow the link and csgosl runs csgo, not CS1.6

**Comment by filloppen** [comment]
Sorry, I meant CSGO

**Comment by lenosisnickerboa** [comment]
Oh, all right.
You're not providing much detail.
Is this a new installation?
Has it worked before and stopped working for some reason? Like e.g. after updating the server?
Do you get the error when trying to start the server?
The usual fix for problems like these are "reinstall in another location, like e.g. c:\csgosl (ensure no spaces in the path)"

**Comment by filloppen** [comment]
First installation, downloaded the server files and set all the cfg files and tried to start the server, i will try in a bit

**Comment by filloppen** [comment]
> Oh, all right.
> You're not providing much detail.
> Is this a new installation?
> Has it worked before and stopped working for some reason? Like e.g. after updating the server?
> Do you get the error when trying to start the server?
> The usual fix for problems like these are "reinstall in another location, like e.g. c:\csgosl (ensure no spaces in the path)"

No, i still have this problem, I have the server on my E:\csgosl disk. So when i try too start the server that pops up. This is a fresh install I installed now today

**Comment by lenosisnickerboa** [comment]
Seems no one can help out with this one, closing.
