### ISSUE TITLE
rcon ingame?

### ISSUE THREAD

**Issue by hakooooom** [lenosisnickerboa/csgosl#195]
Hello,

i have a problem with rcon ingame he tells me this; Unable to connect to remote server (IP xxx.xxx.xxx:xxx). How can i fix this?

Greetings,
Hakooooom

**Comment by CJNiiva** [comment]
A temp fix would be to enter your local address to your rcon_address or whatever, if you want to have your friends being able to join you you must have cl_join_advertise 2 before you join the server, join from the public IP that you can find in several ways I like to just find the lowest ping server on the internet tab on the server browser, then while ingame you can easily find your local ip by opening the server browser, go to lan, then properties on your server and then you just copy your local ip. The reason I mentioned this is that if you just join your local server IP that would work, but your friends cant join you anymore via steam.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by hakooooom** [comment]
I got a dedicated server with csgosl of course as program,
need i sometimes add csgosl to mine firewall? 

![bfc7bc9cba876523a42403104e137952](https://user-images.githubusercontent.com/51494256/59135511-76e3c000-897f-11e9-9aad-8d2892e473ca.png)
![26201a4f07c30d38130e7c4296580d31](https://user-images.githubusercontent.com/51494256/59135515-79deb080-897f-11e9-9528-60ae32f5f546.png)

**Comment by AThePeanut4** [comment]
The same thing happened to me, I had to put 27016 as the overrideport (my server port was 27015) at the bottom and it worked.

**Comment by lenosisnickerboa** [comment]
I've seen this too and I also used 27016 as overrideport. Don't know why it **sometimes*
* happens. Right now 27015 works on the same machine?!?
Did this work for you @hakooooom ?
Can I close it?

**Comment by lenosisnickerboa** [comment]
No update, closing. Please reopen if you have new info.
