### ISSUE TITLE
Loss bonus tooltip and broken controls

### ISSUE THREAD

**Issue by AThePeanut4** [lenosisnickerboa/csgosl#196]
(This is all on the Run tab)
From the update on 2019/05/14, the loss bonus system was tweaked again, so the tooltip for mp_consecutive_loss_max is incorrect. The loss counter and loss bonus are both now limited by that value, and so the tooltip should read: "The maximum value for the consecutive loss counter"
The tooltip for killcam also is a bit misleading, I think it would be easier to understand if it was "Allow dead players to spectate the other team".
The default value for c4timer is also incorrect, it was changed from 45 to 40 in 2015. The control for that actually doesn't work as it gets reset to 40 on map load. I just looked through the settings and the controls for enablebunnyhopping (the tooltip here has a / instead of a %), mp_ autobunnyhopping, and airaccelerate also don't work, and also get reset on map load. I also couldn't figure out what cvars fraglimit and winlimit were supposed to manipulate, and they don't seem to have any effect on the actual game.

**Comment by lenosisnickerboa** [comment]
Tagged as bug + enhancement. Destined for next release.

**Comment by lenosisnickerboa** [comment]
Fixed, please open new issue if still a problem.
