### ISSUE TITLE
Retakes plugin not updated

### ISSUE THREAD

**Issue by mm0ji** [lenosisnickerboa/csgosl#197]
The retakes plugin isn't updated to the latest version so some players may spawn inside of the silo on Nuke.

**Comment by lenosisnickerboa** [comment]
The latest release according to github is 0.3.4 (https://github.com/splewis/csgo-retakes/releases), which is the one supplied in csgosl. 

Where do you see a newer version?

**Comment by lenosisnickerboa** [comment]
No reply, closing.
