### ISSUE TITLE
"Error: not_running" when trying to install new server on Windows

### ISSUE THREAD

**Issue by NotNite** [lenosisnickerboa/csgosl#198]
`not_running
find: '/I': No such file or directory
find: 'ExecutablePath=C:\\Users\\nited\\Downloads\\csgosl-windows\\cs go\\server\\srcds.exe': No such file or directory
not_running
find: '/I': No such file or directory
find: 'ExecutablePath=C:\\Users\\nited\\Downloads\\csgosl-windows\\cs go\\server\\srcds.exe': No such file or directory
    while executing
"exec "$serverControlScript-status.bat""
    (procedure "DetectServerRunning" line 6)
    invoked from within
"DetectServerRunning"
    (procedure "UpdateServer" line 9)
    invoked from within
"UpdateServer"
    invoked from within
".title.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.update"
    (command bound to event)`

**Comment by BobDylan10** [comment]
Looks like #108, check it out.

**Comment by lenosisnickerboa** [comment]
Had a look and it could be related. Did you try the suggested fix?

If you start a command prompt, can you run the commands **wmic** and **find**?

**Comment by lenosisnickerboa** [comment]
No reply, closing.
