### ISSUE TITLE
Bugs with workshop maps and map groups

### ISSUE THREAD

**Issue by zhulenghan** [lenosisnickerboa/csgosl#199]
First I wanna say that it's truly lucky that the problem of connection fails which happened on my Linux fixed when I use Windows,but new problems appear.
When using an workshop map id to start the server,the server will first open at actually dust2,but I later realized that it is downloading workshop maps.And after the download the server will automatically change the dust2 to which map I actually wanted it to be.Till now,the progression is perfect.
But when I close it and then open up csgosl again,it will crash with a cmd window.Now what I need to do is going to the task manager and shut down tclkit ,then delete the maps in the workshop folder or simply move to another folder,after this the tclkit will open and work well.If I still want to use the workshop map,I need to move the maps back to the workshop folder after the tclkit have been opened,and the server will just use the map and it's work well.

So it can actually work,but I have two questions.
1 Why I have to do this every time I use workshop map,and of course I can't use workshop map to create my own map group because the map will not show in the tclkit.

2 Can I make the workshop map like a normal map?When client connect ,must they download from the steam server,can they download from my sever(because my server is quicker than the steam in my country)

That's it. But anyway,it still can work.Thank you.

**Comment by lenosisnickerboa** [comment]
1. I really don't know what happens for you. This works fine for me and others. If you wait until all workshop maps are downloaded properly and then restart csgosl, does it work better?

2. No idea about this one, anyone?

**Comment by lenosisnickerboa** [comment]
No update, closing. Please reopen if you have new/more info.
