### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Darkarchon1972** [lenosisnickerboa/csgosl#200]
hi i have a csgosl problem, after installing and updating while online, on another machine, I now have copied entire directory to same location on new machine, but on startup I get a error msg saying "Error: couldn't open socket: No such host is known"

and this is the error log:

couldn't open socket: No such host is known. 
couldn't open socket: No such host is known. 
    while executing
"socket $target $port"
    (procedure "net::localIpAddress" line 2)
    invoked from within
"net::localIpAddress"
    (procedure "ShowNetInfo" line 6)
    invoked from within
"ShowNetInfo "
    ("after" script)

P.s this is done in this way because im offshore at the moment with very limited satellite internet bandwith, and we wanna end up playing "offline steam" Lan only with bots games

**Comment by lenosisnickerboa** [comment]
AFK, but maybe try disabling the showing of local and external IP adress in
the window title? I think this option is available in the applikation
settings tab if I remember correctly.

**Comment by lenosisnickerboa** [comment]
No reply, closing.
