### ISSUE TITLE
Can't connect console 

### ISSUE THREAD

**Issue by CriminalAcorns** [lenosisnickerboa/csgosl#201]
(couldn't open socket: connection refused)

**Comment by lenosisnickerboa** [comment]
Really? You expect me to guess your problem based on that?

Please read [Report a bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug) and try again.

**Comment by CriminalAcorns** [comment]
stfu

**Comment by spacecow123** [comment]
Imagine having to live your life this stupid lol

**Comment by lenosisnickerboa** [comment]
One born every minute

**Comment by CriminalAcorns** [comment]
I was kidding lmao
