### ISSUE TITLE
running on Manjaro issue

### ISSUE THREAD

**Issue by JackChestnut** [lenosisnickerboa/csgosl#202]
package tk, tcl and Img issues.
Before the 2.7.2 version, trying to run csgosl on Manjaro is failing because of the tk related problem. Now it seems my system still lack Img package, and I've tried many ways to do. So any more possible fix still, please?

**Comment by lenosisnickerboa** [comment]
Did you read the updated docs for manjaro?
https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server

Specially the part for manjaro:

The following packages are required on Manjaro, install them like this:
sudo pacman -Syu pamac
sudo pamac install tcl
sudo pamac build tkimg net-tools-debian-ifconfig

**Comment by xoth42** [comment]
On manjaro, trying to set up with csgosl, original problem still stands. pamac & tcl installed, guide followed up until that point, but I run into a problem with
 $ sudo pamac build tkimg net-tools-debian-ifconfig

Warning: Building packages as dynamic user
Warning: Setting build directory to /var/cache/pamac
Error: target not found: net-tools-debian-ifconfig

looking up net-tools-debian-ifconfig brings nothing on AUR.
out of spite I try to start csgosl and am met with this:

  ./csgosl.sh
can't find package Img
    while executing
"package require Img"
    (file "bin/csgosl.tcl" line 7)

Any response or direction for fix would help.
