### ISSUE TITLE
cash_team_winner_bonus_consecutive_rounds 500 default

### ISSUE THREAD

**Issue by jnexlevel** [lenosisnickerboa/csgosl#203]
cash_team_winner_bonus_consecutive_rounds has the tooltip like it is cash_team_loser_bonus_consecutive_rounds and is defaulted to 500 when it should be 0. Can you add the cvar cash_team_loser_bonus_consecutive_rounds that defaults to 500 and then set cash_team_winner_bonus_consecutive_rounds default to 0? Took me over a week of having economy issues in scrims to finally realize this command was backwards.

**Comment by lenosisnickerboa** [comment]
Will have a look

**Comment by lenosisnickerboa** [comment]
Fixed in release https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.7.3
