### ISSUE TITLE
Error: key "131972360" not known in dictionary

### ISSUE THREAD

**Issue by KuliuTho** [lenosisnickerboa/csgosl#204]
When trying to host a workshop map collection on my server the server wont even open and the csgosl application has an error that pops up which says **Error: key "131972360" not known in dictionary** 

`key "131972360" not known in dictionary
key "131972360" not known in dictionary
    while executing
"dict get $mapGroupsMapper $mapGroup"
    (procedure "GetStartServerCommand" line 55)
    invoked from within
"GetStartServerCommand"
    (procedure "StartServer" line 15)
    invoked from within
"StartServer"
    invoked from within
".title.startstop invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.startstop"
    (command bound to event)
`

**Comment by lenosisnickerboa** [comment]
Confirmed this problem and it was introduced when the randomstartmap option was added. If you try to deselect randomstartmap in the same section (right below the mapgroup and startmap options), does it work for you?

I will fix the issue but the above may work as a workaround til the fix is out.

**Comment by lenosisnickerboa** [comment]
Fixed in release https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.7.3
