### ISSUE TITLE
Use better weapon allocator for retakes

### ISSUE THREAD

**Issue by spacecow123** [lenosisnickerboa/csgosl#205]
This replacement for the weapon chooser lets you do pistol rounds as well as gun rounds.

https://github.com/BatMen/csgo-retakes-splewis-convar-weapon-allocator

I would do it manually but every time I update csgosl it overwrites it with the old retakes_standardallocator.smx and retakes_standardallocator.sp

**Comment by lenosisnickerboa** [comment]
Would this one replace the splewis retake plugin? I mean the splewis plugin is newer, the one you're suggesting hasn't been updated for 4 years. I don't use any of them so I have no idea. Simply replacing the splewis one with the one you suggest would be simple. Having both and being able to select one or the other would require some special handling of these plugins.

**Comment by spacecow123** [comment]
Oh didn't realize it wasn't being supported, let me find one that is still being updated.

**Comment by lenosisnickerboa** [comment]
Any update?

**Comment by spacecow123** [comment]
Yes sorry, I've been using this weapon allocator. https://github.com/shanapu/MyWeaponAllocator

**Comment by lenosisnickerboa** [comment]
So this is something you put on top of splewis retake plugin? Seems to be pretty straight forward to add shanapus plugin but there's a lot of config options which I suppose you need to edit in the config file for this plugin. Adding all of them to csgosl would take an entire page.

What do you think?

**Comment by spacecow123** [comment]
You actually use it instead of the gun allocator or pistol allocator plugin included with the retakes mod. It's up to you if you want to add it to csgosl but I am using it by adding it manually and it works great.

**Comment by lenosisnickerboa** [comment]
Added it in just released 2.7.5
