### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by vikizor** [lenosisnickerboa/csgosl#206]
Hello!

My server keeps crashing on startup and it last line that it gives says:

"Missing shutdown function sv.Init( bDedicated ) : sv.Shutdown()"

Any solutions for this?

![crash](https://user-images.githubusercontent.com/31817077/64112505-4f3ea100-cd90-11e9-9ef5-b21ddc62edf7.png)

**Comment by mmendesico** [comment]
For me also began to give this error today... already researched and tried to solve and was unsuccessful.... 
https://prnt.sc/p0pdw1

**Comment by lenosisnickerboa** [comment]
Fixed in [2.7.4](https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.7.4)
