### ISSUE TITLE
Plugins are unchecked when server is started

### ISSUE THREAD

**Issue by Blucass** [lenosisnickerboa/csgosl#209]
Server has been updated with banprotection enabled, however when those plugins are checked saving settings, updating server and starting server all cause them to become unchecked and not loaded. Is there a fix for this? (The two plugins in question are the ones below banprotection)
![Screenshot (69)_LI - Copy](https://user-images.githubusercontent.com/35420200/64195041-63f66400-ce78-11e9-964f-326414618818.png)

**Comment by lenosisnickerboa** [comment]
I think you may have misunderstood the banprotection setting described further https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod . With banprotection enabled the "bad plugins" below it will always be disabled. Read the help text very carefully before disabling banprotection.

**Comment by Blucass** [comment]
My bad, thank you
