### ISSUE TITLE
custom variable

### ISSUE THREAD

**Issue by LegoCraftNW** [lenosisnickerboa/csgosl#210]
Can you add custom variable line all configs
example sourcemod.cfg , server.cfg 
when I manually add it back to its original state

**Comment by lenosisnickerboa** [comment]
Please try to explain that in a little more detail, don't understand.

**Comment by LegoCraftNW** [comment]
when I edit the server.cfg its changing back. csgosl loads own settings. I want to edit by hand. When I press the save button on csgosl everything I do goes

**Comment by spacecow123** [comment]
![Capture](https://user-images.githubusercontent.com/26336759/64291931-de81bb00-cf2e-11e9-8d9e-46ddf1a8d172.PNG)
you want to use the highlighted tab for those variables, Then they wont get overwritten

**Comment by LegoCraftNW** [comment]
thanks for help. I never seen this place.
