### ISSUE TITLE
couldn't open socket

### ISSUE THREAD

**Issue by deicol** [lenosisnickerboa/csgosl#218]
couldn't open socket: connection timed out
couldn't open socket: connection timed out
    while executing
"socket $target $port"
    (procedure "net::localIpAddress" line 2)
    invoked from within
"net::localIpAddress"
    (procedure "ShowNetInfo" line 6)
    invoked from within
"ShowNetInfo "
    ("after" script)

**Comment by lenosisnickerboa** [comment]
I suggest you start by reading https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug to give me a chance to troubleshoot this.g
