### ISSUE TITLE
Autoupdate on start, makes sure you cant open the GUI anymore

### ISSUE THREAD

**Issue by HenneCuppens** [lenosisnickerboa/csgosl#22]
Whenever i tried to use the autoupdate on start function the program wont open anymore and it would give me a fatal error.

**Comment by lenosisnickerboa** [comment]
Hi,

I will have a look at this problem. I need some info first:

- Which version of csgosl are you running?
- Are you running the linux or windows version?
- What "fatal error message" are you getting?

BR
Lennart

**Comment by lenosisnickerboa** [comment]
Fixed in release 1.0.5

**Comment by lenosisnickerboa** [comment]
Fixed now, download 1.0.5.
Den 3 maj 2016 12:01 skrev "HenneCuppens" <notifications@github.com>:
