### ISSUE TITLE
Server update overwrites some config files

### ISSUE THREAD

**Issue by spacecow123** [lenosisnickerboa/csgosl#220]
When the server updates it overwrites all my pugsetup config files.

Also does the same thing with my databases.cfg

**Comment by lenosisnickerboa** [comment]
That's unfortunately "by design". When a sourcemod plugin is added to csgosl the configs will be overwritten by default configs. It's not an ideal solution but other than keeping copies of your altered configs and overwriting them after csgosl updates I don't know.
