### ISSUE TITLE
Why server dont change maps itself

### ISSUE THREAD

**Issue by gilobij** [lenosisnickerboa/csgosl#221]
Why server dont change maps, if where are no players except bots currently played?

I use Deathmatch game mode with my maplist. Have sourcemode enable with gunmenu enable, with filled bots
these cvars I DONT change, seems like it was changed by game mode
roundtime is 10
fraglimit 0
maxrounds 30
winlimit 30

**Comment by gilobij** [comment]
I edit game mode and game still set default value. WHY?

"bot_join_after_player" = "1" game replicated   

then I check value from RCON

**Comment by lenosisnickerboa** [comment]
Can't really help you with this one, sounds like a server issue? Not something csgosl does?
