### ISSUE TITLE
error after running several hours

### ISSUE THREAD

**Issue by gilobij** [lenosisnickerboa/csgosl#223]
The subsystem needed to support the image type is not present.
The subsystem needed to support the image type is not present.
    while executing
"exec "$serverControlScript-status.bat""
    (procedure "DetectServerRunning" line 6)
    invoked from within
"DetectServerRunning"
    (procedure "PeriodicWindowUpdate" line 2)
    invoked from within
"PeriodicWindowUpdate"
    invoked from within
"if 1 $body"
    (procedure "Every" line 2)
    invoked from within
"Every 2000 PeriodicWindowUpdate"
    ("after" script)

**Comment by lenosisnickerboa** [comment]
[Report-a-bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)

**Comment by lenosisnickerboa** [comment]
Closing, no input.
