### ISSUE TITLE
installing ws plugin

### ISSUE THREAD

**Issue by Zasheus** [lenosisnickerboa/csgosl#224]
I have installed a ws plugin manually, but the banprotection disabled automatically foreces lanonly. Is there any way to force this off without having people connect via VPN?

**Comment by lenosisnickerboa** [comment]
It's described here
https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod , it's
all controlled by the banprotection option.

When banprotection is disabled:

   - the FollowCSGOServerGuidelines option in core.cfg is set to "no" (to
   allow "bad" plugins to perform all actions)
   - lanonly mode is always enabled (+sv_lan 1)
   - no GSLT is supplied (+sv_setsteamaccount will NOT be set)
   - no API auth key is supplied (-authkey will NOT be set)

**Comment by Zasheus** [comment]
So there is no way of making it not put lan only

**Comment by lenosisnickerboa** [comment]
No, sorry. But why do you need to disable banprotection? I mean, if your not using the "bad" plugins and you have only added some other plugin yourself, why not just keep banprotection enabled?

**Comment by Zasheus** [comment]
I did add "bad" plugins, I just thought adding a different skin-changer plugin would work, but the GUI detected it was bad and put it in lan only. Thanks for clarifying anyway.

**Comment by lenosisnickerboa** [comment]
You could of course let csgosl install everything for you and then manage stuff manually, e.g. edit the config files yourself and start the csgo server manually. csgosl even creates the start scripts/bat-files for you containing the last settings you used so all you need to do is call the start script/bat-file. Of course, if you start csgosl again it will again enforce its rules and overwrite your config files.
