### ISSUE TITLE
Steam Settings not taking effect

### ISSUE THREAD

**Issue by Kowalski1700** [lenosisnickerboa/csgosl#225]
csgosl version: 2.7.7
platform: Linux
describe problem: I recently installed csgo(sl) in hopes of creating a private server for me and friends to 2v2 on, but the server doesn't want to accept the steam settings. I have tried generating a new gameserver account token, it has not expired, I have (supposedly) set up everything correctly in the steam tab of the GUI, but it's still not being listed or going public.
does it happen every time or just once-in-a-while: Every time
did this work before and stopped working: Has not worked at all (so far)
if it stopped working, what changed? updated csgosl? updated csgo server?
screen dump: 
![image](https://user-images.githubusercontent.com/48137471/68096418-6e77ae80-fe65-11e9-815c-3150db4be2a5.png)

console output: 
![image](https://user-images.githubusercontent.com/48137471/68096485-e3e37f00-fe65-11e9-9e64-d22a4ddc189a.png)

**Comment by Kowalski1700** [comment]
Tested it on Windows as well, same issue.

**Comment by lenosisnickerboa** [comment]
Did you read [Host-public-server](https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server) ? 
Specially the "Under the Server tab just make sure the lanonly setting is not ticked (it is as a secure default after installation)." part.

**Comment by Kowalski1700** [comment]
I did change it, figured out it was a result from the "banprotection" option in SourceMod from reading around on other issues. I got it working and running. Thanks for the help though :D
