### ISSUE TITLE
I have issue on csgosl start

### ISSUE THREAD

**Issue by Peter82kr** [lenosisnickerboa/csgosl#229]
wrong # args: should be "ServerSetUpdateServerOnRestartState ?value?"
wrong # args: should be "ServerSetUpdateServerOnRestartState ?value?"
    while executing
"ServerSetUpdateServerOnRestartState 6:00 9:00 12:00 15:00 18:00 21:00 00:00"
    ("eval" body line 1)
    invoked from within
"eval $onChangeCmd $value"
    (procedure "UpdateEntryChangedStatus" line 7)
    invoked from within
"UpdateEntryChangedStatus .config.n.server.scrollableitems.canvas.container.content.wrestartserverat.e "6:00\ 9:00\ 12:00\ 15:00\ 18:00\ 21:00\ 00:00" ..."
    (in validation command executed by .config.n.server.scrollableitems.canvas.container.content.wrestartserverat.e)

Windows Server 2019 standard.
Csgosl version 2.7.7

**Comment by lenosisnickerboa** [comment]
If this prevents csgosl from starting you need to edit the file csgosl\cfg\server.cfg and make sure the following settings are set as below:
autorestart "0"
startserveronstart "0"
restartserverat ""
updateserveronstart "0"
updateserveronrestart "1"

If csgosl starts, simply go to the Server tab and set "Startup server options" and "Restart server options" to default by clicking the eraser button to the right of each setting and finally select "Save all settings"

**Comment by Peter82kr** [comment]
But how to set restart server at desired time? If i set any hour i get errors preventing me to run csgosl.Sory for my english.

**Comment by Osberg** [comment]
So what you want is restart time function let's say st 02:00 the server will auto restart and update if there is a new update right?

**Comment by Peter82kr** [comment]
Yes but if i set this in csgosl it crashes csgosl.And when i try to restart csgosl crashes on start.

**Comment by lenosisnickerboa** [comment]
OK, reproduced this problem and it seems as long as you only state one time it works but if you state several times (space separated) you get the error you describe. 

These settings work:
![image](https://user-images.githubusercontent.com/16888566/69501613-e8500480-0f06-11ea-873f-1b44601925e0.png)

But if I add a second time, e.g. "22:06 22:08" you get the error you describe. Something broke in csgosl and I will fix it, marking it as a bug for now.

**Comment by Peter82kr** [comment]
Thanks.

**Comment by lenosisnickerboa** [comment]
Have a look at new release 2.7.8 which should fix the problem. Also found and fixed a bigger problem where this functionality had completely broken on linux. Thanks for reporting it!
