### ISSUE TITLE
I cant get more source mod plugins

### ISSUE THREAD

**Issue by HenneCuppens** [lenosisnickerboa/csgosl#23]
This might be just me doing something wrong, but i cant get my plugins working on the source mod. I found that there are 2 places in the files where it stores the source mods, might it be conflicting with each other?

**Comment by lenosisnickerboa** [comment]
I'm sorry but I'm just starting out with sourcemod and has really only used the sm_admin command and some sm_ settings. When I distribute metamod/sourcemod I only install them according to the instructions in respective package. Sourcemod is installed in <csgosl-directory>/server/csgo/addons/sourcemod. I will need some more information to be able to help you out, logs, error messages, which source mod you have problem with.

**Comment by HenneCuppens** [comment]
Hello,
Well i have with my old server, i couldnt update it and i stumbled into yours. I normally its just addind 2 files to the right folders but that didnt work this time (or im just forgetting a step)

**Comment by lenosisnickerboa** [comment]
As I said, haven't played around with sourcemod much. I tried moving some plugins from server/csgo/addons/sourcemod/plugins/disabled to server/csgo/addons/sourcemod/plugins (e.g. mapchoser and rockthevote), restarted the server (stop server, start server) and they where loaded and worked just fine. Can't remember the command for listing loaded sourcemod plugins but google it "and ye shall find..." If you run csgosl version 1.0.4 you can now easily become sourcemod admin, see https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Steam and fill in the three first entries on this config page.

**Comment by lenosisnickerboa** [comment]
I'm closing this question since I got no more replies. I will add improved sourcemod plugin support in a coming release, stay tuned...

**Comment by lenosisnickerboa** [comment]
Hi again,

Just released csgosl 1.1
<https://github.com/lenosisnickerboa/csgosl/releases/tag/v1.1> which fixes
a lot of problems with running sourcemod plugins on a windows server.
Actually csgosl 1.0.5 installed linux metamod/sourcemod binaries on the
windows server so it never could work. This is all fixed in 1.1.

Please let me know if this helped.

BR
Lennart
