### ISSUE TITLE
Server starts fine but when I join it crashes

### ISSUE THREAD

**Issue by Jettos** [lenosisnickerboa/csgosl#231]
Hey, 
this started happening not too long ago and I don't know how I can fix it. If there is a way to troubleshoot this issue it would be well appreciated.

**Comment by spacecow123** [comment]
Update your sourcemod to the latest version, I had to use the dev build to get it to work.

**Comment by lenosisnickerboa** [comment]
Thanks for the sourcemod hint. You can try disabling sourcemod in csgosl
first to ensure this is the real reason.

**Comment by lenosisnickerboa** [comment]
Check out the new release 2.7.9 with the latest sourcemod included. Please report back if this solves your issues.
