### ISSUE TITLE
loss bonus is not being calculated

### ISSUE THREAD

**Issue by mtbeercan** [lenosisnickerboa/csgosl#235]
I have been using this for a while, but I didn't catch this until now.

My server is not calculating loss bonuses.  No matter what, a loss give you 1400 no matter how many losses you have.  Everything is at default and it is a fresh install of Ubuntu 18.04.  Is this a settings issue that I am missing, or is this a steam issue?

The only 2 server cvars I know of are;
mp_consecutive_loss_max
mp_consecutive_loss_aversion
both of these are set to default settings of 4 and 1 respectively.

**Comment by mtbeercan** [comment]
Sorry, it looks like this is being addressed from #196.  If this is the case please feel free to close this and I apologize.

**Comment by lenosisnickerboa** [comment]
No worries, will close both once I get around to fixing it. Thanks for reporting the issue.

**Comment by lenosisnickerboa** [comment]
Had a look now and this is a mess, perhaps because I don't use it and don't understand it. Anyhow, it is described here and there seems to be more variables involved. https://steamdb.info/patchnotes/3643227/
Right now I don't see anything I can do in csgosl, seems the default values are correct?

**Comment by lenosisnickerboa** [comment]
Released https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.8, please reopen a new ticket if you still see problems.
