### ISSUE TITLE
HOW TO LEAVE THE ONLINE SERVER? I CAN NOT

### ISSUE THREAD

**Issue by olitheus** [lenosisnickerboa/csgosl#238]
csgosl version: 2.7.10
platform: windows 10 PRO
describe problem: I can't get the server online for my friends to get in.
![image](https://user-images.githubusercontent.com/34096069/73113530-31b2d500-3ef3-11ea-900a-be56fc8e320f.png)

_CONSOLE:
21:47:43: Workshop map validation status : 0
21:47:49 Local IP is 192....
21:47:49 Wget: whatismyip.akamai.com -> C:/server/csgosl/externalIP.txt
21:47:49 Wget: whatismyip.akamai.com -> C:/server/csgosl/externalIP.txt OK
21:47:49 External IP is 191.189.23...
21:47:50 Getting latest release...
21:47:50 Wget: https://github.com/lenosisnickerboa/csgosl/releases/latest -> release-info.txt
21:47:51 Wget: https://github.com/lenosisnickerboa/csgosl/releases/latest -> release-info.txt OK
21:47:51 Found latest release 2.7.10
21:47:51 Running latest release.
21:47:51 Creating assync update and start script C:\server\csgosl\bin\onstart.bat
21:47:51 Creating assync update and start script C:\server\csgosl\bin\onrestart.bat
21:48:19 Sourcemod functionality is disabled.
21:48:19 Executing command: "C:\server\csgosl\bin\server-start.bat" "C:\server\csgosl\server\srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 1  +mapgroup "<allmaps>"  +map de_dust2  +sv_setsteamaccount <AAAAAAAA> -authkey <AAAAAAAAAAA> -maxplayers_override 16  -tickrate 128      +hostname "mix" -port 27015 +sv_lan 0  
21:48:19 Creating command script C:\server\csgosl\bin\cmd-start.bat containing command "C:\server\csgosl\bin\server-start.bat" "C:\server\csgosl\server\srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 1  +mapgroup "<allmaps>"  +map de_dust2  +sv_setsteamaccount <AAAAAAAAAA> -authkey <AAAAAAAAAAAAA>  -maxplayers_override 16  -tickrate 128      +hostname "mix" -port 27015 +sv_lan 0_

![image](https://user-images.githubusercontent.com/34096069/73113613-86565000-3ef3-11ea-95d0-44f96b6104c9.png)

I OPEN VIRTUAL SERVERS...

I CAN'T GET IT NOW I NEED HELP

**Comment by lenosisnickerboa** [comment]
Removed all personal details (accounts and keys) from your question.

Have you opened ports in your router? Described here: https://portforward.com/counter-strike-global-offensive/

Hav you allowed connections in the Windows firewall?

**Comment by olitheus** [comment]
yes, open as router and modem ports. and also allow the connection of firewal, and disable firewal from windows

**Comment by Peter82kr** [comment]
You cannot connect over external ip?Its impossible.Join your own server via lan (lan tab).Others can join over external ip if you set up router and modem properly.

**Comment by lenosisnickerboa** [comment]
@olitheus , did this solve the problem? If so, close the issue.

**Comment by lenosisnickerboa** [comment]
closing, no reply
