### ISSUE TITLE
rcon error when using binded ip.

### ISSUE THREAD

**Issue by Peter82kr** [lenosisnickerboa/csgosl#239]
I cannot connect by rcon using "rconcli" tab when using option "bind ip" in "server" tab.

**Comment by lenosisnickerboa** [comment]
OS? Win/Linux?
Does it work if you don't use the bindip option?
Why do you use the bindip option? 
If you use bindip you also need to enter the same IP in overrideip in the RconCli tab, did you do that?

**Comment by Peter82kr** [comment]
OS Debian 10.2.
It works when i dont use bindip option.
I use bindip when on computer with 2 network cards but i returned to to standard setting.
I dont set ip in rconcli tab.

**Comment by lenosisnickerboa** [comment]
Ok, so if you want to get this working I would suggest setting the same ip
address in the bind and rcon fields.

**Comment by Peter82kr** [comment]
Thanks for info.I know now how to use it properly.

**Comment by lenosisnickerboa** [comment]
Closing, problem solved, right?
