### ISSUE TITLE
friendlyfire dosn't change

### ISSUE THREAD

**Issue by rerdoze** [lenosisnickerboa/csgosl#24]
Hello, i'm trying to set the friendlyfire option to 1, but the server always start up with 0, i tried to change it checking the box option, changing the value on gamemodes_all.cfg, and even tried changing the values on gamemode_competitive_server.cfg, but it dosn't work. Can you help me?

**Comment by lenosisnickerboa** [comment]
Sent an email with some questions, did you get it? Didn't get a response so I can't investigate this further. Will have to close if I don't here from you.

**Comment by rerdoze** [comment]
Sorry, but i didn't get your email, can you try sending it again? I'm on college at the moment, so i can't really confirm it to you, but i'll check it when i get home.
Thanks

Date: Tue, 10 May 2016 14:39:14 -0700

**Comment by lenosisnickerboa** [comment]
No worries, could be me slipping on the send button. Couldn't find the email in the sent folder...

Anyway, my questions where something like:

- In what way does it not work? I tried starting the server both with friendlyfire enabled and disabled and I when enabled it I see friendlies taking damage (blood + message about not hurting teammates) and when I disable I don't see any blood of messages when firing at friendlies.
- What do you mean "the server always start up with 0"?  Do you mean it behaves like friendlyfire is always disabled or do you check the config files in the file system?
- Do you run the server on windows or linux? 

I tried this on the latest release (1.1) and it would be great if you update to this release and tell me how it works for you.

**Comment by rerdoze** [comment]
Sorry for not answering before, after updating it's working very well , and thank you for having added the option to set warmuptime and freeze time directly on the Run tab .

And thank you also for creating the application, it helps a lot when creating a server.

**Comment by lenosisnickerboa** [comment]
Glad to hear it works now!
