### ISSUE TITLE
Interface lags on Windows

### ISSUE THREAD

**Issue by AntonivkA** [lenosisnickerboa/csgosl#240]
On the Windows Server 2016 through the RDP, the program interface terribly lags. very hard to work with such lags.
any other program runs smoothly.
if necessary, I can record a video.

**Comment by lenosisnickerboa** [comment]
Never tried csgosl via RDP but if it's laggy there's really not much I can do. You can try lowering resolution and bitmap depth to possibly get it running smother. Or try using another remote desktop solution like https://www.nomachine.com/ which I have had very good experience with (using it with csgosl on one of my linux servers and also on windows).

**Comment by AntonivkA** [comment]
This is not a RDP or screen resolution issue. I tried other remote control programs, the result is the same as through the RDP. There is a gigabit network between my home PC and the server, so the problem is not with the remote access program or the network. Only the csgosl interface lags, any other interface of any program works well and smoothly. One gets the feeling that csgosl requires 3D rendering to draw the interface. There is no video card on my server.

**Comment by lenosisnickerboa** [comment]
Right, I don't have a clue about any 3D rendering requirements. I have been
running csgosl in various VMs without any virtual 3D HW. csgosl is just a
standard tcl/tk app, not using any fancy stuff, just standard widgets. So,
can't really say why you experience such graphical issues. Haven't heard
about anything similar before. I will try it out on a VM with windows 10,
connecting with RDP, and get back to you.

**Comment by lenosisnickerboa** [comment]
Tried, as I said in previous post, win10 via RDP and everything worked just fine. All default settings in RDP client.

**Comment by AntonivkA** [comment]
The problem is solved, everything began to work well.
The problem was in Windows Server 2016 build 14393, which had problems with displaying and rendering the interface. It turned out that this problem was not only mine. It was decided to upgrade to Windows Server 2019 and everything began to work well.
Thanks for the help! And you can add to Readme that the csgosl does not work correctly on Windows Server 2016 build 14393 due to the fact that there are serious bugs in this build of the operating system.

**Comment by lenosisnickerboa** [comment]
Thanks for getting back with that information! And good to hear it worked out for you.  Added docs about it here: https://github.com/lenosisnickerboa/csgosl/wiki/Platform-support
