### ISSUE TITLE
Server autostart.Feature request.

### ISSUE THREAD

**Issue by Peter82kr** [lenosisnickerboa/csgosl#241]
Do its possible to add option "autostart cs go server on system start".From time to time i got powerloss on my hardware, and if im not home nobody boots up server back up online without my intervention.Do its possible add option to start server on system start?If its possible anyone in home can push computer power button and launch the server back online.Thanks.(sorry for my english)

**Comment by lenosisnickerboa** [comment]
Can't really do it just in csgosl, but it can be accomplished by generating standalone server scripts from csgosl and having the OS start it when the OS starts (you where running some kind of linux, right?). Go into the server tab and enable these options and then press SaveAll

![image](https://user-images.githubusercontent.com/16888566/75609483-50ffdc00-5b09-11ea-8e6f-3c33b0363959.png)

This will generate some scripts, one called standalone-server-start.sh, in the csgosl folder where you have installed csgosl (e.g. /home/somename/csgosl/csgosl/standalone-server-start.sh).

You can test just calling the script directly to ensure it starts the server for you. There's also a stop script, and you can optionally include server update before starting the server.

Finally, call this script from some linux startup script and you should be good to go.

**Comment by Peter82kr** [comment]
Yes im using debian for cs go.Where are located generated scripts?

**Comment by lenosisnickerboa** [comment]
Csgosl generated scripts are in <csgosl install folder>/csgosl
