### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Peter82kr** [lenosisnickerboa/csgosl#242]
Today i entered on server based on debian 10.3 and i have this error:

not_running
9424: Nie ma takiego procesu
not_running
9424: Nie ma takiego procesu
    while executing
"exec "$serverControlScript" status"
    (procedure "DetectServerRunning" line 8)
    invoked from within
"DetectServerRunning"
    (procedure "PeriodicWindowUpdate" line 2)
    invoked from within
"PeriodicWindowUpdate"
    invoked from within
"if 1 $body"
    (procedure "Every" line 2)
    invoked from within
"Every 2000 PeriodicWindowUpdate"
    ("after" script)

I dont know it is related to csgosl or csgo but if i maximize csgosl i cant do anything in program.Everything is inactive.Cant switch tabs.Probably csgosl crashed.When i pressed "ok" on popup window with error csgosl backs to live.Server itself was probably intact.No crash in server console.I got pi-hole server on same mashine.Im not pro with linux.Maybe pi-hole colides with csgosl or csgo.I also added periodic cron job to update blocklists to pi-hole every hour.I dont know where the problem is.

**Comment by lenosisnickerboa** [comment]
Yes, it's csgo related. But I need more information about what you did before this happened. I guess everything was working at some point and then this happened?

**Comment by Peter82kr** [comment]
I dont know what happened.Just whem im log remotelly to debian i saw window popup with this error.I do nothing when people playing on my server.On same mashine works pi-hole network wide ad blocker.

**Comment by lenosisnickerboa** [comment]
OK, I don't know what to make of that. Same suggestion as in your other thread I guess, clean reinstall.

**Comment by lenosisnickerboa** [comment]
Closing. not an apparent csgosl issue.
