### ISSUE TITLE
How to run server at boot?

### ISSUE THREAD

**Issue by Peter82kr** [lenosisnickerboa/csgosl#243]
I added job to crontab by adding this:
@reboot sleep 60 && siarap cd /home/siarap/csgosl/ && siarap standalone-server-start.sh
siarap is my username.
Server not starting after boot.I dont see process in htop after minute from launch
I tried also:
@reboot sleep 60 && siarap /home/siarap/csgosl/standalone-server-start.sh
and:
@reboot siarap /home/siarap/csgosl/standalone-server-start.sh
with no sucess.

**Comment by lenosisnickerboa** [comment]
First of all, does /home/siarap/csgosl/standalone-server-start.sh work for you? Just make sure that is the case first.

Then, did some googling and found this https://unix.stackexchange.com/questions/109804/crontabs-reboot-only-works-for-root

I would suggest using a script like the one below first to ensure cron actually supports @reboot and that you are using the correct user siarap.

#!/bin/bash
"$(whoami): $(date)" >> /home/siarap/test.log

You should see new entries like these in test.log when it works
siarap:Mon Mar  2 08:10:25 CET 2020

When that works replace the test script with /home/siarap/csgosl/standalone-server-start.sh

**Comment by Peter82kr** [comment]
I tested many crontab entries with no success.Solved that issue by adding cs go start script to "Session & startup" application from xfce4.But just autoupdate part of script started and closed itself.Its advance.Now i need to know how to edit startup script to work with update at desired time (after reboot).

**Comment by lenosisnickerboa** [comment]
I don't think I can help you get this sorted. I don't how much you've edited files on your own. For instance the script you have edited in your previous post lacks "start" after "/home/siarap/csgosl/bin/server.sh" so it will never work. That would explain why " just autoupdate part of script started and closed itself".

I also asked about if "/home/siarap/csgosl/standalone-server-start.sh" worked if called directly but I can't see an answer above?

I would suggest a clean reinstall to some other location and then trying "/home/siarap/some-other-location/standalone-server-start.sh" again

**Comment by Peter82kr** [comment]
Default script generated by csgosl starts with session but after autoupdate window close itself and server not running.That behavior is without any modification of csgosl.

Modified script starts autoupdate on system bot and after that starts server but server wont auteorestart+update itself.

**Comment by Peter82kr** [comment]
Probably pi-hole blocking: whatsmyip.akamai.com as akamai is adds domain blacklisted in default pi-hole addserver lists.Maybe this makes problems.

**Comment by lenosisnickerboa** [comment]
About whatismyip.akamai.com, I think you're missing the point. You are not providing your external IP, and akamai doesn't need to know your external IP. It's the site I use to get your external IP (by parsing the returned data from akamai). Even if you know your external IP, others don't and want that information easily available. And also, if you don't like that part simply disable it in the Application-tab (disable getips) and akamai will not be used any more.

About "Its something wrong with your script"; It's working for 2000+ users on windows and various linux flavors so perhaps there could be some other problem? Also, your final statement about the script actually working when you run it in a terminal and don't auto start it suggests just that. I don't know which special requirements your linux flavor has on startup scripts but the two calls in standalone-server-start.sh is basically direct calls to Valves scripts/commands so it's really Valves requirements you need to deal with. If you want to be dead sure directly call Valves scripts like this:

/home/siarap/csgosl/steamcmd/steamcmd.sh" +runscript "/home/siarap/csgosl/bin/steamcmd.txt"
"/home/siarap/csgosl/server/srcds_run" -game csgo -usercon -condebug -ip 0.0.0.0 +game_type 0 +game_mode 1 +mapgroup "de_dust2" +map de_dust2 -maxplayers_override 16 -tickrate 128 +hostname "War Never Changes" -port 27015 +sv_lan 0 -tos -noipx -preload +sv_hibernate_when_empty 0 +sv_setsteamaccount XXXXXXXXXXXXXXXXXXXXXXXXXXXX -nobots

All that generated script does is call Valves scripts with the command line options you configured in csgosl.

**Comment by Peter82kr** [comment]
i run this script in session and startup:
#!/bin/bash
sleep 60 && "/home/siarap/csgosl/server/srcds_run"  -game csgo  -usercon -condebug -ip 0.0.0.0  +game_type 0 +game_mode 1  +mapgroup "de_dust2"  +map de_dust2     -maxplayers_override 16  -tickrate 128      +hostname \"War Never Changes\" -port 27015 +sv_lan 0  -console -tos -noipx -preload +sv_hibernate_when_empty 0 +sv_setsteamaccount XXXXXXXXXXXXXXX -nobots -autoupdate  -steam_dir   "/home/siarap/csgosl/steamcmd"  -steamcmd_script   "/home/siarap/csgosl/bin/steamcmd.txt"

with editing srcds_run as mentioned in another treads because srcds_run link autoupdate to steam.sh not steamcmd.sh and symlink not changes anything in that case.After that scripy runs fine.
Only csgosl scripts makes problems in my case (server.sh).Maybe i just use csgosl to generate configs only and run server in my way because it works with autostart.

**Comment by lenosisnickerboa** [comment]
OK, closing this issue then since it seems everything except -autoupdate works. I will create a separate issue for -autoupdate and have a look at it sometimes later, see here: https://github.com/lenosisnickerboa/csgosl/issues/244
