### ISSUE TITLE
my friends cant find the srver 

### ISSUE THREAD

**Issue by zpgamer** [lenosisnickerboa/csgosl#245]

**Comment by SaeedMasoumi** [comment]
@zpgamer What is the output of this URL?
http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=YOUR-IP&format=json

**Comment by fdrios** [comment]
Hi, I have the same issue: the response whit the IP of the server is:

{"response":{"success":true,"servers":[{"addr":"190.247.213.189:27015","gmsindex":65534,"appid":730,"gamedir":"csgo","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}

if I go to the list servers I cant find my server.

**Comment by SaeedMasoumi** [comment]
I had the same issue and resolve it with the following steps:

- First, wait for some hours (3-4)
- If it didn't appear, make sure you apply port forwarding into your server
- If it didn't appear, try to disable the firewall in your OS

**Comment by fdrios** [comment]
I solve.... port fowarding in the modem was the problem!
TY!!!
