### ISSUE TITLE
Rcon problem

### ISSUE THREAD

**Issue by fdrios** [lenosisnickerboa/csgosl#246]
I try to use the RCON Cli, but i have this message when I try to use a command, for example ask for users:

con@192.168.0.234:27015> users
Failed connecting to server 192.168.0.234:27015 (couldn't open socket: connection refused)

**Comment by lenosisnickerboa** [comment]
You don't state which platform you use, windows/linux?
If on windows: 
Did you get a firewall question about allowing access when you enabled rcon cli? If yes, did you answer it with "yes, allow access"?
I have also had the same issue and others have reported it as well, see now closed issue https://github.com/lenosisnickerboa/csgosl/issues/195. You can try overriding the rcon cli port used in the RconCli tab (bottom options) and see if that helps.

**Comment by fdrios** [comment]
I solve the problem...
I run the server before run steam.
Now I put the server on other Windows PC and run fine.
TY
