### ISSUE TITLE
win round reduces the loss counter by two 

### ISSUE THREAD

**Issue by Moontrey** [lenosisnickerboa/csgosl#247]
I enable mp_consecutive_loss_aversion, but I think this is not working correctly. The first winning round reduces the loss counter by two (have to reduce only by one), and the next winning rounds reduce this number by 1.

Could you help me. Maybe I'm doing something wrong.

Ty in advance.

**Comment by lenosisnickerboa** [comment]
This problem has been reported here https://github.com/lenosisnickerboa/csgosl/issues/196. Will have a look as soon as I get the time to play around with csgosl again :)

**Comment by lenosisnickerboa** [comment]
Had a look now and this is a mess, perhaps because I don't use it and don't understand it. Anyhow, it is described here and there seems to be more variables involved. https://steamdb.info/patchnotes/3643227/
Right now I don't see anything I can do in csgosl, seems the default values are correct?

**Comment by lenosisnickerboa** [comment]
Released https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.8, please reopen a new ticket if you still see problems.
