### ISSUE TITLE
Server cant be stopped

### ISSUE THREAD

**Issue by paulikappi** [lenosisnickerboa/csgosl#248]
When I press Stop server from gui, console window re-opens and servers restarts. I have to kill process from task manager.

**Comment by lenosisnickerboa** [comment]
Could you please check out this page https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug and get back to me. The above post is really not enough information for me to take this issue further.

**Comment by lenosisnickerboa** [comment]
Closing, no reply. Please reopen if still an issue.
