### ISSUE TITLE
Virus scanner problems with new 2.8 update

### ISSUE THREAD

**Issue by MarsTwix** [lenosisnickerboa/csgosl#249]
When i updated my csgosl to 2.8, my virus scanner (avira) blocked the file 'sourcemod_mm.dll'. So im getting the error 'PutClientInServer: no info_player_start on level' and doing 'sm plugins list' will give the error 'Unknown command "sm"'. if i  put the file back it will keep getting blocked.

**Comment by lenosisnickerboa** [comment]
I really can't guarantee the correctness of the sourcemod dll but it's downloaded by my linux build server directly from the stable sourcemod site https://www.sourcemod.net/downloads.php?branch=stable. I run csgosl both on linux and windows and haven't experienced any issues, nor have I heard anything from anyone else. I wouldn't worry about it and add an exception for the sourcemod_mm.dll file.

**Comment by MarsTwix** [comment]
Thanks for the help, it works now completely fine!
