### ISSUE TITLE
WarMode

### ISSUE THREAD

**Issue by fdrios** [lenosisnickerboa/csgosl#250]
When I Run WARMODE, in danger zone game. When I start the match using /ready WM commando. I cant pickup guns, they disappear, the dron don´t drop nothing.
I'm running a Windows Server. The only one sourcemode enabled is WARMod.
I'm not excecuting nothing in AUTOEXEC tag.
I put the warmode on because I cant enter with another players in Danger Zone mode game, just one player can enter to the game in this mode without WARMODE plugin.
I want to run a DANGER ZONE server, but I found this problems to use.

**Comment by lenosisnickerboa** [comment]
Anyone who can help out? I don't use Warmode and don't understand the issue.

**Comment by lenosisnickerboa** [comment]
Closing, no replies.
