### ISSUE TITLE
Map group broken

### ISSUE THREAD

**Issue by Osberg** [lenosisnickerboa/csgosl#251]
After release 2.8 the map group is now broken, you cannot chose the maps groups that you have made for ex workshop maps etc. I only choose all maps no matter what.

**Comment by lenosisnickerboa** [comment]
Isn't the problem that you have the new "automapgroup" option enabled and you have no auto_<gamemodetype> mapgroup defined for your current gamemodetype?

**Comment by Osberg** [comment]
Year i found out that the new feature "automapgroup" was the issue for me. :) 

We can close the issue here. :)
