### ISSUE TITLE
Fresh install issue

### ISSUE THREAD

**Issue by ChineseNorris** [lenosisnickerboa/csgosl#252]
System: windows 10 64 bits

Hi,

I'm trying to run csgosl on my computer for testing and I'm receiving the following error when I click on Install Server : 

not_running
find: /I: No such file or directory
find: ExecutablePath=C:\csgosl\server\srcds.exe: No such file or directory
not_running
find: /I: No such file or directory
find: ExecutablePath=C:\csgosl\server\srcds.exe: No such file or directory
    while executing
"exec "$serverControlScript-status.bat""
    (procedure "DetectServerRunning" line 6)
    invoked from within
"DetectServerRunning"
    (procedure "UpdateServer" line 9)
    invoked from within
"UpdateServer"
    invoked from within
".title.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.update"
    (command bound to event)

Why is it checking on " /I: " even if I don't have this drive? It's the first time I'm trying to run it and I've downloaded the zip file from the code section.

Regards

**Comment by lenosisnickerboa** [comment]
Did this happen on the first csgosl run? Or did it happen after a failed installation? It sounds a bit like an installation has been started, failed (or got interrupted somehow, closed/killed?)  and then you try to restart csgosl which determines the install has been performed and tries to determine if the server is running. I would remove the installation directory, unzip the archive again and restart and let the installation finish.

Here are some [similar problems](https://github.com/lenosisnickerboa/csgosl/issues?q=is%3Aissue+find%3A+%2FI%3A+No+such+file+or+directory) as well which might also be a reason.

**Comment by ChineseNorris** [comment]
Looks like it's always a PATH variable problem, maybe a change in the code to fix this so it will work 100%? I don't know if it's possible to fix from the script.

Thanks
