### ISSUE TITLE
 problem to enter the server

### ISSUE THREAD

**Issue by Pessegoamass** [lenosisnickerboa/csgosl#253]
I can create the server, but I can't get it online, I've done everything, and when I'm going to enter even with it not online, it loads but returns to the home screen without any error message, please help!

**Comment by lenosisnickerboa** [comment]
[Please read this first](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)

**Comment by lenosisnickerboa** [comment]
Adding your text from the other two duplicate issues (which I will close).

versão:2.8.1
Plataforma:Windows
problem:I tried to open the server, but it starts to load and for no reason it goes back to the home screen and no error notification appears,
always happens and never works.
Screen dunp:don't have it
console output:
KouTako
2 dias atrás
Error reading file maps/workshop/125438372/thumb125438372.jpg.
Error reading file maps/workshop/125439125/thumb125439125.jpg.
Error reading file maps/workshop/205240106/thumb205240106.jpg.
Error reading file maps/workshop/152508932/thumb152508932.jpg.
Host_WriteConfiguration: Wrote cfg/config.cfg
Host_WriteConfiguration: Wrote cfg/config.cfg
** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
CS_App_Lifetime_Gamestats: Recording ServerBrowserLAN
Connecting to public(25.3.94.83:27016) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'MMStatus'
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
Failed to load image data from https://media.st.dl.eccdnx.com/apps/csgo/images/trans.gif
Please help me.

**Comment by lenosisnickerboa** [comment]
Some questions:

Did you try just installing the server and start it using all default values? From the console traces in your post I see error messages suggesting several things have been changed since the default installation.

1. I see "Error reading file maps/workshop/125438372/thumb125438372.jpg." which suggests workshop maps have been installed, correct?
1. If you google parts of the error message, like e.g. "ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU" you find several people having issues like yours, not related to csgosl though. 
1. Do you have any other stuff, like mods, which you have installed yourself?

I would perform a clean install of the server, leave everything at default values, start the server and see if that works first. If it does, start changing stuff until it breaks and you know what caused your problems.

**Comment by Pessegoamass** [comment]
I did not download any map of the workshop I used de_dust2

I didn't install mods.

I already installed without changing anything, even formatted my computer

I don't think it's a problem with my PC, because none of my friends can log in, and I've done everything I can to make it online.

**Comment by Asimovv** [comment]
Same problem! The solution that I found is edit cms-start.bat from CSGOServer\csgosl\bin and put "-net_port_try 1" and run it manually and resolved my problem. The issue is if I open csgosl and run from there the cmd-start.bat reset the values to the default and can't enter in online mode, only lan. Can you fix that please?

**Comment by lenosisnickerboa** [comment]
Don't know what -net_port_try=1 really does? Anyone? I see in some posts they say "always include it" but I would like to understand what it does first.

As a temporary fix you can just add -net_port_try=1 to the options setting (Run tab, section Misc, at the bottom of that tab) and it will always be appended to the command line.

**Comment by Asimovv** [comment]
""Note: For public server also add +sv_setsteamaccount THISGSLTHERE -net_port_try 1 to use your GSLT. THISGSLTHERE""  This is a note from valve website. The thing I'm suprise is by only one "missing" command I can't run the server online, either with "onlylan" disable. But thanks for the fast temporary fix! Hope you can fix it permanently.

**Comment by lenosisnickerboa** [comment]
Np
So I'll just add this option for non-lan/public games, that's it?

**Comment by Asimovv** [comment]
So when you disable the "onlylan" option you need to automatic put "-net_port_try 1" in startfile and that's it.

**Comment by lenosisnickerboa** [comment]
Just released https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.8.2 with support for -net_port_try option (and new sourcemod)

**Comment by Pessegoamass** [comment]
still does not work

**Comment by lenosisnickerboa** [comment]
And you disabled lanonly? Have you read https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server ?
@Asimovv , did it work for you with 2.8.2 and without using the options setting in the Run tab?

**Comment by Asimovv** [comment]
Yes, like a charm!
And you only need to open the 27015 port to play online.
@Pessegoamass Try to add a rule in windows firewall, UDP and TCP rule.

**Comment by minestarnl** [comment]
I am still having the same issue. Do I need to toggle net_port_try? I added the firewall rule inbound udp and tcp. Port forwarded as well. Even after adding the net_port_try 1. It still didn't work. I can post the server info(ip) if needed

**Comment by lenosisnickerboa** [comment]
Wild guessing... what does ipconfig tell you? Do you have multiple interfaces, like e.g. a VPN interface (active or not). I played around with a VPN client which created a new interface and even when the VPN was down this interface was active with a 169.x.x.x address. I noticed my csgo server bound to the 169.x.x.x address and no one was able to connect. I finally uninstalled the VPN client, rebooted and ensured that interface was gone and then everything worked again. Probably could have forced the csgo server to bind to the correct address but that didn't work so I brute-forced uninstalled the VPN client instead.

**Comment by minestarnl** [comment]
Ok figured it out. After some fiddling I found out windows set the network connection to public. Therefore nothing could connect to it. After setting the network connection to private everything worked fine 😄 Thank you

**Comment by lenosisnickerboa** [comment]
Thanks for reporting back! Will surely help someone with similar problems.
