### ISSUE TITLE
problem to enter in the server

### ISSUE THREAD

**Issue by Pessegoamass** [lenosisnickerboa/csgosl#254]
versão:2.8.1
Plataforma:Windows
problem:I tried to open the server, but it starts to load and for no reason it goes back to the home screen and no error notification appears, 
always happens and never works.
Screen dunp:don't have it
console output:
KouTako
2 dias atrás
@D3KO Error reading file maps/workshop/125438372/thumb125438372.jpg.
Error reading file maps/workshop/125439125/thumb125439125.jpg.
Error reading file maps/workshop/205240106/thumb205240106.jpg.
Error reading file maps/workshop/152508932/thumb152508932.jpg.
Host_WriteConfiguration: Wrote cfg/config.cfg
Host_WriteConfiguration: Wrote cfg/config.cfg
** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
CS_App_Lifetime_Gamestats: Recording ServerBrowserLAN 
Connecting to public(25.3.94.83:27016) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'MMStatus'
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
Failed to load image data from https://media.st.dl.eccdnx.com/apps/csgo/images/trans.gif
Please help me.

**Comment by Pessegoamass** [comment]
Sorry dont have @deko in the console

**Comment by lenosisnickerboa** [comment]
Duplicate
