### ISSUE TITLE
Server on VM and virtual Firewall // Vlan Bind

### ISSUE THREAD

**Issue by Minasmins** [lenosisnickerboa/csgosl#257]
Hi,
when i try to bind the ip of my vlan port i get the error msg: 
"CreateBoundSocket: ::bind returned error [no name available](10049)

What can i do to fix this?

**Comment by lenosisnickerboa** [comment]
Let's start with some more info: https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug

What do you mean "you try to bind the ip..." - what do you do? which command? where do you enter it?  Who prints the error message?

**Comment by lenosisnickerboa** [comment]
No answer, please reopen if still an issue.
