### ISSUE TITLE
Workshop maps don't load on their own

### ISSUE THREAD

**Issue by napzka** [lenosisnickerboa/csgosl#259]
At the end of round vote if a workshop map receives the most votes, that map is not loaded. Instead a "regular" map is loaded. When trying to use the in-game vote to change it manually the vote does not go through and we get the message "that map doesn't exist".

**Comment by lenosisnickerboa** [comment]
do you have sourcemod enabled with one of the mapchooser plugins? That happened to me, I selected a map in the csgo standard interface but it was the sourcemod plugin which chose another map instead.

**Comment by napzka** [comment]
I do not, although I might try and see if the mapchooser plugin does load the maps. But right now SM isn't even enabled.

**Comment by CJNiiva** [comment]
It might happen if the map isnt downloaded or if the map download is corrupt for the workshop map

Sendt fra min iPhone

28. apr. 2020 kl. 10:57 skrev napzka <notifications@github.com>:

﻿

I do not, although I might try and see if the mapchooser plugin does load the maps. But right now SM isn't even enabled.

**Comment by napzka** [comment]
The maps load just fine if I set them as a startmap, so I don't think that's the issue.

**Comment by napzka** [comment]
I think I may have found the issue. The mapvote system (end of round and ingame vote) try to load from the \maps folder. So for example if I try to load Tuscan, it will look for the directory \maps\de_tuscan.bsp. This directory does not exist however, as the bsp is stored under \maps\workshop\(workshop ID)\de_tuscan.bsp. I don't know how this issue could be fixed, so help is appreciated.

**Comment by lenosisnickerboa** [comment]
Sorry, late reply. If you look into the mapcycle.txt I guess it just contains the map names but I guess in the workshop map case it should contain something like \workshop\<map-id>\map-name. I will investigate this.

**Comment by Osberg** [comment]
hi @lenosisnickerboa i have seen on my server where I have 3 workshop maps running...These 3: https://steamcommunity.com/sharedfiles/filedetails/?id=2029613169

So every time I have played the AK47 map, and you choose another map out of the 3, it always just reload the running AK47 map??

**Comment by lenosisnickerboa** [comment]
If you check your mapcycle.txt, does it only contain the map names? Not the workshop path?
(look in <Install-directory>\csgosl\server\csgo)

**Comment by Osberg** [comment]
only name.

![image](https://user-images.githubusercontent.com/23699885/81046280-4f131a00-8eb8-11ea-8325-a9bb42239ca4.png)

**Comment by lenosisnickerboa** [comment]
Thanks, guess it should look something like from this thread https://forums.alliedmods.net/showthread.php?t=301746 :

workshop/241267905/aim_multi_v4
workshop/252477933/am_nuke
workshop/255301758/am_dust2_cat

**Comment by Osberg** [comment]
Alright let me test it a bit later, and give you a update on this. :)

**Comment by Osberg** [comment]
So I tried to edit the file, but every time I start up the server, it removes the lines that I have put in. :(

**Comment by lenosisnickerboa** [comment]
Yup, it will regenerate the config files. But I have played around with some workshop maps and I think I have solved it. I got the same problem you did but changed csgosl so that it generates mapcycle.txt, maplist.txt and gamemodes_server.txt differently. They will all contain the workshop/<id>/mapname instead of just mapname for workshop maps. It works perfectly for me, will release this fix soon, stay tuned.

**Comment by lenosisnickerboa** [comment]
Just released https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.8.3
Check it out and see if workshop maps works as you want now. They do for me.

**Comment by Osberg** [comment]
Year it works perfect. :)

**Comment by lenosisnickerboa** [comment]
Closing, also see https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.9 which adds some better map handling.
