### ISSUE TITLE
Advanced Launch Options not found

### ISSUE THREAD

**Issue by ElementTimes682** [lenosisnickerboa/csgosl#26]
I'm making a minigame server and as some minigames may be locked because these launch options are available without csgosl, I don't want to have to go through console everytime I start it back up again. The thing is I can't find launch options in console or run. This hasn't been posted in the wiki.

**Comment by lenosisnickerboa** [comment]
Not sure I complete understand but if you just want to append some command line options to srcds.exe (which is what I understand you're doing in the console) you can do this on the Run page, see help [here](https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Run). It's the last option on the line named **option**. Anything you type here will be appended to the command line.

Please let me know if this was what you were looking for.

**Comment by lenosisnickerboa** [comment]
Closing this issue due to no more feedback.
