### ISSUE TITLE
Friends unable to join server.

### ISSUE THREAD

**Issue by hydrox1de** [lenosisnickerboa/csgosl#260]
NET_CloseAllSockets
WARNING: UDP_OpenSocket: unable to bind socket
WARNING: UDP_OpenSocket: unable to bind socket
Trying to open socket on 192.168.1.150

I've opened the relevant ports, and terminated any and all traffic concerning port 27015. Is there any other workaround to this?:

**Comment by hydrox1de** [comment]
csgosl version: 2.8.2
platform: windows
describe problem: I start csgosl, start server, but friends are unable to join, notably on non-LAN/public setting
does it happen every time or just once-in-a-while: every time
did this work before and stopped working: fresh install of csgosl
if it stopped working, what changed? updated csgosl? updated csgo server? : N/A
do you have sourcemod enabled? no
if sourcemod is enabled
does it help to disable sourcemod? : N/A
do you have any mods enabled? which? : N/A
do you have any mods that you have installed yourself? : No
screen dump: N/A

app_update 740 validate is initiated every time when launching the server.

**Comment by lenosisnickerboa** [comment]
First about "app_update 740 validate is initiated every time when launching the server.", where do you see that output? Screenshot?

About why your friends can't connect; there's a number of possible issues you could run into. Have you for instance forwarded ports correctly in your router? Allowed access through your Windows firewall?

I have found the easiest way to get this working is setting up a VPN using my router and allowing friends access to the VPN. Then I can host a lanonly csgo server and it just works.

**Comment by hydrox1de** [comment]
app_update 740 validate is outputted into the console. It's one of the first few lines that get displayed. It's right below _force_install_dir "C:/Users/trans/Downloads/csgosl-windows/csgosl/server"_. Firewall and port access have been granted. Will try the VPN method, and I'll update this thread when I do so.

**Comment by hydrox1de** [comment]
Alright, I've tried the Hamachi VPN method, everything works fine, no error messages, save for one small problem: I can't find the server in the LAN tab within csgo. When making a random workshop map, the server IP is correct though: it's the IP shown within Hamachi.

**Comment by hydrox1de** [comment]
Trying out my router's in-built VPN now.

**Comment by hydrox1de** [comment]
Well, after some tinkering around with a VPN, I’ve gotten the server to work. Thanks for the help, closing thread.
