### ISSUE TITLE
cant see my server in serverlist

### ISSUE THREAD

**Issue by cptmacp** [lenosisnickerboa/csgosl#262]
Hello .
I hosted a server of csgo on a VPS ( 2 core , 4 gb ram)

it works just fine , I can connect from its IP , rcon works fine .

but it does not SHOW in server list .

http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=myip

also shows the server  , my friends can also connect onto it ( from the ip ) 

but idk why its not showing in server list.

**Comment by lenosisnickerboa** [comment]
Don't know either, anyone hosting a public server? I'm just running a local one and friends connect via VPN.

**Comment by jensbhurtah** [comment]
Yes, i have the same issue.
i can host public servers not lan. Friends can connect through my ip and join the server.
http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=myip
Can also see my server.

But the server never appears on the community browsers server list.

sv_region , sv_tags are set up.

host_name_store 1
sv_tags "casual,,csgo!knife,Deathmatch,secure"
host_info_show 2
host_players_show 2
sv_region 7
sv_lan 0

**Comment by Peter82kr** [comment]
Server token set?You need server token to work with steam servers. You can generate token on steam site. Search info in internet.

**Comment by lenosisnickerboa** [comment]
This sounds like #272 

I have listed the basic steps for hosting a public server here https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server, have you checked that all this is setup properly? Have you checked that your gameserverlogintoken has not expired? You can check this here https://steamcommunity.com/dev/managegameservers.

There are a number of reasons for this problem not related to csgosl but more of a general csgo dedicated server hosting issue.

**Comment by gitcroni** [comment]
I have the same problem, except that I'm only hosting on my PC and not a VPS. I see the server on the LAN list but I can't see it on the "Internet" tab of the server browser. When I check the server on the API link, this is what I get:

> {"response":{"success":true,"servers":[{"addr":"152.32.109.**_XXX_**:27015","gmsindex":65534,"appid":730,"gamedir":"csgo","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}

ending of IP address edited out.

I've tried editing the various CFG files but csgosl seems to override any edits I make as soon as I start the server. What can I do to have my server show publically?

**Comment by lenosisnickerboa** [comment]
About the overwriting of cfg files; you can start your server using the script cmd-start.bat in <install-location>\csgosl\bin instead (you don't state platform, assuming windows, if on linux it's still in the csgosl/bin folder named cmd-start.sh). That way csgosl will not overwrite your changed cfg files. Of course, if you run csgosl and change anything all files will again be overwritten. But if you want to try out different options you can shutdown csgosl, edit the cfg files and also cmd-start.bat|sh to experiment.

**Comment by cptmacp** [comment]
nat loopback issues 
fixed it
