### ISSUE TITLE
Hosting server problem

### ISSUE THREAD

**Issue by Juleo232** [lenosisnickerboa/csgosl#265]
Just I can enter in my server.
Its logged in Anonymous and shows it in console
****************************************************
*                                                  *
*  No Steam account token was specified.           *
*  Logging into anonymous game server account.     *
*  Connections will be restricted to LAN only.     *
*                                                  *
*  To create a game server account go to           *
*  http://steamcommunity.com/dev/managegameservers *
*                                                  *
****************************************************
but i already put my token, and loggin in steamcmd. it doesnt appear and never logged in the steam token. anyone can help me ?

**Comment by Juleo232** [comment]
someone can help me???????

**Comment by lenosisnickerboa** [comment]
First this: https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug

Then, did you read this? https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server

It seems the GSLT is invalid or not entered properly. Did you enter a valid gameserverlogintoken in the Steam tab? If you look into the console (Console tab on windows, terminal window on linux) and look for the command which starts the game do you see the gameserverlogintoken there? Should look something like +sv_setsteamaccount xxxxxxxxxxxxxxxxxxxxxx
Also, sure you unchecked lanonly option in Server tab?

**Comment by lenosisnickerboa** [comment]
Closing, no respones.
