### ISSUE TITLE
Fresh Install Fatal Error

### ISSUE THREAD

**Issue by Vercetty3** [lenosisnickerboa/csgosl#266]
Hey, I'm getting this error when I try to run the VBScript File for the first time, I just downloaded this for the first time today. I get the initial "no server detected, starting in minimal mode" dialog, and the error appears once I click I understand. I tried deleting everything and starting over, but got the same error. Thanks!

![image](https://user-images.githubusercontent.com/65307421/81849749-9afb3a00-951c-11ea-855e-f9be5862a5df.png)

**Comment by lenosisnickerboa** [comment]
Thanks for reporting, just reproduced the same problem and will have a quick look at it now.

**Comment by lenosisnickerboa** [comment]
Should be fixed in https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.9.1 , please check if it works for you now.

**Comment by Vercetty3** [comment]
Everything appears to be working, thanks a ton!
