### ISSUE TITLE
Unable to perform fresh install from 2.9.1

### ISSUE THREAD

**Issue by mhu-tech** [lenosisnickerboa/csgosl#267]
Thank you so much for putting this together!
My current workaround based on a previous issue list is to install 2.7.3 and that works so far .(https://github.com/lenosisnickerboa/csgosl/issues/204)

It looks like resources (either maps or widgets) won't load.

key "" not known in dictionary while executing "

![image](https://user-images.githubusercontent.com/65470614/82131630-0139c400-978c-11ea-85cd-086cd4002d19.png)

Cheers!

**Comment by Nounnours** [comment]
Similar issue here, also once I managed to actually start it (by updating from an older version strangely?)
I get the Public server crashing at startup (works in LAN...)

**Comment by Nounnours** [comment]
yes fresh unzip then click on csgosl.vbs and boom same error!

I reinstalled it from scratch again and this went away for me (but I think I used the batch file directly without the vbs script this time), weird but it works now (vbs script is also fine once installed) :/
not sure what triggers it since I had the same issue as mhu-tech on 2 different PCs

**Comment by rodrigorioo** [comment]
Same issue here. I try install the server through csgosl and using an existing server installation and I have the same error.

**Comment by lenosisnickerboa** [comment]
Could it be that you are using the 2.9 zip file somehow? The error message you get above suggests that. It says "Procedure SetSelectedMapGroup... line 8" and that code existed on line 8 in the 2.9 release. In the 2.9.1 release that code is on line 10.

**Comment by Futayo** [comment]
Hi there !
I just try it and got the same error, but i found that the download link for 2.9.1 in the README don't go on 2.9.1 but the old 2.9.
I dowload the 2.9.1 manually by Github, and it launch at first attempt.

Thx for your marvellous tools, and have a nice day

**Comment by lenosisnickerboa** [comment]
Thanks again! 😁

**Comment by lenosisnickerboa** [comment]
Fixed by correcting the link to 2.9.1
