### ISSUE TITLE
Unusable Interface Colors / Text Size

### ISSUE THREAD

**Issue by Sam-Belliveau** [lenosisnickerboa/csgosl#268]
![image](https://user-images.githubusercontent.com/28713194/82506595-3caafa00-9ace-11ea-80d0-4d63e45e17d4.png)

I use Manjaro i3wm, and there is no obvious way to change the look of the interface. The text in the boxes are the same color as the text, making it impossible to read without highlighting. Also today, the text got really big for no apparent reason.

**Comment by lenosisnickerboa** [comment]
Sorry, no idea about the i3 wm, guess colors are configurable in the wm? No
idea how I could solve this in my application?

**Comment by Sam-Belliveau** [comment]
I found the issue!

For anybody wondering about this issue in the future:

I had the weird colors because:
```
*background:                      #222D31
*foreground:                      #d8d8d8
```
the background was black and the forground was white.

If you want the correct colors for CSGOSL or any TCL/Tk app, you need to switch it to 
```
