### ISSUE TITLE
Can only stop the server by killing the process (Linux)

### ISSUE THREAD

**Issue by goedras14** [lenosisnickerboa/csgosl#274]
After starting the server in the UI, the button stays the same and doesn't change to "stop server" and can only stop the server by issuing the "kill" command in the terminal.

**Comment by lenosisnickerboa** [comment]
Run the following command after you started the server and paste the output here:

`pgrep -f srcds_linux `

You should get the pid of your csgo server. If you look in the console where the csgo output is printed, at the end you should see something like this:

RecordSteamInterfaceCreation (PID **794015**): SteamUtils009 / Utils

Check that the pid reported here is the same as the one reported by `pgrep -f srcds_linux ` above.

This is really strange, haven't heard anyone reporting issues like these on linux.

**Comment by lenosisnickerboa** [comment]
No further response, please reopen if still an issue. Closing.
