### ISSUE TITLE
Create launcher script to avoid having to start csgosl just to start the server

### ISSUE THREAD

**Issue by lenosisnickerboa** [lenosisnickerboa/csgosl#28]
Add option to create a launcher script using current configuration to allow the server to be started directly without starting csgosl

**Comment by thimoonxy** [comment]
can you twist https://github.com/crazy-max/csgo-server-launcher in csgosl? I was trying to config csgo-server-launcher.conf after csgosl installed, but vars like DIR_ROOT, DIR_GAME which just confused me since it seems csgosl has different file paths from csgo-server-launcher ?

**Comment by lenosisnickerboa** [comment]
Hi,

Had a quick look at the launcher script you linked and I see no reason why
it shouldn't be possible to use with csgosl. You just need to get the paths
right as you pointed out (might require script change...?) csgosl keeps the
server installation in its server folder and the steamcmd installation in
the steamcmd folder so it should be pretty straight forward.

BUT... what is it this script offers that csgosl lacks? Would be
interesting to read what you want to do so I perhaps could incorporate that
into csgosl.

BR
/Lennart

Den 25 juli 2016 09:36 skrev "Simon Xie" <notifications@github.com>:
