### ISSUE TITLE
Any method to host map data locally?

### ISSUE THREAD

**Issue by Naville** [lenosisnickerboa/csgosl#280]
Sorry I'm kinda new to server hosting. Due to reasons Steam Workshop is usually really freaking slow to download from here in China especially when downloading in-game. Is there any option for me to let the clients download the map data from my server instead of Steam?

**Comment by lenosisnickerboa** [comment]
FastDL is already supported in csgosl (Server tab) but I have never used it personally. Just google "csgo fastdl" and you will get a lot of information about how to set it up. Basically you need to provide an alternate location to download stuff from, could be your own http server or some other server which is faster where you live.

**Comment by Naville** [comment]
Thanks!
