### ISSUE TITLE
Could not establish connection to steam servers.

### ISSUE THREAD

**Issue by SuperK2-OS** [lenosisnickerboa/csgosl#283]
My CSGO server is up and running.

BUT ... if I put the TOKEN .... "Could not establish connection to steam servers"

if I delete the Token ... works fine, but only in LAN.

Ports are open...

27000-27050
3478
4379
4380

all TCP+UDP

Firewall disabled

I tried DMZ too.

Can anyone help me ?

**Comment by SuperK2-OS** [comment]
What I am doing wrong?

Please, any help or hint ?

**Comment by lenosisnickerboa** [comment]
All that's really needed is described here: https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server

Obvious things to make sure is to login to https://steamcommunity.com/dev/managegameservers to verify the GSLT hasn't expired and to double-check port-forwarding. But I guess you already did that?

**Comment by lenosisnickerboa** [comment]
No response, closing.
