### ISSUE TITLE
Can't run mutiple servers at once?

### ISSUE THREAD

**Issue by kENN1N** [lenosisnickerboa/csgosl#284]
Fixed

**Comment by lenosisnickerboa** [comment]
Nice if you would share what the problem was

**Comment by kENN1N** [comment]
Sure :) 
Problem was with Ports - they had to be like this.

Server - 27015
GOTV - 27020

Next server had to be 
Server - 27025
GOTV - 27030

And so on.

**Comment by lenosisnickerboa** [comment]
Thanks!
