### ISSUE TITLE
fatal error when trying to start server

### ISSUE THREAD

**Issue by daveduno** [lenosisnickerboa/csgosl#286]
![image](https://user-images.githubusercontent.com/69153980/89187888-e1849180-d56b-11ea-8d79-2fcc5312185a.png)
I uploaded a picture of the error message.  This just appeared 1 day.  It was working fine for days.  How do I fix this?  The path says its on desktop/backup, because I saved it as a backup from c:/, and tried to delete the entire csgosl folder from C:/ and downloaded the newest version to install.  But that didnt work either, and the error message was pretty much the same.

**Comment by lenosisnickerboa** [comment]
All I can say from the error message is that it seems like you're starting csgosl from the backup folder on your desktop, or perhaps via a shortcut which points to csgosl in the backup folder. I would delete the backup folder and any other csgosl folder + all csgosl shortcuts, create a new folder c:\csgosl and reinstall from scratch in that folder.

**Comment by daveduno** [comment]
![image](https://user-images.githubusercontent.com/69153980/89216794-0cd1a580-d599-11ea-9094-1f27a3be9ea8.png)

ok, I did that, and when I try to install from scratch, this is the error that comes up.

**Comment by lenosisnickerboa** [comment]
Really no idea why this happens. Haven't seen anything like it before. But
what if you rename/delete the TCL000010b0 folder under Temp in the first
line from the error message?

**Comment by daveduno** [comment]
I have deleted the entire folder in temp and it just recreates it.

**Comment by lenosisnickerboa** [comment]
Full c: ?

**Comment by daveduno** [comment]
![image](https://user-images.githubusercontent.com/69153980/89220533-c03d9880-d59f-11ea-8db6-0e96e2f16508.png)

**Comment by lenosisnickerboa** [comment]
I meant if the c: drive has space left? Properties on c: will tell you how
much space is used.

**Comment by daveduno** [comment]
![image](https://user-images.githubusercontent.com/69153980/89222693-76ef4800-d5a3-11ea-9c2a-17e83037ccc0.png)
looks like 357 GB left

**Comment by lenosisnickerboa** [comment]
Hmmm, running out of ideas... 

- Redownload csgosl from https://github.com/lenosisnickerboa/csgosl/releases/download/v2.9.2/csgosl-windows.zip
- Try installing on another disk? d: ?
- Is user Dave2 administrator? If not try make him administrator.
- Create another user and login as that user. Reinstall in another location as that user.

**Comment by daveduno** [comment]
I do not have another disk to install on.
dave2 is the administrator, and I can not create another user. 
I rightlicked and ran csgosl as administrator, and got
![image](https://user-images.githubusercontent.com/69153980/89225756-c126f800-d5a8-11ea-8e6b-98ce9665a67f.png)

**Comment by daveduno** [comment]
So I tried editing the csgosl file and added C:\csgosl\ in front of bin\csgosl.bat, and then ran as administrator, but nothing seems to happen.  No error message either.

**Comment by lenosisnickerboa** [comment]
Got the same behavior here as well. Don't know why though. 

Googled "couldn't load library tkimgwindow.dll permission denied" and found this: https://wiki.tcl-lang.org/page/load 

```
On Microsoft Windows, attempting to load a .dll file for which Read & execute permissions are not allowed results in an error:

couldn't load library ".../some.dll": permission denied

```

How do you unpack the downloaded zip file? 

I looked in my C:\Users\lenos\AppData\Local\Temp\TCL00001374 and found a lot of dlls there, all with "Read and Execute" permissions, as well as the TCL00001374 folder. Select properties for the folder/files and look into the "Security" tab to see if "Read & execute" is allowed.

**Comment by daveduno** [comment]
I unpacked the zip file with winrar.   It shouldn't be a problem with the unpacking because it was working fine until yesterday.  Every attempt with running the csgosl.bat file creates an empty folder inside temp with the name scheme starting with TCL0000.

**Comment by lenosisnickerboa** [comment]
Weird, no idea what's going on. I have some empty folders but also folders
with dlls in.

**Comment by daveduno** [comment]
wow... it works again... lol I dont know why

**Comment by lenosisnickerboa** [comment]
That's also weird 😀, hope it stays that way though.
