### ISSUE TITLE
Adding another plugin to CSGOSL

### ISSUE THREAD

**Issue by klankisbad** [lenosisnickerboa/csgosl#289]
Sorry for the lack of technical literacy, but im having difficulty installing the Practice Mode plugin made by Splewis. I've followed the install instructions for both projects. I am able to host, and join my server using CSGOsl, but can not get Practice Mode to show up in the plugins list. Is this something to do with CSGOsl coming pre-installed with plugins, or am i just incompetent. 

Thank you for you time, i apologize if this is a misuse of said time.

**Comment by lenosisnickerboa** [comment]
Not sure what you mean by "but can not get Practice Mode to show up in the plugins list". Which plugins list? The list in the sourcemod tab in csgosl or the list of installed sourcemod plugins using command "sm plugins list"?
It will never automatically appear in the csgosl sourcemod tab, it's all hard coded. If it doesn't appear when entering the "sm plugins list" command the reason could be sourcemod is not enabled at all (need to enable it in csgosl, sourcemod tab, General options). In this case the sm command will just show - Unknown command "sm"
If you have enabled sourcemod in the csgosl sourcemod tab and you enter "sm plugins list" and get a list of other plugins but not the practice mode one it sounds to me you either have installed it incorrectly or perhaps csgosl in some way interfere with the plugin. Since I don't know anything about this plugin it's hard to know how and if csgosl could somehow interfere with it.
Please get back with info about which of the cases above it is. One way forward could be adding this plugin to the ones installed by csgosl. Are you using the 1.3.3 version from https://github.com/splewis/csgo-practice-mode/releases ?

**Comment by klankisbad** [comment]
> 
> 
> Not sure what you mean by "but can not get Practice Mode to show up in the plugins list". Which plugins list? The list in the sourcemod tab in csgosl or the list of installed sourcemod plugins using command "sm plugins list"?
> It will never automatically appear in the csgosl sourcemod tab, it's all hard coded. If it doesn't appear when entering the "sm plugins list" command the reason could be sourcemod is not enabled at all (need to enable it in csgosl, sourcemod tab, General options). In this case the sm command will just show - Unknown command "sm"
> If you have enabled sourcemod in the csgosl sourcemod tab and you enter "sm plugins list" and get a list of other plugins but not the practice mode one it sounds to me you either have installed it incorrectly or perhaps csgosl in some way interfere with the plugin. Since I don't know anything about this plugin it's hard to know how and if csgosl could somehow interfere with it.
> Please get back with info about which of the cases above it is. One way forward could be adding this plugin to the ones installed by csgosl. Are you using the 1.3.3 version from https://github.com/splewis/csgo-practice-mode/releases ?

Yes, when using the command "sm plugins list" in the console, Practice Mode is not listed. As far as i can tell, Practice Mode is installed correctly. Unless i am chronically incompetent, installation is only dragging and dropping the plugin into the correct folders, with some admin tweaking to give myself permissions. With my limited knowledge, i was wondering if how csgosl handles the hardcoded plugins would somehow interfere with with adding an additional plugin to the server. I am using the current version 1.3.3 of the plugin. 

Given that there are already splewis plugins added to csgosl, i thought i would be prudent to ask here about my problem first. Thank you for your response. I hope i answered your questions. Do you have any recommendations for the next step in troubleshooting this problem? Again, thank you for your time and effort. I am not the most technically competent person, and csgosl got me to to the step of actually being able to host and connect to a personal server. Thank you.

**Comment by lenosisnickerboa** [comment]
Good to hear csgosl helped you get a server running. thanks!

It seems you have enabled sourcemod and enabled some other plugins which you are able to list using the command "sm  plugins list", right?

Your sourcemod tab looks something like this I guess?
![image](https://user-images.githubusercontent.com/16888566/97917373-ace3ca00-1d54-11eb-9a57-9277de51cc30.png)

The only problem seems to be the practice mode plugin, which does not show up in the list together with the other plugins?

Assuming you extracted the files into the correct location you should see the following directory structure:

<folder where you installed csgosl>\server\csgo\addons\sourcemod\plugins

and in the plugins folder you should see the practicemode.smx file. If this is all true I see no reason why it all shouldn't just work.

Possible problems:

1. sourcemod is disabled in csgosl which will mean the you will see the folder <folder where you installed csgosl>\server\csgo\addons\sourcemod.DISABLED
2. The plugin file is not present in <folder where you installed csgosl>\server\csgo\addons\sourcemod\plugins but is present in <folder where you installed csgosl>\server\csgo\addons\sourcemod\plugins\disabled -- this will mean your plugin will not be loaded
3. You extracted the plugin archive into the wrong location

I decided to try the practice mode plugin, enabled sourcemod in the sourcemod tab (SaveAll), extracted the practice mode plugin (see top window) then copied the addons folder into the <folder where you installed csgosl>\server\csgo folder (overwriting all files). Then just started a server and entered "sm plugins list" and as you see the plugin is listed as nr 20 below.

![image](https://user-images.githubusercontent.com/16888566/97918938-36949700-1d57-11eb-8206-e9f5e01c4018.png)

Hope this helps, or keep asking :)

**Comment by klankisbad** [comment]
Yes! It did help! Thank you so much. I didnt understand that the plugin needed to be copied to two different places. Thank you for the help. You and csgosl have been a major help.
