### ISSUE TITLE
Pugmode.smx not loading?

### ISSUE THREAD

**Issue by Irunga** [lenosisnickerboa/csgosl#298]
Hi, I recently downloaded CSGOsl and I added practice mode and admin_advance_esp plugins, but pugmode seems unable to load, despise if I unload the others plugins or not, or try to manually loaded. What can I do to solve it?

**Comment by lenosisnickerboa** [comment]
I think you need to ask the modding community about that. If you installed things yourself on top of csgosl installed mods I can't really help.

**Comment by lenosisnickerboa** [comment]
No response.
