### ISSUE TITLE
Game Server Login Token not working

### ISSUE THREAD

**Issue by harryverrall** [lenosisnickerboa/csgosl#303]
Hi there, I have added my game server token to the correct place in the steam page. everything is stock as I just downloaded the application but every time I start the server it says it is in lan only mode for not specifying an account token.

**Comment by lenosisnickerboa** [comment]
You checked this instruction? [Public server](https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server)

Sure the GSLT hasn't expired? You can check your GSLT by logging in at [Gameservermanager](https://steamcommunity.com/dev/managegameservers)

Other than that this usually just works. If you still have problems please use this [form](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug) to properly report your problem.

**Comment by lenosisnickerboa** [comment]
No answer, closed.
