### ISSUE TITLE
Firewall configuration - tclkit not happy

### ISSUE THREAD

**Issue by Ghost129er** [lenosisnickerboa/csgosl#304]
Just wondering, what all inbound/outbound ports are needed? I have a /very/ tight firewall with very strict stuff as to not let things connect here and there, upon leaving my firewall on allow all connections (outbound) then CSGO SL boots up successfully. It's usually wget.exe that gets hung up on my firewall..

Maybe a way to disable the errono the start bat or something or disable checking for updates if it's related to that..? There was no way to privately message you as this wasn't a 'breaking' bug but just something on two cents..

**Comment by lenosisnickerboa** [comment]
The two things that come to mind are 
- update check, csgosl will use wget to check if a new csgosl update is available. Can be disabled in Application->applicationcheck
- show local and external ip, csgosl will use wget to get your external ip. Can be disabled in Application->getips

**Comment by Ghost129er** [comment]
Unfortunately, no luck. I was really confident it'd work but it seems to still be attempting to fetch something and only thing I could really thing of was the run bats and such which are told to 'do update' if depending on some error level.

Edit: Just had my CSGO SL crash upon this (firewall on strict mode), 101% thing it's update/start related, check this out:
https://i.imgur.com/uTrO67C.png

**Comment by CJNiiva** [comment]
Dont eat the bats, we dont want another corona, sry, I had to

6. apr. 2021 kl. 13:26 skrev Ghost129er ***@***.***>:

﻿

Unfortunately, no luck. I was really confident it'd work but it seems to still be attempting to fetch something and only thing I could really thing of was the run bats and such which are told to 'do update' if depending on some error level.

Edit: Just had my CSGO SL crash upon this (firewall on strict mode), 101% thing it's update/start related, check this out:
https://i.imgur.com/uTrO67C.png<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fi.imgur.com%2FuTrO67C.png&data=04%7C01%7C%7Cd7b2f0cda3044d9e234808d8f8eed356%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637533051921391836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mu2dM4H5xr5HmlKsqYwKsj0nLXhW%2BFhvjSDd%2BSLSlpQ%3D&reserved=0>

**Comment by lenosisnickerboa** [comment]
Yes, guess wget is used a lot. I think it will be hard to get it working without it. I this case csgosl will try to cache all maps, i.e. download small pictures for all maps to display in the Maps tab. There's currently no way to disable this caching in csgosl. There are also settings in the Steam tab for validateinstall and validateworkshopmaps which you want to make sure are disabled since they will do network access. 

Is there no way you can configure your firewall to allow "everything csgosl does"? :) No idea what kind of firewall you're running.

**Comment by Ghost129er** [comment]
Yeah don't worry about it, just wanted some feedback from your end - this program is wonders and for me to nag about it would be unfair, just wondered if you knew how abouts to go with this, but all is good, might be the custom maps for sure since I run so many and the other Vanilla install didn't have any.

Cheers and thanks!
