### ISSUE TITLE
GUI Not opening

### ISSUE THREAD

**Issue by coshiro1** [lenosisnickerboa/csgosl#305]
Downloaded csgosl on Linux (Ubuntu Mate) yesterday, was working fine until today I might've done something to it and the GUI won't open. Terminal shows this: https://i.ibb.co/vwkw5Wn/csgosl-terminal.png
Reply if you need any additional info, TIA

**Comment by lenosisnickerboa** [comment]
The "I might've done something to it" is a but unspecific :) But if you haven't changed too much in the map groups section I would try stopping csgosl, moving csgosl/cfg/mapGroups.cfg and csgosl/cfg/mapGroupsMapper.cfg somewhere else, and then start csgosl again to see if that fixes the problem. Should start and cerate new empty default files for the files you moved away.

**Comment by coshiro1** [comment]
I'm very sorry for not replying, I ended up reinstalling and it works just fine now haha. Thank you for the response!
