### ISSUE TITLE
 ./csgosl.sh

### ISSUE THREAD

**Issue by Acu1ty** [lenosisnickerboa/csgosl#308]
Hello, 

currently i have one problem i follow steps in instructions but when i run  ./csgosl.sh i get error:

no display name and no $DISPLAY environment variable
    while executing
"load /usr/lib/x86_64-linux-gnu/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.10" script)
    invoked from within
"package require Tk"
    (file "bin/csgosl.tcl" line 6)

Can someone help me to solve this isuess?

**Comment by lenosisnickerboa** [comment]
You need a graphical environment to run csgosl on linux. You must have the DISPLAY variable set correctly in order for the csgosl GUI to have a place to display itself. See this thread for more info: https://github.com/lenosisnickerboa/csgosl/issues/61

A quick way to determine if you have X/DISPLAY setup properly is to just enter the command 'xterm'. If you get the same error as you get above then make sure to set the DISPLAY variable properly first, until 'xterm' gives you a new window without errors.

E.g. try

`export DISPLAY=:0`
`xterm`

If this doesn't work, csgosl will not work either.
