### ISSUE TITLE
!ws, !knife, and steam token not working

### ISSUE THREAD

**Issue by alphaleighezra** [lenosisnickerboa/csgosl#309]
I clicked on weapon skins and knife but when I click save changes. it unchecks.
And also, I've put my steam token but the cmd said that I have no token
https://imgur.com/a/p7UEnVr

**Comment by lenosisnickerboa** [comment]
You really need to provide more info about the first part, preferably screenshots...

About the second part, did you uncheck "lanonly" in server tab? Did you read everything [here](https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server) If you did, please provide the complete log, not just the error message.

**Comment by lenosisnickerboa** [comment]
closed, no response.
