### ISSUE TITLE
(Ubuntu 20.04.2 LTS server) "Can't find package Img" error when executing csgosl.sh

### ISSUE THREAD

**Issue by tankirules** [lenosisnickerboa/csgosl#311]
![image](https://user-images.githubusercontent.com/35437320/128827589-e436bfcc-588a-427f-84a9-a10d16e8b005.png)
I am very new to linux and I installed tcl so I'm not sure how to fix this, google searches are inconclusive for me.

**Comment by tankirules** [comment]
Solved: I used "sudo apt install libtk-img" and it worked

**Comment by lenosisnickerboa** [comment]
Thanks for reporting back the solution. I think you may need to install some more stuff, see this tutorial: https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server

**Comment by tankirules** [comment]
> Thanks for reporting back the solution. I think you may need to install some more stuff, see this tutorial: https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server

Oops I did not even see that page, I kinda thought it was gonna be simple and easy like windows

**Comment by lenosisnickerboa** [comment]
Well, linux comes in so many flavours so it's kinda hard to preinstall
everything needed on all flavours. I've just added some notes on the
distros I've tried. Glad it worked out for you!
