### ISSUE TITLE
RconCli - server is not started?

### ISSUE THREAD

**Issue by MevliN** [lenosisnickerboa/csgosl#312]
![image](https://user-images.githubusercontent.com/79210214/137207242-99682e8e-32be-41de-bb79-07b6eb801646.png)

This appears in the RconCli tab. Rcon works normally in-game

**Comment by lenosisnickerboa** [comment]
Can't really help you with this one. I tried it out on the latest version 2.10 and it worked just fine (had to use overrideport 27016). Could be anything really, something in you windows? firewall? You don't provide any of the information suggested in [reporting a bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug) either so can't even guess anything.

If you haven't done a lot config I would suggest simply performing fresh reinstall in another location, starting the server without changing any more options than required (enable rcon in Server tab, run lanonly mode) and make sure rconcli works before proceeding with any more options.
