### ISSUE TITLE
Cannot get autoexec to work

### ISSUE THREAD

**Issue by tomvernon** [lenosisnickerboa/csgosl#313]
I cannot get any config files that are ticked under the "on server start" section to load when the server starts. I am probably missing something here, but I cannot find any tutorial online that gives instructions on how to use the autoexec feature. The wiki has very little information on how to set it up at all and was not much help to me.

**Comment by lenosisnickerboa** [comment]
Just tried it on latest version 2.10 and had no problems. Are you sure you're putting your cfg file in the correct location using correct names (Windows e.g. appends .txt to files if you don't explicitly delete it).

Some screenshots from my test:

Added a test.cfg file here:

![image](https://user-images.githubusercontent.com/16888566/140193079-1c74777d-4694-4605-a963-d003c7f8fad4.png)

With this contents:

![image](https://user-images.githubusercontent.com/16888566/140193159-028fb06f-9ea4-4deb-92f2-bae2a94dc222.png)

Restarted csgosl and went into the Autoexec tab and there was onserverstart_test_cfg which I ticked to enable it:

![image](https://user-images.githubusercontent.com/16888566/140192986-dd881271-18c1-4768-bcb7-da6c891db3cb.png)

When I start the server and browse the server log window I see this:

![image](https://user-images.githubusercontent.com/16888566/140193413-30485018-491a-46a1-93be-0f271d4d0f10.png)

Seems to work. Please let me know how it goes.
