### ISSUE TITLE
CSGOSL can't connect to server online

### ISSUE THREAD

**Issue by curtismany** [lenosisnickerboa/csgosl#314]
Hey there guys,

I've set up a server using CSGOSL following all the steps, all configured, lanonly disabled etc. I've seen many videos so I doubt the configuration itself is bad. I opened some ports, the port I use in CSGOSL 27015 --> TCP/UDP and then 27020, 27005, 26900 --> UDP (I found out these may also be needed). I have allowed the ports through the firewall and even disabled it entirely but it won't work, the server seems to be running OK but I can't see it in my list when in CSGO and I can't connect directly through f8 either. In case it comes to your mind, I have also disabled the firewall of the router not only windows defender and same happens.
The mind-blowing thing is that yesterday one of the 200 times I tried I could see it and connect, my friend did connect too but then after restart, it won't work again.

Any help would be much appreciated, thanks.

**Comment by lenosisnickerboa** [comment]
This sounds like a general csgo issue, not really related to csgosl. There are a number of possible issues for this not to work (OS firewall, router settings, ...), perhaps a general csgo forum can help you? 

You can take out csgosl from the equation by simply running the generated command script cmd-start.bat located here:

![image](https://user-images.githubusercontent.com/16888566/140268466-44ec45a9-4a9f-4c4d-bf02-9a32f7eae385.png)

This script starts csgo with the options you have entered in csgosl. You can change stuff in this script if you want to try out something else, csgosl will only recreate this script when you Save from csgosl.
