### ISSUE TITLE
Turn on Killer replay on casual ?

### ISSUE THREAD

**Issue by clefrks** [lenosisnickerboa/csgosl#315]
how do i turn on killer replay or "Death Cam"?

**Comment by clefrks** [comment]
closing this, need to enable GOTV for killer replay to work

**Comment by wesc88** [comment]
I'm having a trouble to enable the killers cam replay (death cam) on my dedicated csgosl server, anyone please can help me?

GOTV is enabled and running, spec_replay_enable is also enabled in casual game...but in game nothing happens
does I need to disable kill cam feature to work the death cam ?
