### ISSUE TITLE
I cant start CSGO while the server its running

### ISSUE THREAD

**Issue by elnexreal** [lenosisnickerboa/csgosl#316]

**Comment by elnexreal** [comment]
As the title says im unable to open CSGO, i dont know why steam just detects like im playing csgo and when i close it (through steam client) just closes the server 
![image](https://user-images.githubusercontent.com/40328573/143325719-ba2432e1-c33e-4bd7-ad55-9127ee6f99bc.png)

**Comment by lenosisnickerboa** [comment]
Yup, that's how it is. CSGO can't separate its server from its client when running on the same machine, and hence if the server is running will not start the client. I have to make sure the server is not running before starting the client. If you have some other machine to host the CSGO server this problem of course goes away.
