### ISSUE TITLE
Plugins Not loading 

### ISSUE THREAD

**Issue by SnappierSoap318** [lenosisnickerboa/csgosl#318]
Getting this upon server startup 
`Unable to load plugin "addons\metamod\bin\win64\server"`
read on the modded forum that it is ok for meta mods to show this error, but pugsetup plugin fails to start.

**Comment by lenosisnickerboa** [comment]
Currently got no time to work on csgosl. I see there's a new pug-setup version 2.07 (csgosl packs 2.0.5), does manually upgrading help perhaps?

**Comment by lenosisnickerboa** [comment]
No reply, closing
