### ISSUE TITLE
Adding custom plugins in the sourcemod tab

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#32]
the title says it all, would be cool to add plugins in the sourcemod tab, and if this is an option, I dont see it under the help section:)

**Comment by lenosisnickerboa** [comment]
Agree. Unfortunately sourcemod plugins are not standardized, i.e. they are all installed and configured differently so I don't see how I could add this feature.

What I can do is to take requests for plugins you and others want support for and I'll add them into the sourcemod tab as you suggest. It's just not automatic, you will have to request support.

**Comment by lenosisnickerboa** [comment]
Closing issue. Request any sourcemod plugins you want.
