### ISSUE TITLE
Program fail to start when server installed

### ISSUE THREAD

**Issue by PrinzLast** [lenosisnickerboa/csgosl#320]
I'm running csgosl ver 2.10 on windows server 2012r2, and found this issue when I tried to restart it.
After initial installation, csgosl proceed normally to download server files, and can be restart for only once after the csgo files are installed by steamcmd, and servers can be started normally.
The problem is, csgosl cannot launch after this time. The program window just won't show up again, I can see tclkit and wget in background procedures but they don't seem to be active. However, if I delete the server files, csgosl can be started again, telling me to download server files. Any ideas about what's going on?

**Comment by PrinzLast** [comment]
Update: After waiting for some time I got an error like this.

![微信图片_20211217150750](https://user-images.githubusercontent.com/87886736/146503859-2e629762-18cb-4ad1-837a-33879edd4ea5.png)

**Comment by lenosisnickerboa** [comment]
No idea why this fails (or hangs) in your case. It is a simple download of an image from the workshop which seems to hang forever. How long is "some time"? The caching of map images could take several minutes the first time.

**Comment by PrinzLast** [comment]
> No idea why this fails (or hangs) in your case. It is a simple download of an image from the workshop which seems to hang forever. How long is "some time"? The caching of map images could take several minutes the first time.

Well if it is about downloading files from the workshop I guess the cause is the GFW(I'm hosting the server in China). This error normally pops up after 5-10 minutes of waiting. I am wondering if you can add some sort of bypass in the code to address this issue? Other functions worked perfectly, just this annoying error.

**Comment by lenosisnickerboa** [comment]
Hi again,

I just released 2.11 which adds an option to disable Steam Workshop map loading. Try it out and see if that solves your problem.

You need to go into the Application Tab and disable "loadmapfromworkshop" in the Troubleshooting section.

I also think you need to make sure Steam workshop map validation is disabled in the Steam tab under the Installation section, option validateworkshopmaps.

In case csgosl hangs before you get a chance to change these settings you can change this manually by going into the <csgosl installation directory>/csgosl/cfg and edit the following two files: (close down csgosl first)

application.cfg, add a line like this:
loadmapfromworkshop "1"

steam.cfg, add a line like this:
validateworkshopmaps "0"

If these lines already exist, just edit them instead and set loadmapfromworkshop to "1" and validateworkshopmaps to "0".

After the edit is done, start csgosl again.

Please let me know if this solves your problem.

**Comment by PrinzLast** [comment]
It is solved ,tks a lot.
BTW I guess it shall be loadmapfromworkshop "0" in the cfg.

**Comment by lenosisnickerboa** [comment]
Great to hear! Thanks for reporting back!

Yes, it should be "0", my bad.
