### ISSUE TITLE
Error: child process exited abnormally

### ISSUE THREAD

**Issue by Pasokando** [lenosisnickerboa/csgosl#321]
This problem happens when I try to install server
![image](https://user-images.githubusercontent.com/65315156/152455342-eeedf269-23c1-4370-bad3-7031a7f2f3d6.png)

**Comment by lenosisnickerboa** [comment]
Have you tried installing in different locations? In a clean/empty directory? Ensured your disk has enough free space?

**Comment by lenosisnickerboa** [comment]
Closed, no reply
