### ISSUE TITLE
SM Mapchange not working with banprotection enabled.

### ISSUE THREAD

**Issue by zlohbierdcul** [lenosisnickerboa/csgosl#322]
Hey, 
I have an Issue, when I want to change the map with the Sourcemod Mapselector, it does not change it if the banprotection is enabled. Is there any way to make it work?

Btw, great software u made there!

**Comment by lenosisnickerboa** [comment]
This sounds really odd. There's no relation between ban protection and MapSelector. Are you sure enabling ban protection makes map selector fail and disabling it again makes it work? I mean, will it actually work/not work when you toggle ban protection on/off? Strange...

**Comment by lenosisnickerboa** [comment]
Closed, no response
