### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Xyan1337** [lenosisnickerboa/csgosl#323]
When i press "start server" the cmd console opens up and then after one second closes, i was able to screenshot this maybe it can help
I don't know what causes it to crash/don't start
![srcds_kbU7nrrgxr](https://user-images.githubusercontent.com/50889915/159161182-7fd5321e-afec-4be7-81f3-c3cee1037d7d.png)

**Comment by lenosisnickerboa** [comment]
Hi! There's a lot of information missing in your report, please see this for some hints on what to provide [Report a bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)

I don't play csgosl anymore but updated both client and server and started without issues, so it is not a general problem at least.

If you once had csgosl running, performed some change and then things stopped working, reinstalling from scratch (in a new location) is always an option. It doesn't take long and then you can reapply your changes one by one. If it never worked for you I would start looking for e.g. availabe harddisk space on the disk you're installing to.

**Comment by lenosisnickerboa** [comment]
Closed, no response
