### ISSUE TITLE
No Steam account token was specified. 

### ISSUE THREAD

**Issue by HoshinoSyou** [lenosisnickerboa/csgosl#324]
Hello, thanks for your csgosl. This is the first time that I use csgosl. Today I found a strange phenomenon. If you can help me, 

I have filled the token from https://steamcommunity.com/dev/managegameservers, but it can't also link to steam:
No Steam account token was specified. 
Logging into anonymous game server account. 
Connections will be restricted to LAN only. 
To create a game server account go to 
http://steamcommunity.com/dev/managegameservers

I haven't found where csgosl changed account token except ./cfg/steam.cfg.
And when I run ./csgosl.sh, it said couldn't open socket: network is unreachable. Maybe it's my server's problem?
![image](https://user-images.githubusercontent.com/61332493/163723658-d652f4f3-2256-4d93-8642-87211633c02c.png)

Thank you for taking the time to read my question!

**Comment by lenosisnickerboa** [comment]
Sorry, can't really say much based on the above. Did you come up with a solution? 

You can disable this part of the code by disabling "getips" in the Application tab. If this is the only issue you have with csgosl.

Also, try reporting using this [template](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)

**Comment by lenosisnickerboa** [comment]
No reply.
