### ISSUE TITLE
Workshop Collection as mapgroup gets reset

### ISSUE THREAD

**Issue by iTitus** [lenosisnickerboa/csgosl#325]
Whenever you restart the application the mapgroup gets reset to `<allmaps>` instead of your workshop collection id.

Additional info: I have no map groups set up.

**Comment by lenosisnickerboa** [comment]
The workshop ids for mapgroups and maps are really meant as "one time" entries, i.e. it will cause the underlying csgo server to download whatever is related to those ids. If you don't want the <allmaps> mapgroup selected I suggest you create a new map group in the mapgroups tab and then select it in the Run tab and now that group will always be selected.

**Comment by iTitus** [comment]
You are right about that, but I want to keep a server "synced" to a workshop collection, so that all added maps are automatically downloaded on the next server start.

**Comment by lenosisnickerboa** [comment]
I see what you want to do. Just don't see how to accomplish it. Will add as "future enhancement"

**Comment by iTitus** [comment]
Thank you.

What about a separate field where one can enter the mapgroup which csgosl will automatically use as a mapgroup and workshop collection on startup?

**Comment by lenosisnickerboa** [comment]
Just released [2.15](https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.15) which supports permanent workshop maps and groups. I implemented it slightly different from above discussions, see [mapgroups](https://github.com/lenosisnickerboa/csgosl/wiki/Host-workshop-map-groups), the last lines. The same goes for maps. So you need to head into the Steam tab and enter the workshop id there. Please try it out and see if it works as you intended. If it does you can close this issue.
Not sure if this will update maps in the mapgroup on-the-fly? I.e. if the mapgroup is updated (new maps, updated maps) will it require a server restart or will the update take effect immediately (on next map change?)
Thanks for the hint anyway!

**Comment by iTitus** [comment]
Work as advertised 👍
