### ISSUE TITLE
Not possible to select sv_game_mode_flags in gamemode dropdown

### ISSUE THREAD

**Issue by iTitus** [lenosisnickerboa/csgosl#326]
As one can see [here](https://developer.valvesoftware.com/wiki/CS:GO_Game_Modes) there exists a convar `sv_game_mode_flags` to enable short matches or team vs team/ffa deathmatch.
It would be nice to have support in the game mode drop down on the run tab.

**Comment by lenosisnickerboa** [comment]
will have a look at this (not playing csgo anymore so didn't spot this change)

**Comment by lenosisnickerboa** [comment]
Just released [2.12](https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.12) which adds this support. Try it out and see if it does what you want. Since I don't really play anymore I did a quick test and it seemed to work. Please report back if this what you intended.

**Comment by iTitus** [comment]
Yeah that works perfectly, thanks!
