### ISSUE TITLE
SourceMod and MetaMod not working

### ISSUE THREAD

**Issue by KondiU** [lenosisnickerboa/csgosl#327]
![image](https://user-images.githubusercontent.com/56745473/169659169-efc7207c-dc59-43bd-89cc-de8c1e7e271e.png)
![image](https://user-images.githubusercontent.com/56745473/169659190-35a94a4b-e450-4606-a9ef-450ede839770.png)
![image](https://user-images.githubusercontent.com/56745473/169659255-e627f32f-dc3d-40ab-9186-23aa50da7cd8.png)

My server is working fine online, but both Sourcemod and Metamod is not working on it even tho I have everything checked  to make it work and I gave myself an admin in csgosl panels.

When I type "sm" or "meta" in console it says it's an unknown command

**Comment by KondiU** [comment]
Ok, fixed it, seems like it's a common problem inside the SourceMod on Ubuntu 22.04

https://www.reddit.com/r/GlobalOffensive/comments/s8peb9/sourcemod_metamod_wont_load_version_gcc_700_not/

**Comment by lenosisnickerboa** [comment]
Thanks for reporting and closing the issue 👍
