### ISSUE TITLE
Can you get a GLS ban for this?

### ISSUE THREAD

**Issue by dam2452** [lenosisnickerboa/csgosl#329]
Can you get a GLS ban for this?

**Comment by lenosisnickerboa** [comment]
If you mean a GSLT ban, sure. Read more [here](https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod)

**Comment by dam2452** [comment]
Damn, but a lot of servers have weapon skins and knife.  Can anything else be done to have skins and knife on the server and not get a GSLT ban?

**Comment by lenosisnickerboa** [comment]
Don't think so, [this is pretty clear](https://help.steampowered.com/en/faqs/view/07AF-502E-A104-BD4B)

**Comment by dam2452** [comment]
I guess it's better not to risk it.

**Comment by lenosisnickerboa** [comment]
If you mean GSLT bans and you run not authorized mods, yes. See more here:
https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod
