### ISSUE TITLE
can't find package Tk     while executing "package require Tk"

### ISSUE THREAD

**Issue by dam2452** [lenosisnickerboa/csgosl#330]
I am a Linux novice and I have this problem:
![obraz_2022-05-26_193734159](https://user-images.githubusercontent.com/81230036/170544277-9085f654-ff49-4604-a14d-091a84f9a019.png)

**Comment by lenosisnickerboa** [comment]
Did you read linux part of this?
https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server

**Comment by dam2452** [comment]
Yes, and I did everything as it says there, but using this command: sudo apt install tcl libtk-img lib32gcc1 lib32stdc++6 net-tools it sends me this message, and I think it shouldn't.
![C2868329-E6F8-4172-BDDD-E3DBC85BBEC6](https://user-images.githubusercontent.com/81230036/170556014-b2127bad-c3e9-4a9a-ad9e-db47788bdfaf.jpeg)

**Comment by lenosisnickerboa** [comment]
Could be something changed since I wrote the docs. Why not try the
suggested package? lib32gcc-sl? Don't have time to try this now.

**Comment by lenosisnickerboa** [comment]
Did you try lib32gcc-sl?

**Comment by dam2452** [comment]
Thank you very much for your help, but for now I will let go of the linux topic and make my server on windows server.  When I get back to Linux and I need something or something won't work, I will contact you.

**Comment by dam2452** [comment]
>
