### ISSUE TITLE
csgosl cannot open 

### ISSUE THREAD

**Issue by huoyan1231** [lenosisnickerboa/csgosl#331]
system Windows10
I try to open csgosl but it not
 it happen every time
it works before
I don;t do anything

**Comment by lenosisnickerboa** [comment]
Really have nothing to go by here. Reinstall in different folder perhaps?

**Comment by huoyan1231** [comment]
> 这里真的没什么好逛的。也许重新安装在不同的文件夹中？

if i delete or rename server folder. csgosl can be opened

**Comment by lenosisnickerboa** [comment]
Closing. Reopen if problem still exists.
