### ISSUE TITLE
csgosl is missing important info regarding WMI and Windows 11 22572+ and probably also Server versions

### ISSUE THREAD

**Issue by ViolatorX** [lenosisnickerboa/csgosl#337]
I couldn't get Install Server to work and found out that WMIC has been deprecated by MS.
It is not installed by default from Windows 11 22572 and probably some of the Windows Server releases.

The fix is simple, since WMI is offered as an optional feature:

1. Open Settings by pressing the Windows + I keys together.
2. Then, chooses apps Then, click Optional features.
3. Click the Feature display button.
4. Search for Wmic and check the box next to it and press Next.
5. Click the Install button.

I think that the info above should be added to the Wiki, since it wasn't solved in an earlier ticket from another fellow user, I found that ticket by pasting the entire error code into Google.

**Comment by lenosisnickerboa** [comment]
Thanks! Took a while but have now added info about it in the server install [page](https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server)
