### ISSUE TITLE
CSGO Server not starting?

### ISSUE THREAD

**Issue by fiendish69** [lenosisnickerboa/csgosl#340]
Hello,

I'm encountering a persistent issue with hosting a public csgo server on my machine. I've gone through and tuned the parameters to what I like, enabled public access including port forwarding and all that, and yet at the final hurdle of actually starting the server, I continuously run into an error that doesn't start the server and I can't figure out. Here's a snippet of the terminal when this issue occurs:

![image](https://user-images.githubusercontent.com/125946559/220252691-e76a1462-7967-42a0-89e0-a7a975adaf9b.png)

As soon as I hit "start server" things proceed normally, and then it hits this roadblock. I've attempted to debug it and figure it out on my own, but I don't have the best understanding of things like this.

Here is some relevant info you may find useful:
OS: Ubuntu 22.04 (Hosted in a Proxmox VE Environment)
CSGOSL Version: 2.16
I suppose it's also worth mentioning that as this is a fresh VM, I haven't installed CSGO on it, but I didn't see that as a requirement to get a server up, or maybe I'm just blind.

I've played with this prior and was able to get a server up and running on my windows laptop without much headache, so I have no clue where to begin with fixing this. Please let me know if you require any additional info, and I look forward to getting this figured out! Thanks.

**Comment by lenosisnickerboa** [comment]
Just try changing your server name to something without a lot of special characters. I see you have e.g. ">" and "<" characters and I suspect they mess up starting the server. Head into server tab, option name and enter something without special characters.

**Comment by fiendish69** [comment]
Hi,

I did that, renamed it to just normal characters, and now I am facing another issue, now it's saying that it failed to open 'libtier0.so' and citing GCC_7.0.0 as not found... compounding problems are fun.

Here's a screenshot of what I'm facing now:
![image](https://user-images.githubusercontent.com/125946559/220785830-29c0da3b-a6a2-4e64-a4e3-75fb44a063d8.png)
At least the original problem went away, do you want me to make a new issue for this?
Thanks

**Comment by fiendish69** [comment]
Update, as found in [this](https://forums.alliedmods.net/showthread.php?t=336183) forum post, changing ./libgcc_s.so.1 to libgcc_s.so.1.b has fixed the issue and my server is up and running. Two problems one issue thread! Should be good to go now, thanks for your help!

**Comment by lenosisnickerboa** [comment]
Great to hear! Closing this issue then.
