### ISSUE TITLE
csgosl ignore all server cfgs

### ISSUE THREAD

**Issue by usgitAz** [lenosisnickerboa/csgosl#341]
when i change the cfgs like server.cfg , gamemodeall.cfg gamemode_causal.cfg  folders :  csgosl/cfg  csgosl/server/csgo/cfg   ...
with text editor and  click the start server or update server , my changes will be completely erased
How to disable ignoring by csgosl?

start with cmd_start ? Not a good idea at all

**Comment by lenosisnickerboa** [comment]
I'm afraid you can't do that, i.e. manually edit config files AND use csgosl. Do one of those. csgosl will always overwrite config files with the contents you have configured in the GUI. csgosl is aimed at people who can't or don't want to edit config files themselves. 

In your case you can of course use csgosl for the initial install, change everything you want using the GUI, and then stop using csgosl and instead use the startup script. But as soon as you run csgosl it will again overwrite any manual changes you may have made. Or you do everything yourself, starting from initial install. That gives you full control.

I don't understand the comment "start with cmd_start ? Not a good idea at all". Why not? It's what would work for you if you want to use csgosl as an "installer".

**Comment by usgitAz** [comment]
I think if there is an option inside the program that can prevent changes by the program, it can be very useful!
For example I want to set mp_solid_teammate to 2 or 0 ! But the program does not change it and it is always on 1 .
I created cvar inside the program, but it still changes to 1 !!
What solution do you suggest for proper setup and update?

**Comment by lenosisnickerboa** [comment]
I guess what you are suggesting is "add an option which disables the whole purpose of csgosl". Instead I think it's easier just not to use csgosl and perform your own manual editing of config files. csgosl gives you a GUI where you can edit a selection of options and then csgosl creates the corresponding config files for you. If you disable the config file creation, what's the csgosl purpose?

**Comment by usgitAz** [comment]
I don't want to completely disable the purpose and functionality of csgosl !
I just want to solve a ridiculous bug that I said above!
My question is , it not possible to stop csgosl manipulation on cfg files?

**Comment by lenosisnickerboa** [comment]
Anything is possible in software, but I don't see the point. If I added such an option, csgosl wouldn't be able to read config either since it relies on being able to read the config files it has written. So, then you have a GUI which can't load or save settings, and as a consequence of that can't start, stop or update the server (since it can't construct the command lines without the config). Then what's the point with csgosl? Again, if you wan't to tinker with configs you can use csgosl as an installer and then do the rest yourself.
