### ISSUE TITLE
Bug RETAKE Mode

### ISSUE THREAD

**Issue by Minimalistic09** [lenosisnickerboa/csgosl#348]
Hello guys!
i have installed Retake mode on my CSGO Server, but when i make the second plant i get this bug, but in all maps.
https://www.youtube.com/watch?v=jm-511lhKFs
Any know what is happen? :S

**Comment by lenosisnickerboa** [comment]
Anyone?
I think you might get better help on some general csgo forum. Here I personally only deal with csgosl related issues and this doesn't seem to be one.

**Comment by lenosisnickerboa** [comment]
Closing, no responses.
