### ISSUE TITLE
Failed get into the server

### ISSUE THREAD

**Issue by Q852456q** [lenosisnickerboa/csgosl#349]
Server seems working well. But when I try to try to connect it, CSGO shows me:
Resource materials\panorama\images\icons\ui\globe.svg failed to load.
PNG load error Interlace handling should be turned on when using png_read_image.
I 've read wiki,and I can't solve it.

**Comment by Q852456q** [comment]
I check my file, there's nothing called "ui".

**Comment by lenosisnickerboa** [comment]
You're leaving a lot of information out...
Like does it happen for all maps, or just some? If you try changing the hosted map do you still get the same issue?

**Comment by Q852456q** [comment]
> 

It's my fault. something wrong with my openwrt that I can't control my firewall to open UDP protocol. The problem has been solved. I'm sorry for wasting your time.
