### ISSUE TITLE
I get a fatal error whenever I open csgosl

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#35]
I dont know what it is, and the error is really hard to read, and also, you could easily update it so you can copy paste it:P so I'm just gonna give you a screenshot of the issue:) [The error](https://gyazo.com/5421db4142ced86f08a0d3eaf402e0cb)

**Comment by CJNiiva** [comment]
I just want to let you know that I found the solution, just delete all the workshop folders inside of /csgo/maps/ and /maps/graphs/

**Comment by CJNiiva** [comment]
I also want to add that the reason this is happening is because the server was shutdown (incorectly) by the csgosl launcher while downloading a workshop map, the server should be shutdown with the quit command, so it could very well be a easy fix :) (no I'm not salty, and no I dont know how to do this myself, but I just want to help your program to become the best program around:D)

**Comment by CJNiiva** [comment]
the program just presses the X button, but it should be done with the command

**Comment by lenosisnickerboa** [comment]
I have added this to the improvement list. It is a problem in both linux and windows.
