### ISSUE TITLE
Auto server upgrade doesn't work (Failed to get latest release!)

### ISSUE THREAD

**Issue by zolikonta** [lenosisnickerboa/csgosl#356]
Auto server upgrade mentioned in the wiki doesn't work.
https://github.com/lenosisnickerboa/csgosl/wiki/Upgrade-a-server

I get these in console:

> 19:15:42 Getting latest release...
19:15:42 Wget: https://github.com/lenosisnickerboa/csgosl/releases/latest -> release-info.txt
19:15:43 Wget: https://github.com/lenosisnickerboa/csgosl/releases/latest -> release-info.txt OK
19:15:43 Failed to get latest release!

OS: Windows 10
csgosl version: 2.17 (didn't work for earlier versions either)

**Comment by lenosisnickerboa** [comment]
Thanks for letting me know! Fixed in this release https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.19

Unfortunately you need to perform a manual update since releases prior to 2.19 no longer will detect new releases.

**Comment by zolikonta** [comment]
Thank you very much @lenosisnickerboa for fixing it this quick. Good job!

**Comment by Alex72GOLD** [comment]
Здравствуйте русифицируйте программу пожалуйста чтобы была на русском языке.
Hello, please Russify the program so that it is in Russian. #https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.19
