### ISSUE TITLE
Error When launching server from CSGOSL

### ISSUE THREAD

**Issue by AirForce101HD** [lenosisnickerboa/csgosl#37]
When I launch my server from CSGOSL i get error "Error reading steam application id. Please either write it to steam_appid.txt or use the launcher!"

**Comment by lenosisnickerboa** [comment]
I assume you have installed the server using csgosl?

I googled your problem and found various explanations and solutions. 

But I guess the first thing to try is simply to make sure the steam_appid.txt files are present with correct contents. I checked both a windows and a linux install and this is what works for me:

Let's say you installed csgosl in c:\csgosl\ then you should have the following files:

c:\csgosl\server\steam_appid.txt

This file should contain the number 730. If the file doesn't exist create it and then simply enter the number 730 into the file and save it.

Then in c:\csgosl\server\bin\steam_appid.txt

This file should contain the number 745. If the file doesn't exist create it and then simply enter the number 745 into the file and save it.

This is what works for me. Try it and please let me know if that solved the problem.

**Comment by AirForce101HD** [comment]
I have checked both files and they contain the correct values.

**Comment by AirForce101HD** [comment]
I restarted my pc and server seems to work fine now

**Comment by lenosisnickerboa** [comment]
OK, great. Closing...

**Comment by ciesel** [comment]
I changed the text from 730 to 740 and then it worked for me.

**Comment by ciesel** [comment]
had it backwards. make sure the appid and game token are the same #. 730.

**Comment by lenosisnickerboa** [comment]
I checked my files and they are exactly as stated in my previous post:

"c:\csgosl\server\steam_appid.txt
This file should contain the number 730. If the file doesn't exist create it and then simply enter the number 730 into the file and save it.

Then in c:\csgosl\server\bin\steam_appid.txt
This file should contain the number 745. If the file doesn't exist create it and then simply enter the number 745 into the file and save it."

**Comment by Coxaaaa** [comment]
I click on the csgosl icon and it doesn't run anymore ..

Do you know what can be ...

It just stopped working and I don't know how to do it from the beginning.
