### ISSUE TITLE
Empty Dropdown Lists

### ISSUE THREAD

**Issue by AbeSylvestre** [lenosisnickerboa/csgosl#38]
None of the dropdowns in the menu work; the user can't change some options without knowing the exact terms and spelling. Here's an image: http://imgur.com/mgKRjTh

**Comment by lenosisnickerboa** [comment]
I see you're running 1.0.3. Please try the latest version 1.1.1 available here [latest](https://github.com/lenosisnickerboa/csgosl/releases)

Please let me know if the problem is still there.
