### ISSUE TITLE
Admin isn't working

### ISSUE THREAD

**Issue by spiral6** [lenosisnickerboa/csgosl#40]
Added my Steam id to both the admin field and the server host field with "make me admin" checkbox enabled. Neither of these are allowing me admin access.

**Comment by lenosisnickerboa** [comment]
Not sure I understand what the "server host field" is?

What you need to do to be admin is to fill in your steam username and steam id (something like STEAM_1:1:12345678) and click "Make me admin" on the Steam tab. That's all. The admins entry on the sourcemod tab is for adding friends as admins on your server.

**Comment by spiral6** [comment]
I did exactly that. The admins entry on the sourcemod tab and the admins entry on the server tab are both filled out with my name, which regardless, should work no problem. But it doesn't make me admin.

**Comment by lenosisnickerboa** [comment]
I've tested this several times and had other persons doing the same and it just works. Could this be related to all the other problems you're describing in [issue36](https://github.com/lenosisnickerboa/csgosl/issues/36) ? I mean, in the other issue you're stating that settings don't get saved, which would explain why the admin part doesn't work either.

**Comment by lenosisnickerboa** [comment]
Assuming this one is ok to close, let me know otherwhise

**Comment by InstallGentoo11** [comment]
Same here. I have input the write things for sure, but it doesn't work.
