### ISSUE TITLE
where do i put my server files?

### ISSUE THREAD

**Issue by therealpanse** [lenosisnickerboa/csgosl#41]
Not really a bug, but i already got a server running (only with steamcmd), so i dont want to download the 15/16gig again, when migrating to a nice server GUI. What files go where? Any help maybe?

**Comment by lenosisnickerboa** [comment]
I just wrote an instruction for this here [install-from-existing-server](https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server#install-using-an-existing-csgo-server-installation). I'm testing it atm so stay tuned... or go ahead and try it out directly, if you follow the instructions and make a copy of your existing installation nothing bad can happen.

**Comment by therealpanse** [comment]
Wow... that was quick. Awesome. I just went ahead and downloaded everything new last night, since I didn't see the comment while watching the ESL One. But I guess it's not the worst addition for the Wiki. Especially if others have the same problem. Thanks!

**Comment by lenosisnickerboa** [comment]
Thanks for letting me know, I'll close this issue then.
