### ISSUE TITLE
No Steam Token Detected

### ISSUE THREAD

**Issue by Awperino** [lenosisnickerboa/csgosl#42]
I am paraphrasing in the title but is basically says my CSLT is not being used and it is restricting it to lan. I have double checked it is in correctly and even generated a new one for appid 730. I even double checked my apiauthkey.

Also I can't for the life of my find the plugins folder. I tried the csgo/addons/sourcemod/plugins but I can't find an addons folder for server/csgo/addons/sourcemod/plugins (this might be an issue on my part) 

EDIT: So I managed to get it to go online by enabling ban protection. I also managed to get it to go online by providing my own command line in a manual start BUT none of the plugins seem to load.

**Comment by lenosisnickerboa** [comment]
Good that you figured out the connection to ban protection, had forgotten myself :) Read more about it on the sourcemod wiki page [sourcemod](https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod). Disabling ban protection will only allow lan only games to avoid being banned by Valve. Manually adding command line options overriding this protection may get you banned so be aware...

About the plugins folder, it should be located in server/csgo/addons/ where you should see sourcemod and metamod folders. Sourcemod plugins are available in server/csgo/addons/sourcemod/plugins/. At least if you have installed everything using csgosl.

**Comment by lenosisnickerboa** [comment]
Assuming this one is ok to close, let me know otherwhise.
