### ISSUE TITLE
How to enable franug mods with online server?

### ISSUE THREAD

**Issue by DonBongJohn** [lenosisnickerboa/csgosl#44]
Hey guys,

can someone help me? A few friends of mine wanna play with the mods enabled over the Internet.
I know the risk and I don't care so plz help me. 
Which config do I have to edit so that we can finally play?

Thanks for your help!

**Comment by lenosisnickerboa** [comment]
Hi,

I would suggest some kind of VPN-solution as described on the wiki. Then
you're still playing a LAN-only game and can use csgosl as is.
Unfortunately I have not had time to get a stable working VPN-setup so you
will have to google it. If you get it working it would be great if you
could drop me a few lines describing your setup.

As csgosl works now it will not allow these mods at all when not running
lan-only games. What you can do is to enable tracing in the application tab
and see the exact command line used by csgosl. Then change the config files
and command line switches and start csgo manually. On vacation right now so
I can't help you with the details :-(

/Lennart
Den 19 juli 2016 2:05 em skrev "DonBongJohn" <notifications@github.com>:

**Comment by DonBongJohn** [comment]
Thanks for your fast help.

These are my current run options.

> C:\Steamcmd\csgosl>C:/Steamcmd/csgosl/server/srcds -game csgo -console -usercon -condebug +game_type 0 +game_mode 0 +mapgroup mg_active +map de_blackgold +sv_setsteamaccount 761502E9XXXXXXXXXXXXXXXXXX -authkey 8EEC7D7EAXXXXXXXXXXXXXX
-maxplayers_override 16 -tickrate 128 +sv_password XXXXX +hostname "XXXXXXXXX" -port 27015 +sv_lan 0 +sv_lan 0 

I get what your saying but where do I have to add these run options to manually start the server?
On what .bat or .exe I mean.

**Comment by lenosisnickerboa** [comment]
Just start a command prompt, cd to  C:\Steamcmd\csgosl and copy paste the
command line you sent in the email. That will start the server.

Den 19 juli 2016 15:15 skrev "DonBongJohn" <notifications@github.com>:
>
> Thanks for your fast help.
>
> These are my current run options.
>>
>> C:\Steamcmd\csgosl>C:/Steamcmd/csgosl/server/srcds -game csgo -console
-usercon -condebug +game_type 0 +game_mode 0 +mapgroup mg_active +map
de_blackgold +sv_setsteamaccount 761502E9XXXXXXXXXXXXXXXXXX -authkey
8EEC7D7EAXXXXXXXXXXXXXX
>> -maxplayers_override 16 -tickrate 128 +sv_password XXXXX +hostname
"XXXXXXXXX" -port 27015 +sv_lan 0 +sv_lan 0
>
> I get what your saying but where do I have to add these run options to
manually start the server?

**Comment by lenosisnickerboa** [comment]
Assuming this one is ok to close, let me know otherwhise
