### ISSUE TITLE
Server Autoupdate on Windows not working?

### ISSUE THREAD

**Issue by JamyPatch44** [lenosisnickerboa/csgosl#45]

**Comment by lenosisnickerboa** [comment]
If you enable autoupdate it will always autoupdate when you start the
server. This will require a csgosl restart. This works right? If not I will
have to fix it.

But I guess you want csgosl to do this while running? This would require
csgosl to be able to detect server updates (now it just starts steamcmd)
and also detect number of connected players to your server (not to risk
updating/restarting the server with an ongoing game). Complicates things a
bit, is this what you want?

/Lennart

Den 4 aug. 2016 11:34 skrev "JamyPatch44" <notifications@github.com>:

**Comment by JamyPatch44** [comment]
Thank you for the quick reply!

Yes that is correct. I would like it to update while csgosl is running if possible.

Thank you again.

**Comment by lenosisnickerboa** [comment]
Thinking about it I guess it would mean you have to accept csgosl to
restart the server with a possibly ongoing game? I mean even if csgosl
could detect number of connected players the restart could happen between
games or when a new match starts up.

So, is this feature still interesting if it restarts the server as soon as
it detects a new server update?

Den 4 aug. 2016 11:55 skrev "JamyPatch44" <notifications@github.com>:

**Comment by JamyPatch44** [comment]
Yes, for sure it is interesting :+1: 

I'm not sure if something like a warning could be said in the text chat in game before the server restarts could be possible.

**Comment by lenosisnickerboa** [comment]
I'll add it to the todo-list, on vacation now :-) Thanks for the idea.

About the warning, don't know if csgosl can send messages like that, will
have to investigate.

Den 4 aug. 2016 12:49 skrev "JamyPatch44" <notifications@github.com>:

**Comment by JamyPatch44** [comment]
Awesome, thank you very much!

**Comment by lenosisnickerboa** [comment]
Closing this issue. In release 1.7 I introduced "update server on start of csgosl" and "restart and update server at certain time". I think this pretty much solves the problem with automatically keeping a server up-to-date.
