### ISSUE TITLE
Unable to start csgosl: can't find package Img

### ISSUE THREAD

**Issue by kamild1996** [lenosisnickerboa/csgosl#46]
```
kamil@debian:~/Pulpit/csgosl$ ./csgosl.sh 
can't find package Img
    while executing
"package require Img"
    (file "bin/csgosl.tcl" line 7)

```

That's what happens when I'm trying to start csgosl on Debian Jessie.
Am I doing something wrong?

**Comment by lenosisnickerboa** [comment]
You need to install a debian package containing Img. I'm not using debian
but this seems to be what you want:
https://packages.debian.org/search?keywords=libtk-img

Please let me know if this works for you!

Den 5 aug. 2016 3:18 em skrev "kamild1996" <notifications@github.com>:

**Comment by kamild1996** [comment]
Yep, installing this package via apt-get made it work. Thanks!

**Comment by lenosisnickerboa** [comment]
Np
