### ISSUE TITLE
Unable to close the csgosl window

### ISSUE THREAD

**Issue by kamild1996** [lenosisnickerboa/csgosl#47]
When I try to close the csgosl window, it starts behaving weird. The window stays open nonetheless, but it becomes completely unresponsive - the interface doesn't react to my input. The only way to close it is to kill the process.

OS: Debian Jessie x64
Desktop environment: XFCE
Additional info: Using NVidia proprietary drivers

**Comment by lenosisnickerboa** [comment]
How long did you leave it to close down before killing it? If it is the first run it will do some initial stuff like caching and resizing map pics which takes some time. 

Did you manage to start a server before closing down csgosl?

**Comment by kamild1996** [comment]
I didn't even start the server yet. I just launched the program and tried to close it afterwards.

**Comment by lenosisnickerboa** [comment]
Ok, try starting csgosl, let it finish it's init, then start the server,
wait till it's started, stop the server, then close csgosl. I suspect
you're trying to stop csgosl before it is fully initialized.

If you still have problems closing csgosl it would be great if you could
supply logs from the console. You can also enable trace in the application
tab.

Den 5 aug. 2016 11:05 em skrev "kamild1996" <notifications@github.com>:

**Comment by lenosisnickerboa** [comment]
Closing, no reply.
