### ISSUE TITLE
Windows 10: Won't execute, opens in Notepad++

### ISSUE THREAD

**Issue by Zanto413** [lenosisnickerboa/csgosl#48]
So it seems like I don't know how to make this work.
You say we must doubleclick on the vbs file, but if I do that, it just opens in Notepad++.
Even if I tell Windows 10 to open the file with "Microsoft® Windows Based Script Host".

Are there some dependencies you haven't mentioned?
Visual Studio or something?

**Comment by lenosisnickerboa** [comment]
No, no special dependencies like VS, you should be able to just
double-click and it should run.

Youd could try running the script manually from command line (e.g. here
http://windowsitpro.com/scripting/how-do-i-run-windows-script-command-line)
to see if it is just a problem with the filetype association.

If that works I would suggest resetting the .vbs file type association to
default and see if that works.

**Comment by Zanto413** [comment]
Still the same.
Any better options?

![vbs_default](https://cloud.githubusercontent.com/assets/7524975/17668123/321f8a44-6308-11e6-88fd-a7af7a4ae480.png)
![def_prog](https://cloud.githubusercontent.com/assets/7524975/17668124/322382b6-6308-11e6-9edc-f1f866c74751.png)

**Comment by lenosisnickerboa** [comment]
This is a long shot, where did you extract the csgosl archive? If it was to
some external/USB drive it could be a problem. Try copying the complete
folder to somewhere on C:, e.g. the desktop.

Den 15 aug. 2016 4:50 em skrev "Zanto Sagrochskji" <notifications@github.com

**Comment by Zanto413** [comment]
Extracted it in Downloads folder

**Comment by lenosisnickerboa** [comment]
Didn't get an answer about what happened when you tried to run manually?

Otherwise I'm out of ideas, perhaps create a dummy HelloWorld vbs script
and see if that runs?

On Tue, Aug 16, 2016 at 5:23 PM, Zanto Sagrochskji <notifications@github.com

**Comment by Zanto413** [comment]
How do you mean by manually?
General problem is that MS Windows Based Script Host tells Windows or whatever, to open VBS scripts in Notepad++.
But since this doesn't work, I'll just give up and blame Microsoft for making some bullshit (I hate Win 10)...

**Comment by lenosisnickerboa** [comment]
Manually like instead of clicking on the csgosl.vbs file open a command
prompt, cd to the folder where csgosl.vbs is located and enter:

wscript csgosl.vbs

It is described here:
http://windowsitpro.com/scripting/how-do-i-run-windows-script-command-line
(there
is a typo, cscipt should be cscript)

If that works the only problem is the file type association which may be
easier to solve than if you have some error making it impossible to execute
vbs scripts.


On Wed, Aug 17, 2016 at 8:27 PM, Zanto Sagrochskji <notifications@github.com

**Comment by lenosisnickerboa** [comment]
No reply -> closed.

**Comment by CADbloke** [comment]
for Googlers, this was handy for resetting the default for VBS scripts: https://www.tenforums.com/tutorials/8703-restore-default-file-type-associations-windows-10-a.html ...search for "vbs" on that page for the .reg file to fix the file association.

**Comment by lenosisnickerboa** [comment]
Thanks! There's now also a csgosl.bat file that can be used if the
csgosl.vbs file doesn't work.
