### ISSUE TITLE
ckSurf on csgosl

### ISSUE THREAD

**Issue by takeashot54** [lenosisnickerboa/csgosl#49]
When trying to install the cksurf plugin to my server through the server files, the plugin requires the mapcycle.txt to contain the list of current maps on the server. but csgosl overwrites his file. i have added the map list through csgosl, but when in game i am unable to change the map to one of the surf maps in the map group, although the server does launch on a surf map, but not the one in startmap. so i think this plugin is pretty much not going to work with csgosl. also the error log for cksurf contained the following lines: 
L 08/17/2016 - 08:26:10: SourceMod error session started
L 08/17/2016 - 08:26:10: Info (map "de_dust") (file "errors_20160817.log")
L 08/17/2016 - 08:26:10: [SM] Plugin encountered error 25: Call was aborted
L 08/17/2016 - 08:26:10: [SM] Native "SetFailState" reported: [ckSurf] Unable to connect to database (Configuration "cksurf" not found)
L 08/17/2016 - 08:26:10: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 08/17/2016 - 08:26:10: [SM]   [0]  Line 158, ckSurf/sql.sp::db_setupDatabase()
L 08/17/2016 - 08:26:10: [SM]   [1]  Line 1849, D:\ckSurf\csgo\addons\sourcemod\scripting\ckSurf.sp::OnPluginStart()
L 08/17/2016 - 08:31:51: Error log file session closed.

I would like to run a surf server through csgosl but it seems there are some compatibility issues.
please reply if you have any suggestions for how to reinstall the plugin so it will work properly with my server. also if you have a solution for the map issue.

Also, when the server is launched the bots cannot be kicked and the server is not recognizing my Steam Game Server Account. it automatically sets the server to anonymous and sets a separate code.

  Thanks.
[errors_20160817.txt](https://github.com/lenosisnickerboa/csgosl/files/421536/errors_20160817.txt)
[mapcycle.txt](https://github.com/lenosisnickerboa/csgosl/files/421537/mapcycle.txt)
[csgosl server dialog.txt](https://github.com/lenosisnickerboa/csgosl/files/421550/csgosl.server.dialog.txt)

**Comment by lenosisnickerboa** [comment]
Hi,

Never tried this plugin but read about it and here are some things to try:


   1. About mapcycle.txt, you could create a map group (with csgosl) and
   select that mapgroup in the run tab before starting the csgo server. csgosl
   will then add all maps in the mapgroup to mapcycle.txt. If mapcycle.txt is
   the only problem this should be enough to get everything working for you.
   The empty mapcycle.txt should then be properly populated with all maps in
   the mapgroup ýou created.
   2. I see in the log that the plugin complains about map de_dust, and
   there is a note about that ("(by default the plugin won't launch on cs_
   or de_ maps).") here
   https://forums.alliedmods.net/showthread.php?t=264498 item 6. Not sure
   what you need to do but it says by default it will not launch de_ maps.
   3. Same link as above, have you performed all the database stuff? I see
   complaints about "Unable to connect to database (Configuration "cksurf"
   not found)"

Anyway, my two cents. Please let me know if this helps.

/Lennart

**Comment by takeashot54** [comment]
Thanks for the reply,

So with the mapcycle.text thing(before this post) I tried adding a map group through it collection id on steam, which added some maps to the maps tab in csgosl but the mapcycle in game still didn't work, so I made a new map group and selected the maps that it hap downloaded. The. Ran the server and same problem.

And yeh the server won't launch a de_ or cs map, it launches with a surf map but when trying to change the map through the admin commands, the surf maps aren't listed.

Yeh I performed the database stuff, but once I statrted and stopped the server the databases.cfg was reset.

Thanks for your help, maybe I should go add a post in the ckSurf forums.
But if you have any other suggestions that would be great.

**Comment by lenosisnickerboa** [comment]
See below.

On Wed, Aug 17, 2016 at 11:43 PM, takeashot54 <notifications@github.com>
wrote:

> Thanks for the reply,
>
> So with the mapcycle.text thing(before this post) I tried adding a map
> group through it collection id on steam, which added some maps to the maps
> tab in csgosl but the mapcycle in game still didn't work, so I made a new
> map group and selected the maps that it hap downloaded. The. Ran the server
> and same problem.
>
You mean you created a map group in csgosl and you added the maps you want
to be able to select later, selected that map group in run tab and started
the server and mapcycle.txt was still empty?


> And yeh the server won't launch a de_ or cs map, it launches with a surf
> map but when trying to change the map through the admin commands, the surf
> maps aren't listed.
>
> Yeh I performed the database stuff, but once I statrted and stopped the
> server the databases.cfg was reset.
>
 databases.cfg is not touched by csgosl so this should not be a csgosl
issue.

**Comment by takeashot54** [comment]
Yeh, I can probably sort out the map thing but the main problem is that the plugin isn't working any ideas

**Comment by lenosisnickerboa** [comment]
No, sorry. I don't have time to try out this plugin either. If it's popular
I may include it in a future csgosl update, but no promises :)

**Comment by takeashot54** [comment]
Thanks that would be great if it's popular.

**Comment by lenosisnickerboa** [comment]
Closing, opened a separate sourcemod plugins issue for ckSurf and other plugins.
