### ISSUE TITLE
Sourcemod crashed the server

### ISSUE THREAD

**Issue by HenneCuppens** [lenosisnickerboa/csgosl#55]
The old problem is back since this morning, your server will crash when a player is trying to join the server. 

Disable sourcemod till its fixed

**Comment by lenosisnickerboa** [comment]
Know if there's a sourcemod fix for this? I.e. should I release a new
csgosl version with a later sourcemod version included?

**Comment by HenneCuppens** [comment]
yes there is a fix again, the way to fix it is to again update sourcemod

**Comment by lenosisnickerboa** [comment]
Thanks! I will update csgosl during the weekend.

**Comment by HenneCuppens** [comment]
no problem, i will give more information about bugs if i find them, im now bussy on workshop maps not correctly switching with the normal csgo map voting system, you will hear from me soon ;)

**Comment by HenneCuppens** [comment]
but that is a bug from csgo itself

**Comment by HenneCuppens** [comment]
oke, this is weird. Now it doesnt work anymore, ill try to install sourcemod again later this afternoon. Maybe i destroyed something, but the problem is back

**Comment by lenosisnickerboa** [comment]
Upgraded to sourcemod 1.8.0 5946, should fix crash when player enters according to sourcemod devs.
