### ISSUE TITLE
Editing settings for gamemodes in advanced settings bugged

### ISSUE THREAD

**Issue by Tom100080** [lenosisnickerboa/csgosl#56]
When trying to edit gamemodes in advanced settings (e.g. Classic_Competitive tab), any changes applied to the settings are reset and not applied to 'gamemode_<gamemode>_server'. Things like mp_freezetime get reset to 0 after saving settings

**Comment by lenosisnickerboa** [comment]
This is true for a handful options which are controlled by csgosl. 
They are:
bot_difficulty "3"
bot_quota "4"
mp_buytime "60"
mp_forcecamera "0"
mp_freezetime "0"
mp_friendlyfire "0"
mp_roundtime "5"
mp_warmuptime "10"

These options will be derived from what you select in the csgosl GUI on other config pages. All other settings should be written to the corresponding gamemode_<>_server.cfg file, but ONLY of they are different from the default value in the gamemode_<>.cfg file. I just tried bot_defer_to_human_goals for instance. If you set it to "0" it will be written to the gamemode_<>_server.cfg file, if set to "1" (which is the default in the gamemode_<>.cfg file) it is not written to gamemode_<>_server.cfg.
