### ISSUE TITLE
Using workshop maps makes maxplayers stuck at 64

### ISSUE THREAD

**Issue by patcfly** [lenosisnickerboa/csgosl#60]
On windows version, running any workshop map causes maxplayers to be 64 and cannot be overwritten, as far as I can tell.

**Comment by lenosisnickerboa** [comment]
Just tried it on latest (1.2.4) windows version and it works fine for me. Tested with workshop map http://steamcommunity.com/sharedfiles/filedetails/?id=793266413&searchtext=, set the startmap to 793266413 and started with players set to 2. Everything started up fine with two players.

You're talking about maxplayers, is this the same as players in the csgosl Run tab?

Guess I need more info before I can proceed.

**Comment by lenosisnickerboa** [comment]
No reply, closing.
