### ISSUE TITLE
Error: "no display name and no $DISPLAY environment variable"

### ISSUE THREAD

**Issue by gmask** [lenosisnickerboa/csgosl#61]
This is a fresh Ubuntu 16 Server installation.

```
steam@gameserv:~/csgosl$ ./csgosl.sh
no display name and no $DISPLAY environment variable
    while executing
"load /usr/lib/x86_64-linux-gnu/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.5" script)
    invoked from within
"package require Tk"
    (file "bin/csgosl.tcl" line 6)
```

I have verified that Tk is installed:

```
steam@gameserv:~/csgosl$ sudo apt-get install Tk8.6
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'tk8.6' for glob 'Tk8.6'
tk8.6 is already the newest version (8.6.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by lenosisnickerboa** [comment]
Did you follow the instructions on the wiki?
https://github.com/lenosisnickerboa/csgosl/wiki/Installing%20a%20new%20server

It says you need to perform this command:

sudo apt-get install libtk-img lib32gcc1

I'm having no problems running csgosl on ubuntu16.04. Please let me know if
this helps.

**Comment by gmask** [comment]
@lenosisnickerboa Yes I followed that wiki and have triple-checked that all those are required.

**Comment by lenosisnickerboa** [comment]
Sorry, then I have no idea. Anyone else can help?

**Comment by CJNiiva** [comment]
Can you try to make a new folder called csgosl on your desktop? And download csgosl from there, might work, I had a similiar issue

Sendt fra min iPhone

Den 9. feb. 2017 kl. 22.38 skrev lenosisnickerboa <notifications@github.com<mailto:notifications@github.com>>:

Sorry, then I have no idea. Anyone else can help?

**Comment by gmask** [comment]
Linux servers don't have desktops. I have tried both `wget` and `git clone` to download the repo.

**Comment by Fabolous1** [comment]
Cant get this to work either :( What did you do to fix it

**Comment by dimanscdc** [comment]
Hi All, 
I have the same problem, have Ubuntu 16.04 desktop. Now trying to upgrade to 18.04 and try again. 

@gmask Did you get a solution?

**Comment by gmask** [comment]
@dimanscdc Never did, gave up trying.

**Comment by dimanscdc** [comment]
@gmask I get it working on fresh install of Ubuntu 16.04.01 Desktop version. 

A error of DISPLAY it's ocurred when i try just run the script while i am just connected by ssh to the server by console from remote host. When i access to the desktop of Ubuntu directly with monitor or in my case with proxmox console and run the same script from Ubuntu desktop console i get directly a GUI interface on desktop and a script is still running in console from what i run it.

**Comment by dimanscdc** [comment]
Bad think it's becouse a Ubuntu is locking completly when i start a server and stop accept any connection, all timeout. 
So now i just make a clear install from steamcmd on clear ubuntu server 16.04 version and run server with any problem.

**Comment by elim1234** [comment]
@benjivm This command fixed the problem for me: `export DISPLAY=:0"
