### ISSUE TITLE
can't download maps

### ISSUE THREAD

**Issue by eshabboz** [lenosisnickerboa/csgosl#62]
the server starts and instead of the actual map(bhop_screelee) it starts on dust and it i can't connect to it

**Comment by lenosisnickerboa** [comment]
You're not providing many details.

How did you install the map? Does it show up in csgosl maps view? Can you
select the map in csgosl?

**Comment by eshabboz** [comment]
1.i did everything in this page https://github.com/lenosisnickerboa/csgosl/wiki/Host%20public%20server
2.no
3.no

**Comment by eshabboz** [comment]
1.i did everything on this page https://github.com/lenosisnickerboa/csgosl/wiki/Host-workshop-maps
2.no
3.no

**Comment by eshabboz** [comment]
nvm i read the page again and i saw this "If you host a buggy workshop map which causes the server or connecting clients to crash remove the map folder from /server/csgo/maps/workshop/ and restart csgosl." this aint a buggy map but now i know where is the workshop maps folder and i can put all the maps there. thank you for caring :D

**Comment by lenosisnickerboa** [comment]
Are you on windows or linux? Which csgosl version are you using?

**Comment by lenosisnickerboa** [comment]
Hi again,

Just tried the map on Windows and it worked just fine. All I did was paste
the number 542716028 into the startmap field on the Run tab (used link
http://steamcommunity.com/sharedfiles/filedetails/?id=542716028&searchtext=bhop_screelee).
Then started server and the map was downloaded and I could connect and play.

I then restarted csgosl and then the new map appeared in the Maps tab.

Are you sure you have a proper API auth key pasted into the apiauthkey
field on the Steam tab? This is required to be able to host workshop maps.
You can get a key here:
https://steamcommunity.com/login/home/?goto=%2Fdev%2Fapikey

Let me know if you get it to work or not...

**Comment by eshabboz** [comment]
now that's strange, i could do it by pasting the folder in the workshop directory but i couldn't do it this way :/

**Comment by eshabboz** [comment]
also, what appears when you're downloading?

**Comment by lenosisnickerboa** [comment]
The client says its downloading the map and shows the map picture.

**Comment by eshabboz** [comment]
well thank you for caring :3

**Comment by CJNiiva** [comment]
remember, the map that you are trying to have as a start map, must be downloaded, thats why you should start the server on any (non workshop map) type in console rcon map workshop/xxxxxxx/*mapname* and then let the server download the map, its a common bug with workshop, it will only load dust1 if you havent downloaded the map before hand:)

**Comment by lenosisnickerboa** [comment]
Well, you don't need to download the map prior to starting the server. Just
follow https://github.com/lenosisnickerboa/csgosl/wiki/Host-workshop-maps and
the map will be downloaded when the server is started, It is only csgosl
which needs to be restarted to enable it to find the newly downloaded map.
