### ISSUE TITLE
Fatal error message on hosting server 

### ISSUE THREAD

**Issue by rYDer007** [lenosisnickerboa/csgosl#63]
whenever I try to click on start server I get this error and the bat file exits.
![screenshot 70](https://cloud.githubusercontent.com/assets/9153171/22785600/f0ed9d70-eefa-11e6-9636-02236082f388.png)

**Comment by lenosisnickerboa** [comment]
Hi,

this has nothing to do with csgosl. Try googling the exact error message
you get and you will find the solution.

BR
/Lennart

Den 9 feb. 2017 2:38 em skrev "Ameet Kumar Pradhan" <
notifications@github.com>:

**Comment by lenosisnickerboa** [comment]
Closing, please reopen if you need further assistance.
