### ISSUE TITLE
Wouldn't start a server on my school's network, but would start with a VPN

### ISSUE THREAD

**Issue by longyuxi** [lenosisnickerboa/csgosl#64]
Hello dev,

First of all, thanks for this amazing software! It saves a lot of my time and also helps me test out skins and knives.

My issue is that while using my school's network, it won't start a server unless I connect to a VPN. My school's network blocks gaming websites. Is that the reason why it won't start? Could I start the server even if I connect to a network without internet connection?

Best regards

**Comment by lenosisnickerboa** [comment]
Thanks!

Yes, as far as I know you must have an open internet connection and I would
highly suspect your school is blocking this kind of traffic. VPN to the
rescue :)

Den 21 feb. 2017 2:13 fm skrev "longyuxi" <notifications@github.com>:

**Comment by rishabhc43** [comment]
Well, my college also blocks steam and other gaming sites. But I still use csgosl to host servers on LAN. Even if your school blocks gaming sites, you should be able to start the server. The server may or may not be visible to others in LAN, but that's an other issue. Most probably you will be able to play on LAN in school networks though online is not possible with blocked network

**Comment by lenosisnickerboa** [comment]
Thanks for clarifying rishabhc43, closing.
