### ISSUE TITLE
Run Settings Bug

### ISSUE THREAD

**Issue by rishabhc43** [lenosisnickerboa/csgosl#65]
In Run settings there are few options related with Players & Misc. Some can be filled by giving a value or number while some have tick option(fillwithbots,killcam & friendlyfire). The issue is that when you use fullconfig settings the gamemodes convars are overriden by Run settings convars. For eg. if i don't tick the friendlyfire in Run settings, this will affect in all other modes, from Casual to Training. This makes all other modes to use the same friendlyfire setting as specified in Run mode. This is undesirable in Competitive mode but used in all modes(friendly fire). I faced the same issue with other options where value was used. They also showed same bug. Suppose I set roundtime in Run settings under Misc section as 10 then in all other modes roundtime was 10 after saving the file. So please remove those settings as they are overriding the convars in other modes.

**Comment by lenosisnickerboa** [comment]
csgosl is basically a simplified interface to some of all the billions of
settings available in csgo and is intended for the casual user not willing
to learn about all possible settings. The way csgosl goes about helping the
user is it takes the few basic settings most users are interested in and
pushes them to all the obscure files/vars used to control these options. If
I remove this functionality I can pretty much remove the rest of csgosl as
well. Or do you see some way csgosl can keep simplifying stuff in a smarter
way? If so, please let me know and I will try to implement it.

**Comment by rishabhc43** [comment]
Well I just intend to make all the modes use their default values.
There is a way to simplify those bugs. You can make the fillwithbots, killcam & friendlyfire in Run settings to use numerical values instead of using tick/untick option. Also with the botskill option.
I understand your point and I respect you. I was just trying to point out some bugs. I am a big fan of csgosl as it helps me host servers in my college with great ease.

**Comment by rishabhc43** [comment]
Also, it would be great if  you could incorporate a good deathmatch FFA plugin in csgosl.

**Comment by lenosisnickerboa** [comment]
Yes, that would be one way to do it. I think it will make it a bit more complicated though. I added an [issue](https://github.com/lenosisnickerboa/csgosl/issues/19) for this some time ago. Guess I need some more suggestions on how to make this simple enough to understand.

About the plugin, please add it to [the plugin request list](https://github.com/lenosisnickerboa/csgosl/issues/50) and I will have a look. Please provide a URL for the plugin as well so I can find the correct one.

**Comment by lenosisnickerboa** [comment]
Closing, since this already has an [issue](https://github.com/lenosisnickerboa/csgosl/issues/19) and waiting for the plugin request list to be updated.

**Comment by rishabhc43** [comment]
As I mentioned before, the settings are not being saved to their default values i.e they are being overrided by the options in Run tab. 
So in the next update could u plz remove some of the settings from Run tab...These options are not needed as these are already there in All modes and other modes.
Run settings mode(Under 'Player' Options) - 
remove **botskill and friendlyfire** as these options are already there in othe mode options. Setting them to a value just overrides the value in all other modes and it doesn't get saved to the user set value in that mode even after replacing it with some other value. So let's say I choose friendlyfire to be 1 then it would be reflected in all modes (casual, competitive, dethmatch, etc). So its better to get rid of those options. **One can manually set those values to their needs.**
Also except for ' option' setting in Misc section, no other Setting is required as they posses the same problem. (**killcam, roundtime, warmuptime, buytime freezetime**, )
So I would like to request you to remove these options in next update. Hope you understand. Ty

**Comment by lenosisnickerboa** [comment]
Hi,

Have a look at the latest 1.4 release. I didn't want to remove anything
from the run tab but instead I added an option to disable the writing of
cvars for certain options (the ones you listed). Try it out and let me know
what you think.

/Lennart

**Comment by rishabhc43** [comment]
Thanks man...Appreciate your effort...Its working fine now
