### ISSUE TITLE
different errors on server startup 

### ISSUE THREAD

**Issue by Manni79** [lenosisnickerboa/csgosl#67]
Hello,

I just installed csgosl on my "ubuntu server" edition, with installed xwindows desktop later. I get the following errors.

I read on your issues, that these error should not appear when deactivate sourcemod. I have sourcemod **not** enabled. Any explanation for the different kind of errors?

Screenshot with errors as attachment:
![csgosl_error_on_server_start](https://cloud.githubusercontent.com/assets/26101335/23442181/4cf644a6-fe27-11e6-88af-e7f7a78131f8.png)

Best regards
Manni

**Comment by lenosisnickerboa** [comment]
Hi Manni,

Not sure I understand what problem you are having. or what issues you are referring to regarding " that these error should not appear when deactivate sourcemod". Do you experience any problems except for the error messages when starting the server? I also get a whole bunch of error messages when I start a server but then everything works as expected.

BR
Lennart

**Comment by Manni79** [comment]
Sorry, then I think it's my fault and I have to test it again. By recognize all these errors of missing game types, missing files, unknown cvars, unknown commando... I thought it would not run as expected. But when it's OK to have these errors, then I run some more test next days.

But any idea where all the error come from? Did I install something wrong?

https://github.com/lenosisnickerboa/csgosl/issues/54

> or what issues you are referring to regarding " that these error should not appear when deactivate sourcemod"

I was googling for my errors and found this thread:
https://github.com/lenosisnickerboa/csgosl/issues/54
and on this comment: https://github.com/lenosisnickerboa/csgosl/issues/54#issuecomment-252413838
In this comment are many error of the same kind, not all, but many. And as result of the this, I thought in the thread was speaking of sourcemod problems. So i thought sourcemod could be the reason for the error and I disabled it. 

But again.... when you say that all my errors are normal and fine... than we have **no** open issue. :-)

**Comment by lenosisnickerboa** [comment]
Hi again,

I don't know about all the errors, I just ignore them until I notice
something isn't working. About the issue #54, that was a real problem where
sourcemod had to be updated. I released csgosl 1.1.2 to solve this issue so
if you're just using csgosl of version 1.1.2 or later you should not be
affected by this problem.

Hope it works out for you!
/Lennart

**Comment by lenosisnickerboa** [comment]
Closing, reopen if you have more questions.
