### ISSUE TITLE
Csgo Gun Menu

### ISSUE THREAD

**Issue by IAmsuchNoob** [lenosisnickerboa/csgosl#72]
Hey!

Would be awesome if you could add gun menu into the sourcemod options. I've tried adding it manually but i am to much of a noob to make it work

Big love

**Comment by lenosisnickerboa** [comment]
Just released 1.3.3 containing the GunMenu sourcemod. It is installed with default settings. You need to enable it first in the sourcemod config tab in csgosl.
If you want to change any of the default settings you can do this in the configuration file <your csgosl installation folder>\server\csgo\addons\sourcemod\configs\gunmenu.ini

**Comment by IAmsuchNoob** [comment]
din hjälte! <2

**Comment by lenosisnickerboa** [comment]
:)
