### ISSUE TITLE
Server Fps

### ISSUE THREAD

**Issue by spacecow123** [lenosisnickerboa/csgosl#75]
Is the server fps locked to the tick rate? Is there an option to change from default? 

Thanks!

**Comment by lenosisnickerboa** [comment]
You can control the server tickrate on the Server tab.

From the tooltip:

"Server tickrate, that is the frequency with which the server and
connecting clients communicate. Connecting clients are automatically
instructed to use this frequency."

So csgosl simply takes the value you enter here and pass it on the server
command line with the -tickrate option. For me this means connecting
clients run at 128 fps which is what I want.

Hope that answers your question!


[image: Inline image 1]

**Comment by spacecow123** [comment]
Thanks for the fast reply! So I'm running 128 tick server, but when I check the server console window at the top the fps around 128 there as well. I am because of the recommendation of this article. I would like my server to render at more than 128 fps to lower sv spikes. 
https://support.steampowered.com/kb_article.php?ref=5386-HMJI-5162

**Comment by spacecow123** [comment]
![tick](https://cloud.githubusercontent.com/assets/26336759/23871592/0c12f85e-07f9-11e7-969c-453ff4f33177.PNG)
This is what I'm talking about

**Comment by lenosisnickerboa** [comment]
Hi,

Can't really say I know how to set things properly. I read a couple of
forums where people are making wild guesses so I ended up with the
following setup which works fine for me.

In csgosl you can control the tickrate of your server, default is 128.

csgosl will then set a number of cvars in server.cfg according to the
selected tickrate ($tickRate is the selected tickrate in csgosl):

sv_maxrate 0
sv_minrate 100000
sv_minupdaterate $tickRate
sv_maxupdaterate $tickRate
sv_mincmdrate $tickRate
sv_maxcmdrate $tickRate

I also played around with fps_max but couldn't see a difference when
setting it to e.g. 60 or 300.

Anyhow, using csgosl as described above, clients connecting to the server
get a 128 tickrate and the fps is whatever the client is capable of (I get
around 300 on my PC). I enter "net_grap 1" in the client console to get
client fps, tickrate, ping, ... The server shows both tickrate and fps
around 128.

So, there might certainly be better ways to set this up, I just don't know
how to. If you come up with good settings which somehow work better please
let me know so I can improve csgosl.

/Lennart

**Comment by spacecow123** [comment]
Ok ill keep doing some research and get back to you if I find anything.
