### ISSUE TITLE
After the upgrade the server does not start any more

### ISSUE THREAD

**Issue by Guihs1** [lenosisnickerboa/csgosl#76]
Nothing was modified, just updated as recommended and does not start the server, in the tasks of windows it shows that there is an open console instance (with the name of the server) but does not appear this console nor the server in the active list.

**Comment by lenosisnickerboa** [comment]
Have you tried rebooting windows? Could be a lingering old server process. Close to 100 downloads of version 1.5 and no other complaints about problems upgrading. If reboot doesn't solve it, could you provide a screen shot showing csgosl, taskwindow and any open consoles?

**Comment by Guihs1** [comment]
I made sure not to be another process not closed, I rebooted windows to be sure.
The only way to resolve it was by re-installing everything and deleting the files that were being used.
But now it is resetting, the whole new map is overwritten the CFG I made is reset and the server takes the local configuration (usually the classic competitive) and ignores any cfg I'm trying to use.
I do not know what it can be, everything is defaulted, only a cfg with parameters is executed and it is zeroed: /

**Comment by lenosisnickerboa** [comment]
Did everything work before the update?
Are you editing cfg-files directly or are you only changing stuff via
csgosl GUI?
Maybe you can provide pictures showing the problem?

**Comment by Guihs1** [comment]
It happens when I click the "csgosl" VBScript file, and nothing happens when I click "OK"
![image](https://cloud.githubusercontent.com/assets/10941548/24020337/7569aa9a-0a7a-11e7-91ad-32897a668348.png)

**Comment by lenosisnickerboa** [comment]
This issue is fixed in new release 1.6
