### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Bog12555** [lenosisnickerboa/csgosl#78]
After i updated server to latest csgo and csgosl to latest version, when i try to start csgosl appears this:

![1](https://cloud.githubusercontent.com/assets/26150024/24061383/e9679084-0b5f-11e7-8ecb-69a54c78783c.png)

**Comment by lenosisnickerboa** [comment]
Did you just add a new map prior to getting this fault? If a new map is added which has a .jpg file (map image file) which csgosl fails to read this error will happen. So a quick workaround is to either delete the just added map or replace the .jpg file for that map with a .jpg file for some other map which is working. 

Meanwhile I will fix the error handling so if this occurs csgosl will simply show a "no image available" picture for maps it can't read an image from.

**Comment by Bog12555** [comment]
I think it is from the map "The canals" which has been added to csgo recently

**Comment by lenosisnickerboa** [comment]
Fixed in release 1.6 (you will get a default image for the canals image until I sort this out)
