### ISSUE TITLE
Sourcemod Enabling

### ISSUE THREAD

**Issue by Phlonk** [lenosisnickerboa/csgosl#80]
I am new to CSGOSL so please be patient.

After a new installation following the guide, am I required to unzip the "mods.zip" folder into the "CSGO" root directory to have it installed? ( I did this since I did not see an "addons" folder )

Once I did this it seems that if I enable or disable using the CSGOSL interface it makes no difference on the server. I am trying to only have 2 plugins working currently "Nextmap & Randomcycle" but after match ends it still comes up with voting option.

I apologise if this sounds stupid, but I have googled and couldn't find anything.

Thanks for any help ahead of time.

**Comment by Phlonk** [comment]
After unzipping "mods.zip" and looking in the advanced tabs I got it working.

Thanks a ton for this application, I would not have setup a server in such a short time without it.

**Comment by lenosisnickerboa** [comment]
Great you got it working. But you don't need to unzip mods yourself, csgosl
does that for you. All you need to do is enable stuff in the sourcemod tab
in csgosl.

Den 30 mars 2017 4:26 fm skrev "Phlonk" <notifications@github.com>:
