### ISSUE TITLE
Steam API domain name?

### ISSUE THREAD

**Issue by NaPz2017** [lenosisnickerboa/csgosl#81]
To use custom maps you need the steam API key, but this site needs a domain name...  What domain name? Or am I looking in the wrong place?

**Comment by lenosisnickerboa** [comment]
What is "this site" ? You should be fine with just the API key.

**Comment by NaPz2017** [comment]
By "this site" I meant the link you gave in the how to set up a server, under the workshop csgo maps part

**Comment by lenosisnickerboa** [comment]
Sorry, I can't anything on domains on the csgosl wiki. Can you provide a link to the page where you find this information about domains?

**Comment by NaPz2017** [comment]
https://github.com/lenosisnickerboa/csgosl/wiki/Host-workshop-maps where it says "Steam Registration page" that's the link I followed...

**Comment by lenosisnickerboa** [comment]
Ah now I see. I didn't remember the domain part. I have a domain which I entered here but according to http://steamcommunity.com/app/4000/discussions/1/558752450986071551/ it should be ok to just enter the server IP address here. Have you tried that? Not sure if it has to be the external IP address? (use https://www.whatismyip.com find your external IP). 

Please comment here again how it worked out for you so I can update the wiki.

**Comment by NaPz2017** [comment]
Okay great! I made my own map and was thinking of making a little server for my friends so we can play it with equal ping, and I love csgosl because of it simplicity! Keep up the good work and great tech support ;)

**Comment by lenosisnickerboa** [comment]
Thanks! Just saw this stating about the same; [about domain name](https://github.com/Jessecar96/SteamBot/issues/158). I will update the wiki as well.
