### ISSUE TITLE
Color problem on Kubuntu 16.04

### ISSUE THREAD

**Issue by Keplyx** [lenosisnickerboa/csgosl#83]
![screenshot_20170418_183528](https://cloud.githubusercontent.com/assets/23726131/25142061/e44edd68-2465-11e7-99c6-a5d6f52d8f68.png)

Not a big deal, but as you see in the screenshot, the colors don't match with the desktop customization.
It doesn't bother me much but if you have time someday maybe you could fix that?

**Comment by lenosisnickerboa** [comment]
I'll have a look. I have some hardcoded colors here and there in csgosl. I haven't played around with desktop customization in ubuntu, run stock colors everywhere. Where do I change colors to reproduce the problems you have above?

**Comment by Keplyx** [comment]
Well, I don't know if this is possible in Ubuntu, because I only use Kubuntu (which has a lot more personalization options).
Never used Ubuntu, but you could try to search for custom color scheme tools

**Comment by Keplyx** [comment]
Found how to fix this. You have to **unselect "apply colors to non-Qt apps" under "color settings"**
Here's a screenshot (in french sorry):
![spectacle nns487](https://user-images.githubusercontent.com/23726131/27453601-55e32a88-5797-11e7-9dbf-3666278d0d33.png)

So here's how it looks now:
![spectacle tj1558](https://user-images.githubusercontent.com/23726131/27453683-95c9f8c0-5797-11e7-8699-ef51f447df44.png)

and as you can see, I have custom colors in the rest of the computer.

So @lenosisnickerboa, you don't have to do anything about this, it was a problem on my side!
