### ISSUE TITLE
The latest update broke metamod

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#85]
https://www.reddit.com/r/GlobalOffensive/comments/67r04q/psa_server_owners_update_to_the_latest_metamod/?st=j20he93i&sh=b6f60b02

**Comment by lenosisnickerboa** [comment]
Yup, tried updating to latest sourcemod (5985)/metamod (956) and still the server crashes in both Linux/Windows. Also tried latest sourcemod dev build 6080, also crashes. I read the link you provided and it seems some claim they get it to work but they had to reinstall the server from scratch?!?
Don't have time right now to troubleshoot, any hints appreciated...

**Comment by lenosisnickerboa** [comment]
Nah, just realized I didn't rebuild properly. Verified it working on both linux/windows. New release coming...

**Comment by lenosisnickerboa** [comment]
Release 1.8.3 out.
