### ISSUE TITLE
"wrong # args: should be 'RunMapGroupChanged value'" on Server Start

### ISSUE THREAD

**Issue by nwLSteam** [lenosisnickerboa/csgosl#86]
<img width="347" alt="bcb6f75a011f4916b3a01a58f7d3bfe7" src="https://cloud.githubusercontent.com/assets/25863799/26002945/8a26ba66-3731-11e7-8bac-44b57db4c990.png">

**Comment by lenosisnickerboa** [comment]
Just guessing, do you have a map group name with spaces in it? If so,
remove that mapgroup and recreate without spaces

**Comment by nwLSteam** [comment]
CSGOSL won't start at all, so I can't remove the mapgroup. Where's the config file?

**Comment by lenosisnickerboa** [comment]
AFK but look for a cfg folder in the csgosl folder and remove (or move)
mapgroups.cfg (or something like it). Then start csgosl and you should be
good to go.

**Comment by lenosisnickerboa** [comment]
Haven't heard anything more, closing. Please reopen if issue still exists.
