### ISSUE TITLE
Server name with spaces drops everything after first word

### ISSUE THREAD

**Issue by abshkd** [lenosisnickerboa/csgosl#88]
If I put something like `My Awesome Server`
the server name that finally shows up is only `My`
At which point does the csgosl set the server name. .perhaps I can fix it. thanks

**Comment by lenosisnickerboa** [comment]
Thanks for pointing this out, just confirmed the bug on linux. Windows
works. Will fix this tomorrow.

**Comment by lenosisnickerboa** [comment]
Took a while but it's fixed now.
