### ISSUE TITLE
package require Tk

### ISSUE THREAD

**Issue by weteamsteve** [lenosisnickerboa/csgosl#89]
Still getting the same error as the other guy, anybody able to help?

> steam@gameserv:~/csgosl$ ./csgosl.sh
> no display name and no $DISPLAY environment variable
>     while executing
> "load /usr/lib/x86_64-linux-gnu/libtk8.6.so Tk"
>     ("package ifneeded Tk 8.6.5" script)
>     invoked from within
> "package require Tk"
>     (file "bin/csgosl.tcl" line 6)

**Comment by lenosisnickerboa** [comment]
Closing, nothing has happened for a long time. Reopen if this is still an issue.
