### ISSUE TITLE
Investigate better way to kill linux csgo server

### ISSUE THREAD

**Issue by lenosisnickerboa** [lenosisnickerboa/csgosl#9]
Gives a lot of warnings about files not being closed. Consider e.g. using screen

Connected to other issue about supporting multiple servers on one host.

**Comment by spot88** [comment]
screen is the best way tbh. Take a look at this: http://www.bgpanel.net/

**Comment by lenosisnickerboa** [comment]
Yes, I have considered screen, may be a candidate, thanks for the hint.
Didn't realle get the connection to bgpanel though, does it use screen?
Den 10 maj 2016 12:00 skrev "spot88" <notifications@github.com>:

**Comment by spot88** [comment]
Yes it uses screen :)

**Comment by lenosisnickerboa** [comment]
This issue also goes for windows servers, should try to use some nicer way to close down. Possible to send some kind of "quit" command srcds?

**Comment by lenosisnickerboa** [comment]
Current (new) method seems to work just fine, warnings are gone.
