### ISSUE TITLE
what are the basic system requirements for hosting CSGO dedicated server

### ISSUE THREAD

**Issue by dev-kill3r** [lenosisnickerboa/csgosl#90]
Please help me what are the basics system requirements to host a lagg free server

**Comment by CJNiiva** [comment]
It depends on how many players there are on the server and or if you have bots on the server, tickrate etc, I dont think the req is too high without bots though, but its alot higher if you are planning to play on the same pc

Sendt fra min iPhone

Den 7. jun. 2017 kl. 14.14 skrev dev-kill3r <notifications@github.com<mailto:notifications@github.com>>:


Please help me what are the basics system requirements to host a lagg free server

**Comment by lenosisnickerboa** [comment]
I just tried googling "counter strike go server requirements" and some hints pop up here and there. But as CJNiiva said it's very dependent on how you are going to use it.

**Comment by lenosisnickerboa** [comment]
Closing, nothing further...
