### ISSUE TITLE
GOTV Page BUGs

### ISSUE THREAD

**Issue by jayderfranca** [lenosisnickerboa/csgosl#91]
The GOTV page is not saving the changes in server.cfg and does not recognize the new variables.

The tv_autorecord variable may conflict when the Warmod plugin is active.

**Comment by lenosisnickerboa** [comment]
Hi,

Sorry for missing your email but I'm currently very busy being on vacation
and will be for another 2 weeks :) I'll get back to you.

BR
Lennart

**Comment by jayderfranca** [comment]
Hello, 
No problem .... I submitted a proposal to fix the BUG.

Regards,
Jayder França

**Comment by lenosisnickerboa** [comment]
Thanks @jayderfranca! I have finally released a fix for the gotv issues (based on your patch). Also upgraded sourcemod/metamod. Enjoy!
