### ISSUE TITLE
Not taking settings/cvars

### ISSUE THREAD

**Issue by primaesport** [lenosisnickerboa/csgosl#93]
Hi!

I have setup a server using your application and trying to run a Arena (multi 1vs1).

Problem 1)
The server runs fine , but it's not accepting the changes that I make in the application.
For example servername and those work fine, but the gametyp doesn't.
I've set it to Custom and changed the freezetime and stuff, nothing happends.
Tried restarting the server (both application and the whole machine).

So I tried going "full config" and editing it, and it still won't work.
It won't take the changes that I make.

Problem 2)
And also - the multi1vs1 spawn with all nades. How do I make it so it doesn't?
I tried running the mp_buy_allow_grenades 0 but the players still spawn with HE, Molotov and smoke.
I even tried changing the file that controls the settings for customgame, but it still won't take the changes.

Problem 3)
It always spawn bots altough I've set the bot_quota to 0 and "normal" (not fill)

**Comment by lenosisnickerboa** [comment]
On vacatio for another werk. Will look into this when I'm back. Stay
tuned...

**Comment by primaesport** [comment]
OK! hanging on :)

**Comment by lenosisnickerboa** [comment]
So, I'm back. Do you have the same problem without the 1v1 mod? I.e. if you start an arms race game do you get the same problems with not being able to save? Or is it just when you run the 1v1 mod? 
Also, is it just when you select game mode "Custom"? Does e.g. arms race work?

**Comment by primaesport** [comment]
Hi!

First of all I got a notification that version 2.1 was available, so I updated the application first.

I just tried setting up an “arms race”-game and I set startmoney to 999 and bots to 5 (fillwithbots non checked).
The game still started with 9 bots (I then realized that the money in armsrace isn’t used at all).

So I started a classic competitive on de_train
Players 12 – bots 5 (fillwithbots not checked)
Warmuptime set to 0
Freezetime set to 3
Startmoney 999

Started server and joined… Full warmup time (5 minutes) and full team with bots (maybe because it’s competitive)
But startmoney is still 800.

Did a restart and for some reason multi1vs1 was still loaded although I clicked classic competitive.
Restarted the server with the multi1vs1 unchecked again - Now it took the 999 settings on startmoney

I then activated fullconfig again (and restarted the server), clicked the “Run”.
Gamemodetype Custom
Bots 5 (fillwithbots not checked)
Warmuptime 0
Freezetime 3

Under tab “custom” I set the following:
Mp_timelimit 10
Ammo_grenade_limit_Flashbang 1
Ammo_grenade_limit_total 0

So – there shouldn’t be any nades …
Warmup is still 5 minutes
Freezetime 15 sec
Game says 0 opponent but bots are in the game
Second round me and a bot spawned in the same location (same team as well)

So I tried setting freezetime 0 and clicked “saved all settings”.. it directly reverted it into 3.
(but no nades so far) …

I’m so confused ☹

/Martin


Från: lenosisnickerboa [mailto:notifications@github.com]
Skickat: den 8 juli 2017 23:00
Till: lenosisnickerboa/csgosl <csgosl@noreply.github.com>
Kopia: Martin Mårtensson <martin@prima-esport.se>; Author <author@noreply.github.com>
Ämne: Re: [lenosisnickerboa/csgosl] Not taking settings/cvars (#93)


So, I'm back. Do you have the same problem without the 1v1 mod? I.e. if you start an arms race game do you get the same problems with not being able to save? Or is it just when you run the 1v1 mod?
Also, is it just when you select game mode "Custom"? Does e.g. arms race work?

**Comment by lenosisnickerboa** [comment]
I'll be away a couple of days again, vacation times...

Meantime I would suggest trying a total reinstall in a new directory. You
can of course keep the old installation in case you want to go back.

Then start out with all default settings and start out changing one or a
few settings at a time (e.g start with just game mode and bot count) to
make sure you get the basics working first. Then change some more until you
either run into the same problems or it actually works. If you manage to
reproduce the problem you will know what caused the problem and maybe I can
fix the bug if there is one.

Good luck!
/Lennart

**Comment by lenosisnickerboa** [comment]
Any progress? Closing, reopen if still a problem.
