### ISSUE TITLE
steamcmd.zip: No such file or directory

### ISSUE THREAD

**Issue by Wickfer** [lenosisnickerboa/csgosl#94]
Hi, I have problem with instaling csgosl server on Windows.
Starting instaling it momentally get me a crash (crash1.log)
After I put steamcmd.zip file in that folder it get me another crash (crash2.log)

How do I fix it?

[logs.zip](https://github.com/lenosisnickerboa/csgosl/files/1141914/logs.zip)

**Comment by lenosisnickerboa** [comment]
I see you have spaces in the installation path. Some people have problems with this (and most don't strangely enough). It is mentioned here: [Troubleshooting](https://github.com/lenosisnickerboa/csgosl/wiki/Troubleshooting)

Anyway, just try creating a new folder in a path without spaces, e.g. D:\csgosl, and follow the instructions [here](https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server)

**Comment by lenosisnickerboa** [comment]
No answer, closing.
