### ISSUE TITLE
Steam Gameserver Account Token not being recognized

### ISSUE THREAD

**Issue by FPSEMAJ** [lenosisnickerboa/csgosl#95]
I have created a Gameserver Account Token and put it in the appropriate place under the steam tab... but when I launch the server, it says that "No steam account token was specified." Please inquire for more information.

**Comment by CJNiiva** [comment]
Set the server to no lan mode on the csgosl client

Sendt fra min iPhone

Den 18. jul. 2017 kl. 04.41 skrev FPSEMAJ <notifications@github.com<mailto:notifications@github.com>>:


I have created a Gameserver Account Token and put it in the appropriate place under the steam tab... but when I launch the server, it says that "No steam account token was specified." Please inquire for more information.

**Comment by FPSEMAJ** [comment]
Thank you so very much CJNiiva, this fixed my issue. Funny thing is, I did this before, then reset my settings when it didn't work and put everything back again but I forgot that one setting. Thank you very much.
