### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by FPSEMAJ** [lenosisnickerboa/csgosl#96]
Thanks again to CJNiiva for fixing my previous issue, now I can connect to the server from the internet. But now, when I get in the server, the map ends and it moves to the next one. When I spawn in, I am frozen but the bots around me move to the objective. The scoreboard appears and it says, "Next Map in 3..." and it repeats.
Another issue that may or may not be realated, when I try to use Rcon from the Csgosl client, it says "(couldn't open socket: connection refused)"
Apologies for all the issues 🤷‍♂️ 

*UPDATE*
After telling my friend about the server problem I invited them on so they could see for themselves, and the server worked just fine. However the issue with the Rcon from Csgosl client still presists

**Comment by lenosisnickerboa** [comment]
Can you use rcon from the same machine you run csgosl on if you connect via the csgo client (the game console)?
Are you running csgosl on windows? It may be the windows firewall (or some other firewall you have installed) which is blocking the connection. The first time you try to connect from the csgosl client the firewall may ask if it should block or not (depending on your kind of firewall and the firewall config). Do you remember such a question?
Anyhow it may be a good idea to completely disable the firewall and see if that makes it work.

**Comment by FPSEMAJ** [comment]
I connect to my server using the same machine I host it with. I am on Windows 10 64 bit. And I remember the firewall question and allowed it to function on all networks, I will proceed to test with turning off the firewall.

**Comment by lenosisnickerboa** [comment]
Any progress? Closing, reopen if still not working.
