### ISSUE TITLE
warmod.smx is corrupted

### ISSUE THREAD

**Issue by jayderfranca** [lenosisnickerboa/csgosl#97]
The file from url  http://warmod.bitbucket.org/plugins/warmod.smx is corrupted. The original url https://warmod.bitbucket.io/plugins/warmod.smx its ok.

**Comment by lenosisnickerboa** [comment]
Do you mean it is corrupt in the latest release, i.e. the warmod plugin can't be used or is it just the link which has changed since I built the latest release? Just so I know if I need to create a new release?

**Comment by lenosisnickerboa** [comment]
Pulled your commit, please let me know if you think we need a new release or not.

**Comment by jayderfranca** [comment]
Warmod plugin for that url can't be used, with "bad header" error in log of server. The size of plugin on url  http://warmod.bitbucket.org/plugins/warmod.smx is smaller, compared with https://warmod.bitbucket.io/plugins/warmod.smx.

I think it's interesting to launch a release to update those who already downloaded version 2.1.

**Comment by lenosisnickerboa** [comment]
Just released 2.1.1 with the fixed warmod plugin. Thanks!

**Comment by jayderfranca** [comment]
Great!! :)
