### ISSUE TITLE
Even after updating from 2.1.0 to 2.1.1, its keeps prompting for "update is available"

### ISSUE THREAD

**Issue by salmanhasni** [lenosisnickerboa/csgosl#99]

**Comment by lenosisnickerboa** [comment]
Just confirmed the problem on windows. It seems the update to 2.1.1 fails, I'm still running the old 2.1 version after the update so the real problem seems to be failure to update. The check is actually correct. 

Are you running windows or linux?

**Comment by lenosisnickerboa** [comment]
Just released 2.1.2 with a fix. Please let me know if this fixes the problem.

**Comment by lenosisnickerboa** [comment]
Closed, fixed and no response.
